##########################################################################
# PROGRAM:  NISPUF07.R                                                   #
#                                                                        #
# PURPOSE:  THIS R PROGRAM CREATES A PERMANENT R DATASET                 #
#                FROM THE 2007 NIS PUBLIC USE ASCII FILE                 #
#                                                                        #
# NOTES:    THIS PROGRAM IS DIVIDED INTO SEVEN STEPS AS FOLLOWS:         #
#           		                                                 #
# STEP 1:   LOAD AN R PACKAGE AND ASSIGN FILE NAMES			 #
#                                                                        #
#		 ONE R PACKAGE FOR TWO FUNCTIONS (CONTENTS, WTD.TABLE)   #
#		 WILL BE LOADED			  			 #
#		 THE USER CAN ENTER THE PATH TO THE ASCII DATA FILE AND	 #
#		 THE PATH WHERE THE R DATASET WILL BE CREATED 		 #
#                                                                        #
# STEP 2:   CREATE FORMATS                                               #
#                                                                        #
# STEP 3:   READ THE FLAT DATA FILE                                      #
#                                                                        #
# STEP 4:   ASSIGN VARIABLE LABELS                                       #
#                                                                        #
# STEP 5:   CREATE A PERMANENT R DATASET				 #
#                                                                        #
# STEP 6:   ASSIGN FORMATS                                               #
#                                                                        #
#	 FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES IN R	 #
#                                                                        #
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE        #
#                                                                        #
##########################################################################

##########################################################################
# Step 1:   LOAD R PACKAGES AND ASSIGN FILE NAMES                        #
##########################################################################
library(Hmisc) #TO USE contents()

#---USE SLASH(/) TO SEPERATE A FILE PATH---#
PUF <- "path-to-data" 

flatfile <- "path-to-file/NISPUF07.DAT"




##########################################################################
# Step 2:   CREATE FORMATS                                               #
##########################################################################

AGECPOXRlevels=c(1,2,3,4)
AGECPOXRlabels=c("0 TO 6 MONTHS OLD", "7 TO 12 MONTHS OLD", "13 TO 18 MONTHS OLD","19+ MONTHS OLD")

AGEGRPlevels=c(1,2,3)
AGEGRPlabels=c("19 - 23 MONTHS", "24 - 29 MONTHS", "30 - 35 MONTHS")

C1Rlevels=c(1,2,3,4,5,6,7,8)
C1Rlabels=c("1", "2", "3", "4", "5", "6", "7", "8+")

C5Rlevels=c(1,2,3,4,77,99)
C5Rlabels=c("MOTHER (STEP, FOSTER, ADOPTIVE) OR FEMALE GUARDIAN", "FATHER (STEP, FOSTER, ADOPTIVE) OR MALE GUARDIAN", 
"GRANDPARENT", "OTHER FAMILY MEMBER/FRIEND", "DON'T KNOW", "REFUSED")

CDTPlevels=c(1,2,3,4,5)
CDTPlabels=c("UTD DTP / SC", "NOT UTD DTP / SC","UTD DTP / NSC",
"NOT UTD DTP / NSC","MISSING / SC / NSC")

CENREGlevels=c(1,2,3,4)
CENREGlabels=c("NORTHEAST", "MIDWEST", "SOUTH", "WEST")

CHEPlevels=c(1,2,3,4,5)
CHEPlabels=c("UTD HEPB / SC", "NOT UTD HEPB / SC", "UTD HEPB / NSC",
"NOT UTD HEPB / NSC", "MISSING / SC / NSC")

CHIBlevels=c(1,2,3,4,5)
CHIBlabels=c("UTD HIB / SC", "NOT UTD HIB / SC", "UTD HIB / NSC",
"NOT UTD HIB / NSC", "MISSING / SC / NSC")

CHILDNMlevels=c(1,2,3,77,99)
CHILDNMlabels=c("ONE", "TWO OR THREE", "FOUR OR MORE", "DON'T KNOW", "REFUSED")

D6Rlevels=c(0,1,2,3)
D6Rlabels=c("0", "1", "2", "3+")

CMMRlevels=c(1,2,3,4,5)
CMMRlabels=c("UTD MCV / SC", "NOT UTD MCV / SC", "UTD MCV / NSC",
"NOT UTD MCV / NSC", "MISSING / SC / NSC")

CPOLlevels=c(1,2,3,4,5)
CPOLlabels=c("UTD POL / SC", "NOT UTD POL / SC",  "UTD POL / NSC",
"NOT UTD POL / NSC", "MISSING / SC / NSC")

CVRClevels=c(1,2,3,4,5)
CVRClabels=c("UTD VRC / SC", "NOT UTD VRC / SC",  "UTD VRC / NSC",
"NOT UTD VRC / NSC", "MISSING / SC / NSC")

CWIClevels=c(1,2,3,77,99)
CWIClabels=c("YES", "NO", "NEVER HEARD OF WIC",
"DON'T KNOW", "REFUSED")

D6Rlevels=c(0,1,2,3)
D6Rlabels=c("0", "1", "2", "3+")

DISPlevels = c(1,2,3,4,5,6,7,8,9,10,11)
DISPlabels = c("COMPLETE PROVIDER INFO, NO PROBLEMS", "COMPLETE PROVIDER INFO, NO SHOT CARD",
"COMPLETE PROVIDER INFO, POOR HISTORY", "COMPLETE PROVIDER INFO, POOR HIST/OTHER",
"INCOMPLETE PROVIDER RESP, BUT 4:3:1:3:3 INDICATED", "INCOMPLETE PROVIDER RESP, INFO MATCHES",
"INCOMPLETE PROVIDER RESP, HISTORY UNKNOWN", "INCOMPLETE PROVIDER RESP, 4:3:1:3:3 WITH RDD",
"INCOMPLETE PROVIDER RESP, MATCHES RDD", "INCOMPLETE PROVIDER RESP, RDD NOT EXACT",
"INCOMPLETE PROVIDER RESP, RDD WITHOUT SHOT CARD")

EDUC1_levels=c(1,2,3,4,77,99)
EDUC1_labels=c("< 12 YEARS", "12 YEARS", "> 12 YEARS, NON-COLLEGE GRAD",
"COLLEGE GRAD", "DON'T KNOW", "REFUSED")

ESTIAPlevels=c(1,2,4,5,6,7,8,10,11,12,13,14,16,17,18,19,20,22,24,25,27,28,29,30,31,34,35,36,37,38,40,41,44,46,47,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,68,69,72,73,74,75,76,77,79,80,773)

ESTIAPlabels=c("CT",
 "MA",
 "ME",
 "NH",
 "RI",
 "VT",
 "NJ",
 "NY-REST OF STATE",
 "NY-CITY OF NEW YORK",
 "DISTRICT OF COLUMBIA",
 "DE",
 "MD",
 "PA-REST OF STATE",
 "PA-PHILADELPHIA COUNTY",
 "VA",
 "WV",
 "AL",
 "FL-REST OF STATE",
 "FL-DADE COUNTY",
 "GA",
 "KY",
 "MS",
 "NC",
 "SC",
 "TN",
 "IL-REST OF STATE",
 "IL-CITY OF CHICAGO",
 "IN-REST OF STATE",
 "IN-MARION COUNTY",
 "MI",
 "MN",
 "OH",
 "WI",
 "AR",
 "LA",
 "NM",
 "OK",
 "TX-REST OF STATE",
 "TX-DALLAS COUNTY",
 "TX-EL PASO COUNTY",
 "TX-CITY OF HOUSTON",
 "TX-BEXAR COUNTY",
 "IA",
 "KS",
 "MO",
 "NE",
 "CO",
 "MT",
 "ND",
 "SD",
 "UT",
 "WY",
 "AZ",
 "CA-REST OF STATE",
 "CA-LOS ANGELES COUNTY",
 "HI",
 "NV",
 "AK",
 "ID",
 "OR",
 "WA-REST OF STATE",
 "CA-ALAMEDA COUNTY",
 "CA-SAN BERNARDINO COUNTY",
 "WA-WESTERN WASHINGTON"
)

FLUUTDlevels=c(1,2,3)
FLUUTDlabels=c("VACCINATED","NOT VACCINATED","NOT ELIGIBLE")

FRSTBRNlevels=c(1,2,77,99)
FRSTBRNlabels=c("NO", "YES", "DON'T KNOW", "REFUSED")

HASPDA2Flevels=c(1,2)
HASPDA2Flabels=c("CHILD HAS ADEQUATE PROVIDER DATA OR ZERO VACCINATIONS",
"CHILD DOES NOT HAVE ADEQUATE PROVIDER DATA")

HEPBRTlevels=c(1,2)
HEPBRTlabels=c("AT LEAST ONE PROVIDER CHECKED GIVEN AT BIRTH",
"NO PROVIDERS CHECKED GIVEN AT BIRTH")

HEPFLGlevels=c(1,2)
HEPFLGlabels=c("HEPB BIRTH SHOT DATE IMPUTED FROM SHOTCARD",
"HEPB BIRTH SHOT DATE IMPUTED FROM DISTRIBUTION OF BIRTH DOSE DATES")

HHNUMlevels=c(0,1,50,77,99)
HHNUMlabels=c("NONE", "AT LEAST ONE", "ALL","DON'T KNOW","REFUSED")

HISPlevels=c(1,2,3,4,5)
HISPlabels=c("HISPANIC","NON-HISPANIC","OTHER","DON'T KNOW","REFUSED")

INCPOVlevels=c(1,2,3,4)
INCPOVlabels=c("ABOVE POVERTY, > $75K", "ABOVE POVERTY, <= $75K",
"BELOW POVERTY", "UNKNOWN")

INCQ298Alevels=c(3,4,5,6,7,8,9,10,11,12,13,14,77,99)
INCQ298Alabels=c("$0 - $7500", "$7501 - $10000", "$10001 - $17500",
"$17501 - $20000", "$20001 - $25000", "$25001 - $30000", "$30001 - $35000",
"$35001 - $40000", "$40001 - $50000", "$50001 - $60000", "$60001 - $75000",
"$75001+", "DON'T KNOW", "REFUSED")

INOPHONRlevels=c(1,2,3)
INOPHONRlabels=c("7 TO 14 DAYS", "15 TO 30 DAYS", "31 TO 365 DAYS")

LANGUAGElevels=c(1,2,3)
LANGUAGElabels=c("ENGLISH", "SPANISH", "OTHER")

MAGEGRPlevels=c(1,2,3,77,99)
MAGEGRPlabels=c("<= 19 YEARS", "20 - 29 YEARS", ">= 30 YEARS", 
"DON'T KNOW", "REFUSED")

MAR_PUFlevels=c(1,2,3)
MAR_PUFlabels=c("WIDOWED/DIVORCED/SEPARATED/DECEASED", 
"NEVER MARRIED", "MARRIED")

MOBILlevels=c(1,2,77,99)
MOBILlabels=c("MOVED FROM DIFFERENT STATE", "DID NOT MOVE FROM DIFFERENT STATE",
"DON'T KNOW", "REFUSED")

PROVIDlevels=c(1,2,3,4,5,6,7)
PROVIDlabels=c("ALL PUBLIC FACILITIES", "ALL HOSPITAL FACILITIES", 
"ALL PRIVATE FACILITIES", "ALL MILITARY/OTHER FACILITIES", "MIXED", 
"TYPE OF PROVIDER UNKNOWN", "ALL WIC CLINIC PROVIDERS")

RACEETHKlevels=c(1,2,3,4)
RACEETHKlabels=c("HISPANIC", "NON-HISPANIC WHITE ONLY", 
"NON-HISPANIC BLACK ONLY", "NON-HISPANIC OTHER + MULTIPLE RACE")

RACE_PUFlevels=c(1,2,3)
RACE_PUFlabels=c("WHITE ONLY", "BLACK ONLY", "OTHER + MULTIPLE RACE")

REGISTRYlevels=c(1,2,3,4)
REGISTRYlabels=c("ALL PROVIDERS", "SOME BUT POSSIBLY OR DEFINITELY NOT ALL PROVIDERS",
"NO PROVIDERS", "UNKNOWN/DON'T KNOW")

SCUTDlevels=c(1,2,77,88,99)
SCUTDlabels=c("UTD/SC","NOT UTD/SC", "DON'T KNOW", "UNKNOWN", "REFUSED")

SEXlevels=c(1,2,77,99)
SEXlabels=c("MALE", "FEMALE", "DON'T KNOW", "REFUSED")

SHOTCARDlevels=c(1,2)
SHOTCARDlabels=c("SHOTCARD", "NO SHOTCARD")

STATElevels=c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56)
STATElabels=c(
"ALABAMA", 
"ALASKA", 
" ", 
"ARIZONA", 
"ARKANSAS", 
"CALIFORNIA", 
" ", 
"COLORADO", 
"CONNECTICUT", 
"DELAWARE", 
"DISTRICT OF COLUMBIA", 
"FLORIDA", 
"GEORGIA", 
" ", 
"HAWAII", 
"IDAHO", 
"ILLINOIS", 
"INDIANA", 
"IOWA", 
"KANSAS", 
"KENTUCKY", 
"LOUISIANA", 
"MAINE", 
"MARYLAND", 
"MASSACHUSETTS", 
"MICHIGAN", 
"MINNESOTA", 
"MISSISSIPPI", 
"MISSOURI", 
"MONTANA", 
"NEBRASKA", 
"NEVADA", 
"NEW HAMPSHIRE", 
"NEW JERSEY", 
"NEW MEXICO", 
"NEW YORK", 
"NORTH CAROLINA", 
"NORTH DAKOTA", 
"OHIO", 
"OKLAHOMA", 
"OREGON", 
"PENNSYLVANIA", 
" ", 
"RHODE ISLAND", 
"SOUTH CAROLINA", 
"SOUTH DAKOTA", 
"TENNESSEE", 
"TEXAS", 
"UTAH", 
"VERMONT", 
"VIRGINIA", 
" ", 
"WASHINGTON", 
"WEST VIRGINIA", 
"WISCONSIN", 
"WYOMING")

UTDlevels=c(0,1)
UTDlabels=c("NOT UTD", "UTD")

Ylevels=c(1)
Ylabels=c("YES")

YNlevels=c(1,2)
YNlabels=c("YES", "NO")

YNDKRFlevels=c(1,2,77,99)
YNDKRFlabels=c("YES", "NO", "DON'T KNOW", "REFUSED")

YNDKUKRFlevels=c(1,2,77,88,99)
YNDKUKRFlabels=c("YES","NO", "DON'T KNOW", "UNKNOWN","REFUSED")

DTTYPElevels=c("1", "2", "3", "4", "5", "7", "8")
DTTYPElabels=c("DT", "DTP","DTP-UNKNOWN", "DTAP","DTP-HIB", "DTAP-HIB", "DTAP-HEPB-IPV")

POLIOTYPElevels=c("8", "20", "21", "22")
POLIOTYPElabels=c("DTAP-HEPB-IPV", "OPV", "IPV", "POLIO-UNKNOWN")

MEASLESTYPElevels=c("30", "31", "32", "33", "MM", "VM")
MEASLESTYPElabels=c("MMR", "MEASLES ONLY", "MEASLES-MUMPS", "MEASLES-RUBELLA", "MCV-UNKNOWN", "MMR-VARICELLA")

HIBTYPElevels=c("5", "7", "43", "44", "HI")
HIBTYPElabels=c("DTP-HIB", "DTAP-HIB", "HEPB-HIB", "HIB ONLY", "HIB-UNKNOWN")

HEPBTYPElevels=c("8", "43", "60", "HB")
HEPBTYPElabels=c("DTAP-HEPB-IPV", "HEPB-HIB", "HEPB ONLY", "HEPB-UNKNOWN")

PCVTYPElevels=c("70", "71", "72")
PCVTYPElabels=c("CONJUGATE", "POLYSACCHARIDE", "PCV-UNKNOWN")

VARTYPElevels=c("VA", "VM", "VO")
VARTYPElabels=c("VARICELLA-UNKNOWN", "MMR-VARICELLA", "VARICELLA-ONLY")

##########################################################################
# Step 3:   READ THE FLAT DATA FILE                                      #
##########################################################################

LIST.NAMEWIDTH <- 
c("SEQNUMC",6,
"SEQNUMHH",5,
"PDAT",1,
"PROVWT",19,
"RDDWT",19,
"YEAR",4,
"AGECPOXR",1,
"SC_431",2,
"SC_4313",2,
"SC_43133",2,
"SC_DTP",2,
"SC_HEPB",2,
"SC_HIB",2,
"SC_MCV",2,
"SC_POL",2,
"SC_VRC",2,
"HH_DTP",2,
"HH_FLU",2,
"HH_HEPB",2,
"HH_HIB",2,
"HH_MCV",2,
"HH_POL",2,
"HH_VRC",2,
"HAD_CPOX",2,
"SHOTCARD",1,
"AGEGRP",1,
"BF_ENDR06",8,
"BF_EXCLR06",8,
"BF_FORMR06",8,
"BFENDFL06",1,
"BFFORMFL06",1,
"C1R",1,
"C5R",2,
"CBF_01",2,
"CEN_REG",1,
"CHILDNM",1,
"CWIC_01",2,
"CWIC_02",1,
"EDUC1",1,
"FRSTBRN",1,
"I_HISP_K",1,
"INCPORAR",16,
"INCPOV1",1,
"INCQ298A",2,
"INOPHONR",1,
"INTRP",1,
"LANGUAGE",1,
"M_AGEGRP",1,
"MARITAL",1,
"MOBIL_I",1,
"RACE_K",1,
"RACEETHK",1,
"SEX",1,
"ESTIAP07",3,
"STATE",2,
"D6R",1,
"D7",1,
"DISPCODE",2,
"N_PRVR",1,
"PROV_FAC",1,
"REGISTRY",1,
"VFC_ORDER",1,
"HEP_BRTH",1,
"HEP_FLAG",1,
"P_NUHEPX",1,
"P_NUHIBX",1,
"P_NUHPHB",1,
"P_NUMDAH",1,
"P_NUMDHB",1,
"P_NUMDHI",1,
"P_NUMDHM",1,
"P_NUMDTA",1,
"P_NUMDTM",1,
"P_NUMDTP",1,
"P_NUMFLU",1,
"P_NUMHEA",1,
"P_NUMHEN",1,
"P_NUMHEP",1,
"P_NUMHIB",1,
"P_NUMHIN",1,
"P_NUMIPV",1,
"P_NUMMCN",1,
"P_NUMMMR",1,
"P_NUMMMRX",1,
"P_NUMMMX",1,
"P_NUMMP",1,
"P_NUMMPR",1,
"P_NUMMRV",1,
"P_NUMMS",1,
"P_NUMMSM",1,
"P_NUMMSR",1,
"P_NUMOLN",1,
"P_NUMOPV",1,
"P_NUMPCC",1,
"P_NUMPCN",1,
"P_NUMPCP",1,
"P_NUMPCV",1,
"P_NUMPOL",1,
"P_NUMRB",1,
"P_NUMROT",1,
"P_NUMTPM",1,
"P_NUMTPN",1,
"P_NUMVRC",1,
"P_NUMVRN",1,
"P_NUMVRX",1,
"P_U12VRC",1,
"P_UTD331",1,
"P_UTD431",1,
"P_UTDFL1",1,
"P_UTDFL2",1,
"P_UTDFL3",1,
"P_UTDHEP",1,
"P_UTDHIB",1,
"P_UTDMCV",1,
"P_UTDMMX",1,
"P_UTDPC3",1,
"P_UTDPCV",1,
"P_UTDPOL",1,
"P_UTDTP3",1,
"P_UTDTP4",1,
"PU431331",1,
"PU4313313",1,
"PU4313314",1,
"PUT43133",1,
"PUTD4313",1,
"DDTP1",4,
"DDTP2",4,
"DDTP3",4,
"DDTP4",4,
"DDTP5",4,
"DDTP6",3,
"DDTP7",3,
"DDTP8",1,
"DDTP9",1,
"DFLU1",4,
"DFLU2",4,
"DFLU3",4,
"DFLU4",4,
"DFLU5",4,
"DFLU6",1,
"DFLU7",1,
"DFLU8",1,
"DFLU9",1,
"DHEPA1",4,
"DHEPA2",4,
"DHEPA3",4,
"DHEPA4",4,
"DHEPA5",1,
"DHEPA6",1,
"DHEPA7",1,
"DHEPA8",1,
"DHEPA9",1,
"DHEPB1",4,
"DHEPB2",4,
"DHEPB3",4,
"DHEPB4",4,
"DHEPB5",4,
"DHEPB6",4,
"DHEPB7",3,
"DHEPB8",1,
"DHEPB9",1,
"DHIB1",4,
"DHIB2",4,
"DHIB3",4,
"DHIB4",4,
"DHIB5",4,
"DHIB6",3,
"DHIB7",3,
"DHIB8",1,
"DHIB9",1,
"DMMR1",4,
"DMMR2",4,
"DMMR3",3,
"DMMR4",1,
"DMMR5",1,
"DMMR6",1,
"DMMR7",1,
"DMMR8",1,
"DMMR9",1,
"DMP1",3,
"DMP2",1,
"DMP3",1,
"DMP4",1,
"DMP5",1,
"DMP6",1,
"DMP7",1,
"DMP8",1,
"DMP9",1,
"DMPRB1",3,
"DMPRB2",1,
"DMPRB3",1,
"DMPRB4",1,
"DMPRB5",1,
"DMPRB6",1,
"DMPRB7",1,
"DMPRB8",1,
"DMPRB9",1,
"DPCV1",4,
"DPCV2",4,
"DPCV3",4,
"DPCV4",4,
"DPCV5",4,
"DPCV6",3,
"DPCV7",3,
"DPCV8",1,
"DPCV9",1,
"DPOLIO1",4,
"DPOLIO2",4,
"DPOLIO3",4,
"DPOLIO4",4,
"DPOLIO5",4,
"DPOLIO6",3,
"DPOLIO7",3,
"DPOLIO8",1,
"DPOLIO9",1,
"DRB1",3,
"DRB2",3,
"DRB3",1,
"DRB4",1,
"DRB5",1,
"DRB6",1,
"DRB7",1,
"DRB8",1,
"DRB9",1,
"DROT1",3,
"DROT2",3,
"DROT3",3,
"DROT4",3,
"DROT5",1,
"DROT6",1,
"DROT7",1,
"DROT8",1,
"DROT9",1,
"DTP1_AGE",2,
"DTP2_AGE",2,
"DTP3_AGE",2,
"DTP4_AGE",2,
"DTP5_AGE",2,
"DTP6_AGE",2,
"DTP7_AGE",2,
"DTP8_AGE",1,
"DTP9_AGE",1,
"DVRC1",4,
"DVRC2",4,
"DVRC3",4,
"DVRC4",1,
"DVRC5",1,
"DVRC6",1,
"DVRC7",1,
"DVRC8",1,
"DVRC9",1,
"FLU1_AGE",2,
"FLU2_AGE",2,
"FLU3_AGE",2,
"FLU4_AGE",2,
"FLU5_AGE",2,
"FLU6_AGE",1,
"FLU7_AGE",1,
"FLU8_AGE",1,
"FLU9_AGE",1,
"HEA1_AGE",2,
"HEA2_AGE",2,
"HEA3_AGE",2,
"HEA4_AGE",2,
"HEA5_AGE",1,
"HEA6_AGE",1,
"HEA7_AGE",1,
"HEA8_AGE",1,
"HEA9_AGE",1,
"HEP1_AGE",2,
"HEP2_AGE",2,
"HEP3_AGE",2,
"HEP4_AGE",2,
"HEP5_AGE",2,
"HEP6_AGE",2,
"HEP7_AGE",2,
"HEP8_AGE",1,
"HEP9_AGE",1,
"HIB1_AGE",2,
"HIB2_AGE",2,
"HIB3_AGE",2,
"HIB4_AGE",2,
"HIB5_AGE",2,
"HIB6_AGE",2,
"HIB7_AGE",2,
"HIB8_AGE",1,
"HIB9_AGE",1,
"MMR1_AGE",2,
"MMR2_AGE",2,
"MMR3_AGE",2,
"MMR4_AGE",1,
"MMR5_AGE",1,
"MMR6_AGE",1,
"MMR7_AGE",1,
"MMR8_AGE",1,
"MMR9_AGE",1,
"MP1_AGE",2,
"MP2_AGE",1,
"MP3_AGE",1,
"MP4_AGE",1,
"MP5_AGE",1,
"MP6_AGE",1,
"MP7_AGE",1,
"MP8_AGE",1,
"MP9_AGE",1,
"MPR1_AGE",2,
"MPR2_AGE",1,
"MPR3_AGE",1,
"MPR4_AGE",1,
"MPR5_AGE",1,
"MPR6_AGE",1,
"MPR7_AGE",1,
"MPR8_AGE",1,
"MPR9_AGE",1,
"PCV1_AGE",2,
"PCV2_AGE",2,
"PCV3_AGE",2,
"PCV4_AGE",2,
"PCV5_AGE",2,
"PCV6_AGE",2,
"PCV7_AGE",2,
"PCV8_AGE",1,
"PCV9_AGE",1,
"POL1_AGE",2,
"POL2_AGE",2,
"POL3_AGE",2,
"POL4_AGE",2,
"POL5_AGE",2,
"POL6_AGE",2,
"POL7_AGE",2,
"POL8_AGE",1,
"POL9_AGE",1,
"RB1_AGE",2,
"RB2_AGE",2,
"RB3_AGE",1,
"RB4_AGE",1,
"RB5_AGE",1,
"RB6_AGE",1,
"RB7_AGE",1,
"RB8_AGE",1,
"RB9_AGE",1,
"ROT1_AGE",2,
"ROT2_AGE",2,
"ROT3_AGE",2,
"ROT4_AGE",2,
"ROT5_AGE",1,
"ROT6_AGE",1,
"ROT7_AGE",1,
"ROT8_AGE",1,
"ROT9_AGE",1,
"VRC1_AGE",2,
"VRC2_AGE",2,
"VRC3_AGE",2,
"VRC4_AGE",1,
"VRC5_AGE",1,
"VRC6_AGE",1,
"VRC7_AGE",1,
"VRC8_AGE",1,
"VRC9_AGE",1,
"XDTPTY1",2,
"XDTPTY2",2,
"XDTPTY3",2,
"XDTPTY4",2,
"XDTPTY5",2,
"XDTPTY6",2,
"XDTPTY7",2,
"XDTPTY8",1,
"XDTPTY9",1,
"XHEPTY1",2,
"XHEPTY2",2,
"XHEPTY3",2,
"XHEPTY4",2,
"XHEPTY5",2,
"XHEPTY6",2,
"XHEPTY7",2,
"XHEPTY8",1,
"XHEPTY9",1,
"XHIBTY1",2,
"XHIBTY2",2,
"XHIBTY3",2,
"XHIBTY4",2,
"XHIBTY5",2,
"XHIBTY6",2,
"XHIBTY7",2,
"XHIBTY8",1,
"XHIBTY9",1,
"XMMRTY1",2,
"XMMRTY2",2,
"XMMRTY3",2,
"XMMRTY4",1,
"XMMRTY5",1,
"XMMRTY6",1,
"XMMRTY7",1,
"XMMRTY8",1,
"XMMRTY9",1,
"XPCVTY1",2,
"XPCVTY2",2,
"XPCVTY3",2,
"XPCVTY4",2,
"XPCVTY5",2,
"XPCVTY6",2,
"XPCVTY7",2,
"XPCVTY8",1,
"XPCVTY9",1,
"XPOLTY1",2,
"XPOLTY2",2,
"XPOLTY3",2,
"XPOLTY4",2,
"XPOLTY5",2,
"XPOLTY6",2,
"XPOLTY7",2,
"XPOLTY8",1,
"XPOLTY9",1,
"XVRCTY1",2,
"XVRCTY2",2,
"XVRCTY3",2,
"XVRCTY4",1,
"XVRCTY5",1,
"XVRCTY6",1,
"XVRCTY7",1,
"XVRCTY8",1,
"XVRCTY9",1,
"INS_1",2,
"INS_2",2,
"INS_3",2,
"INS_3A",2,
"INS_4",2,
"INS_5",2,
"INS_6",2,
"INS_11",2
)

NAMEWIDTH <- matrix(LIST.NAMEWIDTH, 430, 2, byrow=T, dimnames = list(NULL, c("VARIABLE","WIDTH")))
NA_STRING <- c(" ", ".", " .", "  .", "   .", "   .    ", " .              ", "    .              ")

NISPUF07 <- read.fwf(flatfile, widths= as.numeric(NAMEWIDTH[,2]), col.names = NAMEWIDTH[,1], na.strings= NA_STRING, as.is=TRUE)

NISPUF07$SEQNUMC <- as.character(NISPUF07$SEQNUMC)
NISPUF07$SEQNUMHH <- as.character(NISPUF07$SEQNUMHH)
NISPUF07$XDTPTY1 <- as.character(NISPUF07$XDTPTY1)
NISPUF07$XDTPTY2 <- as.character(NISPUF07$XDTPTY2)
NISPUF07$XDTPTY3 <- as.character(NISPUF07$XDTPTY3)
NISPUF07$XDTPTY4 <- as.character(NISPUF07$XDTPTY4)
NISPUF07$XDTPTY5 <- as.character(NISPUF07$XDTPTY5)
NISPUF07$XDTPTY6 <- as.character(NISPUF07$XDTPTY6)
NISPUF07$XDTPTY7 <- as.character(NISPUF07$XDTPTY7)
NISPUF07$XDTPTY8 <- as.character(NISPUF07$XDTPTY8)
NISPUF07$XDTPTY9 <- as.character(NISPUF07$XDTPTY9)
NISPUF07$XHEPTY1 <- as.character(NISPUF07$XHEPTY1)
NISPUF07$XHEPTY2 <- as.character(NISPUF07$XHEPTY2)
NISPUF07$XHEPTY3 <- as.character(NISPUF07$XHEPTY3)
NISPUF07$XHEPTY4 <- as.character(NISPUF07$XHEPTY4)
NISPUF07$XHEPTY5 <- as.character(NISPUF07$XHEPTY5)
NISPUF07$XHEPTY6 <- as.character(NISPUF07$XHEPTY6)
NISPUF07$XHEPTY7 <- as.character(NISPUF07$XHEPTY7)
NISPUF07$XHEPTY8 <- as.character(NISPUF07$XHEPTY8)
NISPUF07$XHEPTY9 <- as.character(NISPUF07$XHEPTY9)
NISPUF07$XHIBTY1 <- as.character(NISPUF07$XHIBTY1)
NISPUF07$XHIBTY2 <- as.character(NISPUF07$XHIBTY2)
NISPUF07$XHIBTY3 <- as.character(NISPUF07$XHIBTY3)
NISPUF07$XHIBTY4 <- as.character(NISPUF07$XHIBTY4)
NISPUF07$XHIBTY5 <- as.character(NISPUF07$XHIBTY5)
NISPUF07$XHIBTY6 <- as.character(NISPUF07$XHIBTY6)
NISPUF07$XHIBTY7 <- as.character(NISPUF07$XHIBTY7)
NISPUF07$XHIBTY8 <- as.character(NISPUF07$XHIBTY8)
NISPUF07$XHIBTY9 <- as.character(NISPUF07$XHIBTY9)
NISPUF07$XMMRTY1 <- as.character(NISPUF07$XMMRTY1)
NISPUF07$XMMRTY2 <- as.character(NISPUF07$XMMRTY2)
NISPUF07$XMMRTY3 <- as.character(NISPUF07$XMMRTY3)
NISPUF07$XMMRTY4 <- as.character(NISPUF07$XMMRTY4)
NISPUF07$XMMRTY5 <- as.character(NISPUF07$XMMRTY5)
NISPUF07$XMMRTY6 <- as.character(NISPUF07$XMMRTY6)
NISPUF07$XMMRTY7 <- as.character(NISPUF07$XMMRTY7)
NISPUF07$XMMRTY8 <- as.character(NISPUF07$XMMRTY8)
NISPUF07$XMMRTY9 <- as.character(NISPUF07$XMMRTY9)
NISPUF07$XPCVTY1 <- as.character(NISPUF07$XPCVTY1)
NISPUF07$XPCVTY2 <- as.character(NISPUF07$XPCVTY2)
NISPUF07$XPCVTY3 <- as.character(NISPUF07$XPCVTY3)
NISPUF07$XPCVTY4 <- as.character(NISPUF07$XPCVTY4)
NISPUF07$XPCVTY5 <- as.character(NISPUF07$XPCVTY5)
NISPUF07$XPCVTY6 <- as.character(NISPUF07$XPCVTY6)
NISPUF07$XPCVTY7 <- as.character(NISPUF07$XPCVTY7)
NISPUF07$XPCVTY8 <- as.character(NISPUF07$XPCVTY8)
NISPUF07$XPCVTY9 <- as.character(NISPUF07$XPCVTY9)
NISPUF07$XPOLTY1 <- as.character(NISPUF07$XPOLTY1)
NISPUF07$XPOLTY2 <- as.character(NISPUF07$XPOLTY2)
NISPUF07$XPOLTY3 <- as.character(NISPUF07$XPOLTY3)
NISPUF07$XPOLTY4 <- as.character(NISPUF07$XPOLTY4)
NISPUF07$XPOLTY5 <- as.character(NISPUF07$XPOLTY5)
NISPUF07$XPOLTY6 <- as.character(NISPUF07$XPOLTY6)
NISPUF07$XPOLTY7 <- as.character(NISPUF07$XPOLTY7)
NISPUF07$XPOLTY8 <- as.character(NISPUF07$XPOLTY8)
NISPUF07$XPOLTY9 <- as.character(NISPUF07$XPOLTY9)
NISPUF07$XVRCTY1 <- as.character(NISPUF07$XVRCTY1)
NISPUF07$XVRCTY2 <- as.character(NISPUF07$XVRCTY2)
NISPUF07$XVRCTY3 <- as.character(NISPUF07$XVRCTY3)
NISPUF07$XVRCTY4 <- as.character(NISPUF07$XVRCTY4)
NISPUF07$XVRCTY5 <- as.character(NISPUF07$XVRCTY5)
NISPUF07$XVRCTY6 <- as.character(NISPUF07$XVRCTY6)
NISPUF07$XVRCTY7 <- as.character(NISPUF07$XVRCTY7)
NISPUF07$XVRCTY8 <- as.character(NISPUF07$XVRCTY8)
NISPUF07$XVRCTY9 <- as.character(NISPUF07$XVRCTY9)

##########################################################################
# Step 4:   ASSIGN VARIABLE LABELS                                       #
##########################################################################

label(NISPUF07$SEQNUMC) <- "UNIQUE CHILD IDENTIFIER"
label(NISPUF07$SEQNUMHH) <- "UNIQUE HOUSEHOLD IDENTIFIER"
label(NISPUF07$PDAT) <- "CHILD HAS ADEQUATE PROVIDER DATA"
label(NISPUF07$PROVWT) <- "WEIGHT FOR CHILDREN WITH ADEQUATE PROVIDER DATA AND UNVACCINATED CHILDREN"
label(NISPUF07$RDDWT) <- "RDD CHILD INTERVIEW WEIGHT"

label(NISPUF07$YEAR) <- "YEAR OF INTERVIEW"
label(NISPUF07$AGECPOXR) <- "AGE IN MONTHS AT CHICKEN POX DISEASE (RECODE)"
label(NISPUF07$SC_431) <- "HH SHOT CARD REPORT OF 4:3:1 UP-TO-DATE"
label(NISPUF07$SC_4313) <- "HH SHOT CARD REPORT OF 4:3:1:3 UP-TO-DATE"
label(NISPUF07$SC_43133) <- "HH SHOT CARD REPORT OF 4:3:1:3:3 UP-TO-DATE"

label(NISPUF07$SC_DTP) <- "HH SHOT CARD REPORT OF 4+ DT-CONTAINING UP-TO-DATE"
label(NISPUF07$SC_HEPB) <- "HH SHOT CARD REPORT OF 3+ HEPATITIS B-CONTAINING UP-TO-DATE"
label(NISPUF07$SC_HIB) <- "HH SHOT CARD REPORT OF 3+ HIB-CONTAINING UP-TO-DATE"
label(NISPUF07$SC_MCV) <- "HH SHOT CARD REPORT OF 1+ MEASLES-CONTAINING UP-TO-DATE"
label(NISPUF07$SC_POL) <- "HH SHOT CARD REPORT OF 3+ POLIO-CONTAINING UP-TO-DATE"

label(NISPUF07$SC_VRC) <- "HH SHOT CARD REPORT OF 1+ VARICELLA-CONTAINING UP-TO-DATE"
label(NISPUF07$HH_DTP) <- "HH REPORT OF NUMBER OF DT-CONTAINING SHOTS RECEIVED"
label(NISPUF07$HH_FLU) <- "HH REPORT OF NUMBER OF FLU VACCINATIONS RECEIVED"
label(NISPUF07$HH_HEPB) <- "HH REPORT OF NUMBER OF HEPATITIS B-CONTAINING SHOTS RECEIVED"
label(NISPUF07$HH_HIB) <- "HH REPORT OF NUMBER OF HIB-CONTAINING SHOTS RECEIVED"
label(NISPUF07$HH_MCV) <- "HH REPORT OF NUMBER OF MEASLES-CONTAINING SHOTS RECEIVED"

label(NISPUF07$HH_POL) <- "HH REPORT OF NUMBER OF POLIO-CONTAINING SHOTS RECEIVED"
label(NISPUF07$HH_VRC) <- "HH REPORT OF NUMBER OF VARICELLA-CONTAINING SHOTS RECEIVED"
label(NISPUF07$HAD_CPOX) <- "CHILD EVER HAD CHICKEN POX DISEASE?"
label(NISPUF07$SHOTCARD) <- "SHOT CARD USE FLAG"
label(NISPUF07$AGEGRP) <- "AGE CATEGORY OF CHILD (19-23, 24-29, 30-35 MO) (RECODE)"

label(NISPUF07$BF_ENDR06) <- "DURATION OF BREAST FEEDING IN DAYS (TOPCODE)"
label(NISPUF07$BF_EXCLR06) <- "DURATION OF EXCLUSIVE BREAST/FORMULA FEEDING IN DAYS (TOPCODE)"
label(NISPUF07$BF_FORMR06) <- "AGE IN DAYS WHEN CHILD FIRST FED FORMULA (TOPCODE)"
label(NISPUF07$BFENDFL06) <- "DURATION OF BREAST FEEDING EXCEEDS CHILD AGE IN DAYS, WITH BUFFER"
label(NISPUF07$BFFORMFL06) <- "AGE IN DAYS WHEN CHILD FIRST FED FORMULA EXCEEDS CHILD AGE IN DAYS, WITH BUFFER"

label(NISPUF07$C1R) <- "NUMBER OF PEOPLE IN HOUSEHOLD (TOPCODE)"
label(NISPUF07$C5R) <- "RELATIONSHIP OF RESPONDENT TO CHILD (RECODE)"
label(NISPUF07$CBF_01) <- "WAS CHILD EVER BREAST FED OR FED BREAST MILK?"
label(NISPUF07$CEN_REG) <- "CENSUS REGION BASED ON TRUE STATE OF RESIDENCE"
label(NISPUF07$CHILDNM) <- "NUMBER OF CHILDREN LESS THAN 18 YEARS IN HH (RECODE)"

label(NISPUF07$CWIC_01) <- "CHILD EVER RECEIVED WIC BENEFITS?"
label(NISPUF07$CWIC_02) <- "CHILD CURRENTLY RECEIVING WIC BENEFITS?"
label(NISPUF07$EDUC1) <- "EDUCATION OF MOTHER CATEGORIES (RECODE)"
label(NISPUF07$FRSTBRN) <- "FIRST BORN STATUS OF CHILD"
label(NISPUF07$I_HISP_K) <- "HISPANIC ORIGIN OF CHILD"

label(NISPUF07$INCPORAR) <- "INCOME TO POVERTY RATIO (TOP- AND BOTTOMCODE)"
label(NISPUF07$INCPOV1) <- "POVERTY STATUS"
label(NISPUF07$INCQ298A) <- "FAMILY INCOME CATEGORIES (RECODE)"
label(NISPUF07$INOPHONR) <- "LENGTH OF INTERRUPTION IN TELEPHONE SERVICE IN DAYS (RECODE)"
label(NISPUF07$INTRP) <- "PHONE INTERRUPTION OF 7 DAYS OR MORE IN PAST YEAR?"

label(NISPUF07$LANGUAGE) <- "LANGUAGE IN WHICH INTERVIEW WAS CONDUCTED"
label(NISPUF07$M_AGEGRP) <- "AGE OF MOTHER CATEGORIES"
label(NISPUF07$MARITAL) <- "MARITAL STATUS OF MOTHER CATEGORIES (RECODE)"
label(NISPUF07$MOBIL_I) <- "GEOGRAPHIC MOBILITY STATUS: STATE OF RESIDENCE OF CHILD AT BIRTH VERSUS CURRENT STATE"
label(NISPUF07$RACE_K) <- "RACE OF CHILD (RECODE)"

label(NISPUF07$RACEETHK) <- "RACE/ETHNICITY OF CHILD (RECODE)"
label(NISPUF07$SEX) <- "GENDER OF CHILD"
label(NISPUF07$ESTIAP07) <- "ESTIMATION IAP AREA OF RESIDENCE"
label(NISPUF07$STATE) <- "TRUE STATE OF RESIDENCE (STATE FIPS CODE)"
label(NISPUF07$D6R) <- "NUMBER OF VACCINATION PROVIDERS IDENTIFIED BY RESPONDENT (TOPCODE)"

label(NISPUF07$D7) <- "CONSENT TO OBTAIN CHILD'S IMMUNIZATION RECORDS FROM PROVIDERS"
label(NISPUF07$DISPCODE) <- "NIS PROVIDER RECORD-CHECK DISPOSITION CODE"
label(NISPUF07$N_PRVR) <- "NUMBER OF PROVIDERS RESPONDING WITH VACCINATION DATA FOR CHILD (TOPCODE)"
label(NISPUF07$PROV_FAC) <- "PROVIDER FACILITY TYPE"
label(NISPUF07$REGISTRY) <- "CHILD'S PROVIDERS REPORTED CHILD'S VACCINATIONS TO IMMUNIZATION REGISTRY"

label(NISPUF07$VFC_ORDER) <- "DO CHILD'S PROVIDERS ORDER VACCINES FROM STATE/LOCAL HEALTH DEPT?"
label(NISPUF07$HEP_BRTH) <- "HEPATITIS B-CONTAINING SHOT GIVEN AT BIRTH FLAG"
label(NISPUF07$HEP_FLAG) <- "HEPATITIS B BIRTH SHOT DATE IMPUTATION FLAG"
label(NISPUF07$P_NUHEPX) <- "NUMBER OF HEPATITIS B-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUHIBX) <- "NUMBER OF HIB-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISPUF07$P_NUHPHB) <- "NUMBER OF HEPATITIS B/HIB COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMDAH) <- "NUMBER OF DTAP/HIB COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMDHB) <- "NUMBER OF DTP/HIB CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMDHI) <- "NUMBER OF DTAP/HEPB/IPV COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RRD INTERVIEW DATE."
label(NISPUF07$P_NUMDHM) <- "NUMBER OF DTP/HIB COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISPUF07$P_NUMDTA) <- "NUMBER OF DTAP-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMDTM) <- "NUMBER OF DT-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMDTP) <- "NUMBER OF DT-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMFLU) <- "NUMBER OF FLU-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMHEA) <- "NUMBER OF HEPATITIS A-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISPUF07$P_NUMHEN) <- "NUMBER OF HEPATITIS B-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMHEP) <- "NUMBER OF HEPATITIS B-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMHIB) <- "NUMBER OF HIB-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMHIN) <- "NUMBER OF HIB-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMIPV) <- "NUMBER OF IPV-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISPUF07$P_NUMMCN) <- "NUMBER OF MEASLES-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMMMR) <- "NUMBER OF MEASLES-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMMMRX) <- "NUMBER OF MMR-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMMMX) <- "NUMBER OF MMR-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMMP) <- "NUMBER OF MUMPS-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISPUF07$P_NUMMPR) <- "NUMBER OF (MUMPS/RUBELLA)-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMMRV) <- "NUMBER OF MMR/VARICELLA COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMMS) <- "NUMBER OF MEASLES-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMMSM) <- "NUMBER OF MEASLES/MUMPS COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMMSR) <- "NUMBER OF MEASLES/RUBELLA COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISPUF07$P_NUMOLN) <- "NUMBER OF POLIO SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMOPV) <- "NUMBER OF OPV-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMPCC) <- "NUMBER OF PCV CONJUGATE SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMPCN) <- "NUMBER OF PCV SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMPCP) <- "NUMBER OF PCV POLYSACCHARIDE SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISPUF07$P_NUMPCV) <- "NUMBER OF PNEUMOCOCCAL-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMPOL) <- "NUMBER OF POLIO-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMRB) <- "NUMBER OF RUBELLA-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMROT) <- "NUMBER OF ROTAVIRUS-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMTPM) <- "NUMBER OF DTP-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISPUF07$P_NUMTPN) <- "NUMBER OF DT-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMVRC) <- "NUMBER OF VARICELLA-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMVRN) <- "NUMBER OF VARICELLA-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_NUMVRX) <- "NUMBER OF VARICELLA-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISPUF07$P_U12VRC) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ VARICELLA-CONTAINING SHOT AT 12+ MONTHS"

label(NISPUF07$P_UTD331) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3:3:1"
label(NISPUF07$P_UTD431) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1"
label(NISPUF07$P_UTDFL1) <- "UTD FLAG FOR PROVIDER INFLUENZA VARIABLE 1"
label(NISPUF07$P_UTDFL2) <- "UTD FLAG FOR PROVIDER INFLUENZA VARIABLE 2"
label(NISPUF07$P_UTDFL3) <- "UTD FLAG FOR PROVIDER INFLUENZA VARIABLE 3"

label(NISPUF07$P_UTDHEP) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HEPATITIS B-CONTAINING SHOTS"

label(NISPUF07$P_UTDHIB) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HIB-CONTAINING SHOTS"
label(NISPUF07$P_UTDMCV) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ MEASLES-CONTAINING SHOT"
label(NISPUF07$P_UTDMMX) <- "UTD FLAG FOR PROVIDER 1+ MMR COMBO SHOT"
label(NISPUF07$P_UTDPC3) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ PNEUMOCOCCAL-CONTAINING SHOTS"
label(NISPUF07$P_UTDPCV) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4+ PNEUMOCOCCAL-CONTAINING SHOTS"

label(NISPUF07$P_UTDPOL) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ POLIO-CONTAINING SHOTS"
label(NISPUF07$P_UTDTP3) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ DT-CONTAINING SHOTS"
label(NISPUF07$P_UTDTP4) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4+ DT-CONTAINING SHOTS"
label(NISPUF07$PU431331) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3:1 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS)"
label(NISPUF07$PU4313313) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3:1:3 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS)"
label(NISPUF07$PU4313314) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3:1:4 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS)"

label(NISPUF07$PUT43133) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3"
label(NISPUF07$PUTD4313) <- "UTD FLAG FOR PROVIDER 4:3:1:3"
label(NISPUF07$DDTP1) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #1"
label(NISPUF07$DDTP2) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #2"
label(NISPUF07$DDTP3) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #3"
label(NISPUF07$DDTP4) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #4"

label(NISPUF07$DDTP5) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #5"
label(NISPUF07$DDTP6) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #6"
label(NISPUF07$DDTP7) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #7"
label(NISPUF07$DDTP8) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #8"
label(NISPUF07$DDTP9) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #9"

label(NISPUF07$DFLU1) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING SHOT #1"
label(NISPUF07$DFLU2) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING SHOT #2"
label(NISPUF07$DFLU3) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING SHOT #3"
label(NISPUF07$DFLU4) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING SHOT #4"
label(NISPUF07$DFLU5) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING SHOT #5"

label(NISPUF07$DFLU6) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING SHOT #6"
label(NISPUF07$DFLU7) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING SHOT #7"
label(NISPUF07$DFLU8) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING SHOT #8"
label(NISPUF07$DFLU9) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING SHOT #9"
label(NISPUF07$DHEPA1) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #1"

label(NISPUF07$DHEPA2) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #2"
label(NISPUF07$DHEPA3) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #3"
label(NISPUF07$DHEPA4) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #4"
label(NISPUF07$DHEPA5) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #5"
label(NISPUF07$DHEPA6) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #6"

label(NISPUF07$DHEPA7) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #7"
label(NISPUF07$DHEPA8) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #8"
label(NISPUF07$DHEPA9) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #9"
label(NISPUF07$DHEPB1) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #1"
label(NISPUF07$DHEPB2) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #2"

label(NISPUF07$DHEPB3) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #3"
label(NISPUF07$DHEPB4) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #4"
label(NISPUF07$DHEPB5) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #5"
label(NISPUF07$DHEPB6) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #6"
label(NISPUF07$DHEPB7) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #7"

label(NISPUF07$DHEPB8) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #8"
label(NISPUF07$DHEPB9) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #9"
label(NISPUF07$DHIB1) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #1"
label(NISPUF07$DHIB2) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #2"
label(NISPUF07$DHIB3) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #3"

label(NISPUF07$DHIB4) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #4"
label(NISPUF07$DHIB5) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #5"
label(NISPUF07$DHIB6) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #6"
label(NISPUF07$DHIB7) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #7"
label(NISPUF07$DHIB8) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #8"

label(NISPUF07$DHIB9) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #9"
label(NISPUF07$DMMR1) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #1"
label(NISPUF07$DMMR2) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #2"
label(NISPUF07$DMMR3) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #3"
label(NISPUF07$DMMR4) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #4"

label(NISPUF07$DMMR5) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #5"
label(NISPUF07$DMMR6) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #6"
label(NISPUF07$DMMR7) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #7"
label(NISPUF07$DMMR8) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #8"
label(NISPUF07$DMMR9) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #9"

label(NISPUF07$DMP1) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #1"
label(NISPUF07$DMP2) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #2"
label(NISPUF07$DMP3) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #3"
label(NISPUF07$DMP4) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #4"
label(NISPUF07$DMP5) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #5"

label(NISPUF07$DMP6) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #6"
label(NISPUF07$DMP7) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #7"
label(NISPUF07$DMP8) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #8"
label(NISPUF07$DMP9) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #9"
label(NISPUF07$DMPRB1) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #1"

label(NISPUF07$DMPRB2) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #2"
label(NISPUF07$DMPRB3) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #3"
label(NISPUF07$DMPRB4) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #4"
label(NISPUF07$DMPRB5) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #5"
label(NISPUF07$DMPRB6) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #6"

label(NISPUF07$DMPRB7) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #7"
label(NISPUF07$DMPRB8) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #8"
label(NISPUF07$DMPRB9) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #9"
label(NISPUF07$DPCV1) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #1"
label(NISPUF07$DPCV2) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #2"

label(NISPUF07$DPCV3) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #3"
label(NISPUF07$DPCV4) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #4"
label(NISPUF07$DPCV5) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #5"
label(NISPUF07$DPCV6) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #6"
label(NISPUF07$DPCV7) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #7"

label(NISPUF07$DPCV8) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #8"
label(NISPUF07$DPCV9) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #9"
label(NISPUF07$DPOLIO1) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #1"
label(NISPUF07$DPOLIO2) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #2"
label(NISPUF07$DPOLIO3) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #3"

label(NISPUF07$DPOLIO4) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #4"
label(NISPUF07$DPOLIO5) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #5"
label(NISPUF07$DPOLIO6) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #6"
label(NISPUF07$DPOLIO7) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #7"
label(NISPUF07$DPOLIO8) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #8"

label(NISPUF07$DPOLIO9) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #9"
label(NISPUF07$DRB1) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #1"
label(NISPUF07$DRB2) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #2"
label(NISPUF07$DRB3) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #3"
label(NISPUF07$DRB4) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #4"

label(NISPUF07$DRB5) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #5"
label(NISPUF07$DRB6) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #6"
label(NISPUF07$DRB7) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #7"
label(NISPUF07$DRB8) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #8"
label(NISPUF07$DRB9) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #9"

label(NISPUF07$DROT1) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #1"
label(NISPUF07$DROT2) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #2"
label(NISPUF07$DROT3) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #3"
label(NISPUF07$DROT4) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #4"
label(NISPUF07$DROT5) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #5"

label(NISPUF07$DROT6) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #6"
label(NISPUF07$DROT7) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #7"
label(NISPUF07$DROT8) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #8"
label(NISPUF07$DROT9) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #9"
label(NISPUF07$DTP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #1"

label(NISPUF07$DTP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #2"
label(NISPUF07$DTP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #3"
label(NISPUF07$DTP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #4"
label(NISPUF07$DTP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #5"
label(NISPUF07$DTP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #6"

label(NISPUF07$DTP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #7"
label(NISPUF07$DTP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #8"
label(NISPUF07$DTP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #9"
label(NISPUF07$DVRC1) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #1"
label(NISPUF07$DVRC2) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #2"

label(NISPUF07$DVRC3) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #3"
label(NISPUF07$DVRC4) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #4"
label(NISPUF07$DVRC5) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #5"
label(NISPUF07$DVRC6) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #6"
label(NISPUF07$DVRC7) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #7"

label(NISPUF07$DVRC8) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #8"
label(NISPUF07$DVRC9) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #9"
label(NISPUF07$FLU1_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING SHOT #1"
label(NISPUF07$FLU2_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING SHOT #2"
label(NISPUF07$FLU3_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING SHOT #3"

label(NISPUF07$FLU4_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING SHOT #4"
label(NISPUF07$FLU5_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING SHOT #5"
label(NISPUF07$FLU6_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING SHOT #6"
label(NISPUF07$FLU7_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING SHOT #7"
label(NISPUF07$FLU8_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING SHOT #8"

label(NISPUF07$FLU9_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING SHOT #9"
label(NISPUF07$HEA1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #1"
label(NISPUF07$HEA2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #2"
label(NISPUF07$HEA3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #3"
label(NISPUF07$HEA4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #4"

label(NISPUF07$HEA5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #5"
label(NISPUF07$HEA6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #6"
label(NISPUF07$HEA7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #7"
label(NISPUF07$HEA8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #8"
label(NISPUF07$HEA9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #9"

label(NISPUF07$HEP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #1"
label(NISPUF07$HEP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #2"
label(NISPUF07$HEP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #3"
label(NISPUF07$HEP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #4"
label(NISPUF07$HEP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #5"

label(NISPUF07$HEP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #6"
label(NISPUF07$HEP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #7"
label(NISPUF07$HEP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #8"
label(NISPUF07$HEP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #9"
label(NISPUF07$HIB1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #1"

label(NISPUF07$HIB2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #2"
label(NISPUF07$HIB3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #3"
label(NISPUF07$HIB4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #4"
label(NISPUF07$HIB5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #5"
label(NISPUF07$HIB6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #6"

label(NISPUF07$HIB7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #7"
label(NISPUF07$HIB8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #8"
label(NISPUF07$HIB9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #9"
label(NISPUF07$MMR1_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #1"
label(NISPUF07$MMR2_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #2"

label(NISPUF07$MMR3_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #3"
label(NISPUF07$MMR4_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #4"
label(NISPUF07$MMR5_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #5"
label(NISPUF07$MMR6_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #6"
label(NISPUF07$MMR7_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #7"

label(NISPUF07$MMR8_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #8"
label(NISPUF07$MMR9_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #9"
label(NISPUF07$MP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #1"
label(NISPUF07$MP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #2"
label(NISPUF07$MP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #3"

label(NISPUF07$MP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #4"
label(NISPUF07$MP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #5"
label(NISPUF07$MP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #6"
label(NISPUF07$MP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #7"
label(NISPUF07$MP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #8"

label(NISPUF07$MP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #9"
label(NISPUF07$MPR1_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #1"
label(NISPUF07$MPR2_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #2"
label(NISPUF07$MPR3_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #3"
label(NISPUF07$MPR4_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #4"

label(NISPUF07$MPR5_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #5"
label(NISPUF07$MPR6_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #6"
label(NISPUF07$MPR7_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #7"
label(NISPUF07$MPR8_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #8"
label(NISPUF07$MPR9_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #9"

label(NISPUF07$PCV1_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #1"
label(NISPUF07$PCV2_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #2"
label(NISPUF07$PCV3_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #3"
label(NISPUF07$PCV4_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #4"
label(NISPUF07$PCV5_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #5"

label(NISPUF07$PCV6_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #6"
label(NISPUF07$PCV7_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #7"
label(NISPUF07$PCV8_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #8"
label(NISPUF07$PCV9_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #9"
label(NISPUF07$POL1_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #1"

label(NISPUF07$POL2_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #2"
label(NISPUF07$POL3_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #3"
label(NISPUF07$POL4_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #4"
label(NISPUF07$POL5_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #5"
label(NISPUF07$POL6_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #6"

label(NISPUF07$POL7_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #7"
label(NISPUF07$POL8_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #8"
label(NISPUF07$POL9_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #9"
label(NISPUF07$RB1_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #1"
label(NISPUF07$RB2_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #2"

label(NISPUF07$RB3_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #3"
label(NISPUF07$RB4_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #4"
label(NISPUF07$RB5_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #5"
label(NISPUF07$RB6_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #6"
label(NISPUF07$RB7_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #7"

label(NISPUF07$RB8_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #8"
label(NISPUF07$RB9_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #9"
label(NISPUF07$ROT1_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #1"
label(NISPUF07$ROT2_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #2"
label(NISPUF07$ROT3_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #3"

label(NISPUF07$ROT4_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #4"
label(NISPUF07$ROT5_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #5"
label(NISPUF07$ROT6_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #6"
label(NISPUF07$ROT7_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #7"
label(NISPUF07$ROT8_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #8"

label(NISPUF07$ROT9_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #9"
label(NISPUF07$VRC1_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #1"
label(NISPUF07$VRC2_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #2"
label(NISPUF07$VRC3_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #3"
label(NISPUF07$VRC4_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #4"

label(NISPUF07$VRC5_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #5"
label(NISPUF07$VRC6_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #6"
label(NISPUF07$VRC7_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #7"
label(NISPUF07$VRC8_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #8"
label(NISPUF07$VRC9_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #9"

label(NISPUF07$XDTPTY1) <- "DT-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF07$XDTPTY2) <- "DT-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF07$XDTPTY3) <- "DT-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF07$XDTPTY4) <- "DT-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF07$XDTPTY5) <- "DT-CONTAINING VACCINATION #5 TYPE CODE"

label(NISPUF07$XDTPTY6) <- "DT-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF07$XDTPTY7) <- "DT-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF07$XDTPTY8) <- "DT-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF07$XDTPTY9) <- "DT-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF07$XHEPTY1) <- "HEPATITIS B-CONTAINING VACCINATION #1 TYPE CODE"

label(NISPUF07$XHEPTY2) <- "HEPATITIS B-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF07$XHEPTY3) <- "HEPATITIS B-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF07$XHEPTY4) <- "HEPATITIS B-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF07$XHEPTY5) <- "HEPATITIS B-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF07$XHEPTY6) <- "HEPATITIS B-CONTAINING VACCINATION #6 TYPE CODE"

label(NISPUF07$XHEPTY7) <- "HEPATITIS B-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF07$XHEPTY8) <- "HEPATITIS B-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF07$XHEPTY9) <- "HEPATITIS B-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF07$XHIBTY1) <- "HIB-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF07$XHIBTY2) <- "HIB-CONTAINING VACCINATION #2 TYPE CODE"

label(NISPUF07$XHIBTY3) <- "HIB-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF07$XHIBTY4) <- "HIB-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF07$XHIBTY5) <- "HIB-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF07$XHIBTY6) <- "HIB-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF07$XHIBTY7) <- "HIB-CONTAINING VACCINATION #7 TYPE CODE"

label(NISPUF07$XHIBTY8) <- "HIB-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF07$XHIBTY9) <- "HIB-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF07$XMMRTY1) <- "MEASLES-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF07$XMMRTY2) <- "MEASLES-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF07$XMMRTY3) <- "MEASLES-CONTAINING VACCINATION #3 TYPE CODE"

label(NISPUF07$XMMRTY4) <- "MEASLES-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF07$XMMRTY5) <- "MEASLES-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF07$XMMRTY6) <- "MEASLES-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF07$XMMRTY7) <- "MEASLES-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF07$XMMRTY8) <- "MEASLES-CONTAINING VACCINATION #8 TYPE CODE"

label(NISPUF07$XMMRTY9) <- "MEASLES-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF07$XPCVTY1) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF07$XPCVTY2) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF07$XPCVTY3) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF07$XPCVTY4) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #4 TYPE CODE"

label(NISPUF07$XPCVTY5) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF07$XPCVTY6) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF07$XPCVTY7) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF07$XPCVTY8) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF07$XPCVTY9) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #9 TYPE CODE"

label(NISPUF07$XPOLTY1) <- "POLIO-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF07$XPOLTY2) <- "POLIO-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF07$XPOLTY3) <- "POLIO-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF07$XPOLTY4) <- "POLIO-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF07$XPOLTY5) <- "POLIO-CONTAINING VACCINATION #5 TYPE CODE"

label(NISPUF07$XPOLTY6) <- "POLIO-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF07$XPOLTY7) <- "POLIO-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF07$XPOLTY8) <- "POLIO-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF07$XPOLTY9) <- "POLIO-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF07$XVRCTY1) <- "VARICELLA-CONTAINING VACCINATION #1 TYPE CODE"

label(NISPUF07$XVRCTY2) <- "VARICELLA-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF07$XVRCTY3) <- "VARICELLA-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF07$XVRCTY4) <- "VARICELLA-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF07$XVRCTY5) <- "VARICELLA-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF07$XVRCTY6) <- "VARICELLA-CONTAINING VACCINATION #6 TYPE CODE"

label(NISPUF07$XVRCTY7) <- "VARICELLA-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF07$XVRCTY8) <- "VARICELLA-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF07$XVRCTY9) <- "VARICELLA-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF07$INS_1) <- "IS CHILD COVERED BY HEALTH INSURANCE PROVIDED THROUGH EMPLOYER OR UNION?"
label(NISPUF07$INS_2) <- "IS CHILD COVERED BY ANY MEDICAID PLAN?"

label(NISPUF07$INS_3) <- "IS CHILD COVERED BY S-CHIP?"
label(NISPUF07$INS_3A) <- "IS CHILD COVERED BY ANY MEDICAID PLAN OR S-CHIP?"
label(NISPUF07$INS_4) <- "IS CHILD COVERED BY INDIAN HEALTH SERVICE?"
label(NISPUF07$INS_5) <- "IS CHILD COVERED BY MILITARY HEALTH CARE, TRICARE, CHAMPUS, OR CHAMP-VA?"
label(NISPUF07$INS_6) <- "IS CHILD COVERED BY ANY OTHER HEALTH INSURANCE OR HEALTH CARE PLAN?"

label(NISPUF07$INS_11) <- "ANY TIME WHEN CHILD WAS NOT COVERED BY ANY HEALTH INSURANCE?"


##########################################################################
# STEP 5:   CREATE A PERMANENT R DATASET						 #
##########################################################################

save(NISPUF07, file=paste(PUF, "/NISPUF07.RData", sep=""))

##########################################################################
# Step 6:   ASSIGN FORMATS                                               #
#	 FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES	IN R		 #
##########################################################################

NISPUF07$AGEGRP <- factor(NISPUF07$AGEGRP, levels=AGEGRPlevels, labels=AGEGRPlabels)
NISPUF07$LANGUAGE <- factor(NISPUF07$LANGUAGE, levels=LANGUAGElevels, labels=LANGUAGElabels)
NISPUF07$HAD_CPOX <- factor(NISPUF07$HAD_CPOX, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF07$CBF_01 <- factor(NISPUF07$CBF_01, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF07$CWIC_02 <- factor(NISPUF07$CWIC_02, levels=YNDKRFlevels, labels=YNDKRFlabels)

NISPUF07$INTRP <- factor(NISPUF07$INTRP, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF07$INS_1 <- factor(NISPUF07$INS_1, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF07$INS_2 <- factor(NISPUF07$INS_2, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF07$INS_3 <- factor(NISPUF07$INS_3, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF07$INS_3A <- factor(NISPUF07$INS_3A, levels=YNDKRFlevels, labels=YNDKRFlabels)

NISPUF07$INS_4 <- factor(NISPUF07$INS_4, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF07$INS_5 <- factor(NISPUF07$INS_5, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF07$INS_6 <- factor(NISPUF07$INS_6, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF07$INS_11 <- factor(NISPUF07$INS_11, levels=YNDKRFlevels, labels=YNDKRFlabels)

NISPUF07$SC_431 <- factor(NISPUF07$SC_431, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF07$SC_4313 <- factor(NISPUF07$SC_4313, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF07$SC_43133 <- factor(NISPUF07$SC_43133, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF07$SC_DTP <- factor(NISPUF07$SC_DTP, levels=SCUTDlevels, labels=SCUTDlabels)

NISPUF07$SC_HEPB <- factor(NISPUF07$SC_HEPB, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF07$SC_HIB <- factor(NISPUF07$SC_HIB, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF07$SC_MCV <- factor(NISPUF07$SC_MCV, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF07$SC_POL <- factor(NISPUF07$SC_POL, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF07$SC_VRC <- factor(NISPUF07$SC_VRC, levels=SCUTDlevels, labels=SCUTDlabels)

NISPUF07$HH_DTP <- factor(NISPUF07$HH_DTP, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF07$HH_FLU <- factor(NISPUF07$HH_FLU,  levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF07$HH_HEPB <- factor(NISPUF07$HH_HEPB, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF07$HH_HIB <- factor(NISPUF07$HH_HIB, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF07$HH_MCV <- factor(NISPUF07$HH_MCV, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF07$HH_POL <- factor(NISPUF07$HH_POL, levels=HHNUMlevels, labels=HHNUMlabels)

NISPUF07$HH_VRC <- factor(NISPUF07$HH_VRC, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF07$D7 <- factor(NISPUF07$D7, levels=YNlevels, labels=YNlabels)
NISPUF07$SHOTCARD <- factor(NISPUF07$SHOTCARD, levels=SHOTCARDlevels, labels=SHOTCARDlabels)
NISPUF07$BFENDFL06 <- factor(NISPUF07$BFENDFL06, levels=Ylevels, labels=Ylabels)
NISPUF07$BFFORMFL06 <- factor(NISPUF07$BFFORMFL06, levels=Ylevels, labels=Ylabels)

NISPUF07$CHILDNM <- factor(NISPUF07$CHILDNM, levels=CHILDNMlevels, labels=CHILDNMlabels)
NISPUF07$CWIC_01 <- factor(NISPUF07$CWIC_01, levels=CWIClevels, labels=CWIClabels)
NISPUF07$EDUC1 <- factor(NISPUF07$EDUC1, levels=EDUC1_levels, labels=EDUC1_labels)
NISPUF07$I_HISP_K <- factor(NISPUF07$I_HISP_K, levels=HISPlevels, labels=HISPlabels)
NISPUF07$M_AGEGRP <- factor(NISPUF07$M_AGEGRP, levels=MAGEGRPlevels, labels=MAGEGRPlabels)

NISPUF07$MOBIL_I <- factor(NISPUF07$MOBIL_I, levels=MOBILlevels, labels=MOBILlabels)
NISPUF07$SEX <- factor(NISPUF07$SEX, levels=SEXlevels, labels=SEXlabels)
NISPUF07$INCPOV1 <- factor(NISPUF07$INCPOV1, levels=INCPOVlevels, labels=INCPOVlabels)
NISPUF07$DISPCODE <- factor(NISPUF07$DISPCODE, levels=DISPlevels, labels=DISPlabels)
NISPUF07$PDAT <- factor(NISPUF07$PDAT, levels=HASPDA2Flevels, labels=HASPDA2Flabels)

NISPUF07$PROV_FAC <- factor(NISPUF07$PROV_FAC, levels=PROVIDlevels, labels=PROVIDlabels)
NISPUF07$REGISTRY <- factor(NISPUF07$REGISTRY, levels=REGISTRYlevels, labels=REGISTRYlabels)
NISPUF07$VFC_ORDER <- factor(NISPUF07$VFC_ORDER, levels=REGISTRYlevels, labels=REGISTRYlabels)
NISPUF07$XDTPTY1 <- factor(NISPUF07$XDTPTY1, levels=DTTYPElevels, labels=DTTYPElabels)
NISPUF07$XDTPTY2 <- factor(NISPUF07$XDTPTY2, levels=DTTYPElevels, labels=DTTYPElabels)

NISPUF07$XDTPTY3 <- factor(NISPUF07$XDTPTY3, levels=DTTYPElevels, labels=DTTYPElabels)
NISPUF07$XDTPTY4 <- factor(NISPUF07$XDTPTY4, levels=DTTYPElevels, labels=DTTYPElabels)
NISPUF07$XDTPTY5 <- factor(NISPUF07$XDTPTY5, levels=DTTYPElevels, labels=DTTYPElabels)
NISPUF07$XDTPTY6 <- factor(NISPUF07$XDTPTY6, levels=DTTYPElevels, labels=DTTYPElabels)
NISPUF07$XDTPTY7 <- factor(NISPUF07$XDTPTY7, levels=DTTYPElevels, labels=DTTYPElabels)

NISPUF07$XDTPTY8 <- factor(NISPUF07$XDTPTY8, levels=DTTYPElevels, labels=DTTYPElabels)
NISPUF07$XDTPTY9 <- factor(NISPUF07$XDTPTY9, levels=DTTYPElevels, labels=DTTYPElabels)
NISPUF07$XHEPTY1 <- factor(NISPUF07$XHEPTY1, levels=HEPBTYPElevels, labels=HEPBTYPElabels)
NISPUF07$XHEPTY2 <- factor(NISPUF07$XHEPTY2, levels=HEPBTYPElevels, labels=HEPBTYPElabels)
NISPUF07$XHEPTY3 <- factor(NISPUF07$XHEPTY3, levels=HEPBTYPElevels, labels=HEPBTYPElabels)

NISPUF07$XHEPTY4 <- factor(NISPUF07$XHEPTY4, levels=HEPBTYPElevels, labels=HEPBTYPElabels)
NISPUF07$XHEPTY5 <- factor(NISPUF07$XHEPTY5, levels=HEPBTYPElevels, labels=HEPBTYPElabels)
NISPUF07$XHEPTY6 <- factor(NISPUF07$XHEPTY6, levels=HEPBTYPElevels, labels=HEPBTYPElabels)
NISPUF07$XHEPTY7 <- factor(NISPUF07$XHEPTY7, levels=HEPBTYPElevels, labels=HEPBTYPElabels)
NISPUF07$XHEPTY8 <- factor(NISPUF07$XHEPTY8, levels=HEPBTYPElevels, labels=HEPBTYPElabels)

NISPUF07$XHEPTY9 <- factor(NISPUF07$XHEPTY9, levels=HEPBTYPElevels, labels=HEPBTYPElabels)
NISPUF07$XHIBTY1 <- factor(NISPUF07$XHIBTY1, levels=HIBTYPElevels, labels=HIBTYPElabels)
NISPUF07$XHIBTY2 <- factor(NISPUF07$XHIBTY2, levels=HIBTYPElevels, labels=HIBTYPElabels)
NISPUF07$XHIBTY3 <- factor(NISPUF07$XHIBTY3, levels=HIBTYPElevels, labels=HIBTYPElabels)
NISPUF07$XHIBTY4 <- factor(NISPUF07$XHIBTY4, levels=HIBTYPElevels, labels=HIBTYPElabels)

NISPUF07$XHIBTY5 <- factor(NISPUF07$XHIBTY5, levels=HIBTYPElevels, labels=HIBTYPElabels)
NISPUF07$XHIBTY6 <- factor(NISPUF07$XHIBTY6, levels=HIBTYPElevels, labels=HIBTYPElabels)
NISPUF07$XHIBTY7 <- factor(NISPUF07$XHIBTY7, levels=HIBTYPElevels, labels=HIBTYPElabels)
NISPUF07$XHIBTY8 <- factor(NISPUF07$XHIBTY8, levels=HIBTYPElevels, labels=HIBTYPElabels)
NISPUF07$XHIBTY9 <- factor(NISPUF07$XHIBTY9, levels=HIBTYPElevels, labels=HIBTYPElabels)

NISPUF07$XMMRTY1 <- factor(NISPUF07$XMMRTY1, levels=MEASLESTYPElevels, labels=MEASLESTYPElabels)
NISPUF07$XMMRTY2 <- factor(NISPUF07$XMMRTY2, levels=MEASLESTYPElevels, labels=MEASLESTYPElabels)
NISPUF07$XMMRTY3 <- factor(NISPUF07$XMMRTY3, levels=MEASLESTYPElevels, labels=MEASLESTYPElabels)
NISPUF07$XMMRTY4 <- factor(NISPUF07$XMMRTY4, levels=MEASLESTYPElevels, labels=MEASLESTYPElabels)
NISPUF07$XMMRTY5 <- factor(NISPUF07$XMMRTY5, levels=MEASLESTYPElevels, labels=MEASLESTYPElabels)

NISPUF07$XMMRTY6 <- factor(NISPUF07$XMMRTY6, levels=MEASLESTYPElevels, labels=MEASLESTYPElabels)
NISPUF07$XMMRTY7 <- factor(NISPUF07$XMMRTY7, levels=MEASLESTYPElevels, labels=MEASLESTYPElabels)
NISPUF07$XMMRTY8 <- factor(NISPUF07$XMMRTY8, levels=MEASLESTYPElevels, labels=MEASLESTYPElabels)
NISPUF07$XMMRTY9 <- factor(NISPUF07$XMMRTY9, levels=MEASLESTYPElevels, labels=MEASLESTYPElabels)
NISPUF07$XPCVTY1 <- factor(NISPUF07$XPCVTY1, levels=PCVTYPElevels, labels=PCVTYPElabels)

NISPUF07$XPCVTY2 <- factor(NISPUF07$XPCVTY2, levels=PCVTYPElevels, labels=PCVTYPElabels)
NISPUF07$XPCVTY3 <- factor(NISPUF07$XPCVTY3, levels=PCVTYPElevels, labels=PCVTYPElabels)
NISPUF07$XPCVTY4 <- factor(NISPUF07$XPCVTY4, levels=PCVTYPElevels, labels=PCVTYPElabels)
NISPUF07$XPCVTY5 <- factor(NISPUF07$XPCVTY5, levels=PCVTYPElevels, labels=PCVTYPElabels)
NISPUF07$XPCVTY6 <- factor(NISPUF07$XPCVTY6, levels=PCVTYPElevels, labels=PCVTYPElabels)

NISPUF07$XPCVTY7 <- factor(NISPUF07$XPCVTY7, levels=PCVTYPElevels, labels=PCVTYPElabels)
NISPUF07$XPCVTY8 <- factor(NISPUF07$XPCVTY8, levels=PCVTYPElevels, labels=PCVTYPElabels)
NISPUF07$XPCVTY9 <- factor(NISPUF07$XPCVTY9, levels=PCVTYPElevels, labels=PCVTYPElabels)
NISPUF07$XPOLTY1 <- factor(NISPUF07$XPOLTY1, levels=POLIOTYPElevels, labels=POLIOTYPElabels)
NISPUF07$XPOLTY2 <- factor(NISPUF07$XPOLTY2, levels=POLIOTYPElevels, labels=POLIOTYPElabels)

NISPUF07$XPOLTY3 <- factor(NISPUF07$XPOLTY3, levels=POLIOTYPElevels, labels=POLIOTYPElabels)
NISPUF07$XPOLTY4 <- factor(NISPUF07$XPOLTY4, levels=POLIOTYPElevels, labels=POLIOTYPElabels)
NISPUF07$XPOLTY5 <- factor(NISPUF07$XPOLTY5, levels=POLIOTYPElevels, labels=POLIOTYPElabels)
NISPUF07$XPOLTY6 <- factor(NISPUF07$XPOLTY6, levels=POLIOTYPElevels, labels=POLIOTYPElabels)
NISPUF07$XPOLTY7 <- factor(NISPUF07$XPOLTY7, levels=POLIOTYPElevels, labels=POLIOTYPElabels)

NISPUF07$XPOLTY8 <- factor(NISPUF07$XPOLTY8, levels=POLIOTYPElevels, labels=POLIOTYPElabels)
NISPUF07$XPOLTY9 <- factor(NISPUF07$XPOLTY9, levels=POLIOTYPElevels, labels=POLIOTYPElabels)
NISPUF07$XVRCTY1 <- factor(NISPUF07$XVRCTY1, levels=VARTYPElevels, labels=VARTYPElabels)
NISPUF07$XVRCTY2 <- factor(NISPUF07$XVRCTY2, levels=VARTYPElevels, labels=VARTYPElabels)
NISPUF07$XVRCTY3 <- factor(NISPUF07$XVRCTY3, levels=VARTYPElevels, labels=VARTYPElabels)

NISPUF07$XVRCTY4 <- factor(NISPUF07$XVRCTY4, levels=VARTYPElevels, labels=VARTYPElabels)
NISPUF07$XVRCTY5 <- factor(NISPUF07$XVRCTY5, levels=VARTYPElevels, labels=VARTYPElabels)
NISPUF07$XVRCTY6 <- factor(NISPUF07$XVRCTY6, levels=VARTYPElevels, labels=VARTYPElabels)
NISPUF07$XVRCTY7 <- factor(NISPUF07$XVRCTY7, levels=VARTYPElevels, labels=VARTYPElabels)
NISPUF07$XVRCTY8 <- factor(NISPUF07$XVRCTY8, levels=VARTYPElevels, labels=VARTYPElabels)

NISPUF07$XVRCTY9 <- factor(NISPUF07$XVRCTY9, levels=VARTYPElevels, labels=VARTYPElabels)
NISPUF07$HEP_BRTH <- factor(NISPUF07$HEP_BRTH, levels=HEPBRTlevels, labels=HEPBRTlabels)
NISPUF07$HEP_FLAG <- factor(NISPUF07$HEP_FLAG, levels=HEPFLGlevels, labels=HEPFLGlabels)
NISPUF07$P_U12VRC <- factor(NISPUF07$P_U12VRC, levels=UTDlevels, labels=UTDlabels)
NISPUF07$P_UTD331 <- factor(NISPUF07$P_UTD331, levels=UTDlevels, labels=UTDlabels)

NISPUF07$P_UTD431 <- factor(NISPUF07$P_UTD431, levels=UTDlevels, labels=UTDlabels)
NISPUF07$P_UTDHEP <- factor(NISPUF07$P_UTDHEP, levels=UTDlevels, labels=UTDlabels)
NISPUF07$P_UTDHIB <- factor(NISPUF07$P_UTDHIB, levels=UTDlevels, labels=UTDlabels)
NISPUF07$P_UTDMCV <- factor(NISPUF07$P_UTDMCV, levels=UTDlevels, labels=UTDlabels)
NISPUF07$P_UTDMMX <- factor(NISPUF07$P_UTDMMX, levels=UTDlevels, labels=UTDlabels)

NISPUF07$P_UTDPC3 <- factor(NISPUF07$P_UTDPC3, levels=UTDlevels, labels=UTDlabels)
NISPUF07$P_UTDPCV <- factor(NISPUF07$P_UTDPCV, levels=UTDlevels, labels=UTDlabels)
NISPUF07$P_UTDPOL <- factor(NISPUF07$P_UTDPOL, levels=UTDlevels, labels=UTDlabels)
NISPUF07$P_UTDTP3 <- factor(NISPUF07$P_UTDTP3, levels=UTDlevels, labels=UTDlabels)
NISPUF07$P_UTDTP4 <- factor(NISPUF07$P_UTDTP4, levels=UTDlevels, labels=UTDlabels)

NISPUF07$PU431331 <- factor(NISPUF07$PU431331, levels=UTDlevels, labels=UTDlabels)
NISPUF07$PU4313313 <- factor(NISPUF07$PU4313313, levels=UTDlevels, labels=UTDlabels)
NISPUF07$PU4313314 <- factor(NISPUF07$PU4313314, levels=UTDlevels, labels=UTDlabels)

NISPUF07$PUT43133 <- factor(NISPUF07$PUT43133, levels=UTDlevels, labels=UTDlabels)
NISPUF07$PUTD4313 <- factor(NISPUF07$PUTD4313, levels=UTDlevels, labels=UTDlabels)
NISPUF07$CEN_REG <- factor(NISPUF07$CEN_REG, levels=CENREGlevels, labels=CENREGlabels)
NISPUF07$STATE <- factor(NISPUF07$STATE, levels=STATElevels, labels=STATElabels)

NISPUF07$P_UTDFL1 <- factor(NISPUF07$P_UTDFL1, levels=FLUUTDlevels, labels=FLUUTDlabels)
NISPUF07$P_UTDFL2 <- factor(NISPUF07$P_UTDFL2, levels=FLUUTDlevels, labels=FLUUTDlabels)
NISPUF07$P_UTDFL3 <- factor(NISPUF07$P_UTDFL3, levels=FLUUTDlevels, labels=FLUUTDlabels)
NISPUF07$RACE_K <- factor(NISPUF07$RACE_K, levels=RACE_PUFlevels, labels=RACE_PUFlabels)
NISPUF07$MARITAL <- factor(NISPUF07$MARITAL, levels=MAR_PUFlevels, labels=MAR_PUFlabels)
NISPUF07$AGECPOXR <- factor(NISPUF07$AGECPOXR, levels=AGECPOXRlevels, labels=AGECPOXRlabels)

NISPUF07$C1R <- factor(NISPUF07$C1R, levels=C1Rlevels, labels=C1Rlabels)
NISPUF07$C5R <- factor(NISPUF07$C5R, levels=C5Rlevels, labels=C5Rlabels)
NISPUF07$INOPHONR <- factor(NISPUF07$INOPHONR, levels=INOPHONRlevels, labels=INOPHONRlabels)
NISPUF07$INCQ298A <- factor(NISPUF07$INCQ298A, levels=INCQ298Alevels, labels=INCQ298Alabels)
NISPUF07$RACEETHK <- factor(NISPUF07$RACEETHK, levels=RACEETHKlevels, labels=RACEETHKlabels)

NISPUF07$D6R <- factor(NISPUF07$D6R, levels=D6Rlevels, labels=D6Rlabels)
NISPUF07$N_PRVR <- factor(NISPUF07$N_PRVR, levels=D6Rlevels, labels=D6Rlabels)
NISPUF07$FRSTBRN <- factor(NISPUF07$FRSTBRN, levels=FRSTBRNlevels, labels=FRSTBRNlabels)
NISPUF07$ESTIAP07 <- factor(NISPUF07$ESTIAP07, levels=ESTIAPlevels, labels=ESTIAPlabels)

##########################################################################
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE        #
##########################################################################

#---CONTENTS---#
NISPUF07.CONTENTS <- contents(NISPUF07)$contents

print(NISPUF07.CONTENTS)

#IN CASE THAT THE R CONSOLE CANNOT DISPLAY WHOLE CONTENTS,
#YOU CAN SAVE CONTENTS INTO A FILE
#write.table(NISPUF07.CONTENTS, file=paste(PUF,"/file-name",sep=""))

#---UNWEIGHTED FREQUENCY---#
unwt_freq <- function(UNWT.VAR){#FUNCTION TO PRINT UNWEIGHTED FREQUENCIES

unwt.tab <- wtd.table(UNWT.VAR, weights= NULL, type='table')
unwtd.freq <- data.frame(cbind(
unwt.tab, round(unwt.tab/sum(unwt.tab)*100,2),
cumsum(unwt.tab), cumsum(round(unwt.tab/sum(unwt.tab)*100,2))))
names(unwtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
unwtd.title <- paste('2007 NIS', 'UNWEIGHTED FREQUENCIES', label(UNWT.VAR), sep="\n")
label(unwtd.freq) <- unwtd.title

print(unwtd.freq)
}

UNWT.VAR <- NISPUF07$AGEGRP	#INPUT A VARIABLE OF INTEREST
unwt_freq(UNWT.VAR)

#---WEIGHTED FREQUENCY---#
WT <- NISPUF07$RDDWT		#INPUT A WEIGHT VARIABLE
WT.VAR <- NISPUF07$AGEGRP	#INPUT A VARIABLE OF INTEREST

wt.tab <- wtd.table(WT.VAR, weights= WT, type='table')
wtd.freq <- data.frame(cbind(
wt.tab, round(wt.tab/sum(wt.tab)*100,2),
cumsum(wt.tab), cumsum(round(wt.tab/sum(wt.tab)*100,2))))
names(wtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
wtd.title <- paste('2007 NIS PUBLIC USE FILE', 'WEIGHTED FREQUENCIES', label(WT.VAR), sep="\n")
label(wtd.freq) <- wtd.title

print(wtd.freq)
