############################################################################
# PROGRAM:  NISPUF09.R                                                     #
#                                                                          #
# PURPOSE:  THIS R   PROGRAM CREATES A PERMANENT R DATASET                 #
#                FROM THE 2009 NIS PUBLIC-USE ASCII FILE                   #
#                                                                          #
# NOTES:    THIS PROGRAM IS DIVIDED INTO SEVEN STEPS AS FOLLOWS:           #
#                                                                          #
# STEP 1:   LOAD AN R PACKAGE AND ASSIGN FILE NAMES                        #
#                                                                          #
#		 ONE R PACKAGE FOR TWO FUNCTIONS (CONTENTS, WTD.TABLE)         #
#		 WILL BE LOADED	                                             #
#		 THE USER CAN ENTER THE PATH TO THE ASCII DATA FILE AND        #
#		 THE PATH WHERE THE R DATASET WILL BE CREATED                  #
#                                                                          #
# STEP 2:   CREATE FORMATS                                                 #
#                                                                          #
# STEP 3:   READ THE FLAT DATA FILE                                        #
#                                                                          #
# STEP 4:   ASSIGN VARIABLE LABELS                                         #
#                                                                          #
# STEP 5:   CREATE A PERMANENT R DATASET                                   #
#                                                                          #
# STEP 6:   ASSIGN FORMATS                                                 #
#                                                                          #
#	   FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES IN R    	   #
#                                                                          #
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE          #
#                                                                          #
############################################################################

############################################################################
# Step 1:   LOAD R PACKAGES AND ASSIGN FILE NAMES                          #
############################################################################
#Users may need to install the Hmisc library before invoking it.
library(Hmisc) #TO USE contents()

#---USE SLASH(/) TO SEPERATE A FILE PATH---#
PUF <- "path-to-data"

flatfile <- "path-to-file/NISPUF09.DAT"



############################################################################
# Step 2:   CREATE FORMATS                                                 #
############################################################################

AGEGRPlevels=c(1,2,3)
AGEGRPlabels=c("19 - 23 MONTHS", "24 - 29 MONTHS", "30 - 35 MONTHS")

LANGUAGElevels=c(1,2,3)
LANGUAGElabels=c("ENGLISH", "SPANISH", "OTHER")

YNDKRFlevels=c(1,2,77,99)
YNDKRFlabels=c("YES", "NO", "DON'T KNOW", "REFUSED")

SHOTCOUNlevels=c(77,88,99)
SHOTCOUNlabels=c("DON'T KNOW", "1+ BUT UNKNOWN NUMBER", "REFUSED")

SCUTDlevels=c(1,2,77,88,99)
SCUTDlabels=c("UTD / SC", "NOT UTD / SC", "DON'T KNOW", "UNKNOWN", "REFUSED")

HHNUMlevels=c(0,1,50,77,99)
HHNUMlabels=c("NONE", "AT LEAST ONE", "ALL", "DON'T KNOW", "REFUSED")

YNlevels=c(1,2)
YNlabels=c("YES", "NO")

SHOTCARDlevels=c(1,2)
SHOTCARDlabels=c("SHOTCARD", "NO SHOTCARD")

Ylevels=c(1)
Ylabels=c("YES")

CHILDNMlevels=c(1,2,3,77,99)
CHILDNMlabels=c("ONE", "TWO OR THREE", "FOUR OR MORE", "DON'T KNOW", "REFUSED")

CWIClevels=c(1,2,3,77,99)
CWIClabels=c("YES", "NO", "NEVER HEARD OF WIC", "DON'T KNOW", "REFUSED")

EDUC1_levels=c(1,2,3,4,77,99)
EDUC1_labels=c("< 12 YEARS", "12 YEARS", "> 12 YEARS, NON-COLLEGE GRAD", "COLLEGE GRAD", "DON'T KNOW", "REFUSED")

HISPlevels=c(1,2,3,4,5)
HISPlabels=c("HISPANIC", "NON-HISPANIC", "OTHER", "DON'T KNOW", "REFUSED")

MAGEGRPlevels=c(1,2,3,77,99)
MAGEGRPlabels=c("<= 19 YEARS", "20 - 29 YEARS", ">= 30 YEARS", "DON'T KNOW", "REFUSED")

MOBILlevels=c(1,2,77,99)
MOBILlabels=c("MOVED FROM DIFFERENT STATE", "DID NOT MOVE FROM DIFFERENT STATE", "DON'T KNOW", "REFUSED")

SEXlevels=c(1,2,77,99)
SEXlabels=c("MALE", "FEMALE", "DON'T KNOW", "REFUSED")

INCPOVlevels=c(1,2,3,4)
INCPOVlabels=c("ABOVE POVERTY, > $75K", "ABOVE POVERTY, <= $75K", "BELOW POVERTY", "UNKNOWN")

DISPlevels=c(1,10,11,2,3,4,5,6,7,8,9)
DISPlabels=c("COMPLETE PROVIDER INFO, NO PROBLEMS", "INCOMPLETE PROVIDER RESP, HH NOT EXACT", "INCOMPLETE PROVIDER RESP, HH WITHOUT SHOT CARD", "COMPLETE PROVIDER INFO, NO SHOT CARD", "COMPLETE PROVIDER INFO, POOR HISTORY",
"COMPLETE PROVIDER INFO, POOR HIST/OTHER", "INCOMPLETE PROVIDER RESP, BUT 4:3:1:3:3 INDICATED", "INCOMPLETE PROVIDER RESP, INFO MATCHES", "INCOMPLETE PROVIDER RESP, HISTORY UNKNOWN", "INCOMPLETE PROVIDER RESP, 4:3:1:3:3 WITH HH",
"INCOMPLETE PROVIDER RESP, MATCHES HH")

HASPDA2Flevels=c(1,2)
HASPDA2Flabels=c("CHILD HAS ADEQUATE PROVIDER DATA OR ZERO VACCINATIONS", "CHILD DOES NOT HAVE ADEQUATE PROVIDER DATA")

PROVIDlevels=c(1,2,3,4,5,6,7)
PROVIDlabels=c("ALL PUBLIC FACILITIES", "ALL HOSPITAL FACILITIES", "ALL PRIVATE FACILITIES", "ALL MILITARY/OTHER FACILITIES", "MIXED", "TYPE OF PROVIDER UNKNOWN", "ALL WIC CLINIC PROVIDERS")

REGISTRYlevels=c(1,2,3,4)
REGISTRYlabels=c("ALL PROVIDERS", "SOME BUT POSSIBLY OR DEFINITELY NOT ALL PROVIDERS", "NO PROVIDERS", "UNKNOWN/DON'T KNOW")

TYPElevels=c("","01","02","03","04","05","07","08","20","21","22","30","31","32","33","43","44","60","70","71","72","BC","D3","DH","DK","FL","FM","FN","FO","H2","HA","HB","HG","HI","HM","HS","MA","MB","MM","MP","NC","OT","RB","RG","RM","RO","TY","UN","VA",
"VM","VO","YF")
TYPElabels=c("MISSING", "DT", "DTP", "DTP-UNKNOWN", "DTAP", "DTP-HIB", "DTAP-HIB", "DTAP-HEPB-IPV", "OPV", "IPV", "POLIO-UNKNOWN", "MMR", "MEASLES ONLY", "MEASLES-MUMPS", "MEASLES-RUBELLA", "HEPB-HIB", "HIB ONLY-UNKNOWN", "HEPB ONLY", "PCV CONJUGATE",
"PCV POLYSACCHARIDE", "PCV-UNKNOWN", "BCG (TUBERCULOSIS)", "DTAP-IPV-HIB", "DTP-HEPB", "DON'T KNOW", "SEASONAL FLU-UNKNOWN", "SEASONAL FLU SPRAY", "SEASONAL FLU INJECTED", "FOUR-IN-ONE", "HIB (SANOFI OR GLAXOSMITHKLINE)", "HEPA", "HEPB-UNKNOWN",
"HIB (GLAXOSMITHKLINE)", "HIB-UNKNOWN", "HIB (MERCK)", "HIB (SANOFI)", "MALARIA", "MUMPS-RUBELLA", "MCV-UNKNOWN", "MUMPS", "NEVER CODABLE", "OTHER", "RUBELLA", "ROTARIX (GSK)", "ROTATEQ (MERCK)", "ROTAVIRUS-UNKNOWN", "TYPHOID", "UNCODABLE",
"VARICELLA-UNKNOWN", "MMR-VARICELLA", "VARICELLA-ONLY", "YELLOW FEVER")

HEPBRTlevels=c(1,2)
HEPBRTlabels=c("AT LEAST ONE PROVIDER CHECKED GIVEN AT BIRTH", "NO PROVIDERS CHECKED GIVEN AT BIRTH")

HEPFLGlevels=c(1,2)
HEPFLGlabels=c("HEPB BIRTH SHOT DATE IMPUTED FROM SHOTCARD", "HEPB BIRTH SHOT DATE IMPUTED FROM DISTRIBUTION OF BIRTH DOSE DATES")

UTDlevels=c(0,1)
UTDlabels=c("NOT UTD", "UTD")

CENREGlevels=c(1,2,3,4)
CENREGlabels=c("NORTHEAST", "MIDWEST", "SOUTH", "WEST")

STATElevels=c(1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,24,25,26,27,28,29,3,30,31,32,33,34,35,36,37,38,39,4,40,41,42,43,44,45,46,47,48,49,5,50,51,52,53,54,55,56,6,7,78,8,9)
STATElabels=c("ALABAMA", "DELAWARE", "DISTRICT OF COLUMBIA", "FLORIDA", "GEORGIA", "", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "ALASKA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA",
"MISSISSIPPI", "MISSOURI", "", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", "ARIZONA", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "", "RHODE ISLAND", "SOUTH CAROLINA",
"SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH", "ARKANSAS", "VERMONT", "VIRGINIA", "", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING", "CALIFORNIA", "", "U.S.  VIRGIN ISLANDS", "COLORADO", "CONNECTICUT")

FLUUTDlevels=c(1,2,3)
FLUUTDlabels=c("VACCINATED", "NOT VACCINATED", "NOT ELIGIBLE")

RACE_PUFlevels=c(1,2,3)
RACE_PUFlabels=c("WHITE ONLY", "BLACK ONLY", "OTHER + MULTIPLE RACE")

AGECPOXRlevels=c(1,2,3,4)
AGECPOXRlabels=c("0 TO 6 MONTHS OLD", "7 TO 12 MONTHS OLD", "13 TO 18 MONTHS OLD", "19+ MONTHS OLD")

C1Rlevels=c(1,2,3,4,5,6,7,8)
C1Rlabels=c("1", "2", "3", "4", "5", "6", "7", "8+")

C5Rlevels=c(1,2,3,4,77,99)
C5Rlabels=c("MOTHER (STEP, FOSTER, ADOPTIVE) OR FEMALE GUARDIAN", "FATHER (STEP, FOSTER, ADOPTIVE) OR MALE GUARDIAN", "GRANDPARENT", "OTHER FAMILY MEMBER/FRIEND", "DON'T KNOW", "REFUSED")

INOPHONRlevels=c(1,2,3)
INOPHONRlabels=c("7 TO 14 DAYS", "15 TO 30 DAYS", "31 TO 365 DAYS")

INCQ298Alevels=c(10,11,12,13,14,3,4,5,6,7,77,8,9,99)
INCQ298Alabels=c("$35001 - $40000", "$40001 - $50000", "$50001 - $60000", "$60001 - $75000", "$75001+", "$0 - $7500", "$7501 - $10000", "$10001 - $17500", "$17501 - $20000", "$20001 - $25000", "DON'T KNOW", "$25001 - $30000", "$30001 - $35000", "REFUSED")

RACEETHKlevels=c(1,2,3,4)
RACEETHKlabels=c("HISPANIC", "NON-HISPANIC WHITE ONLY", "NON-HISPANIC BLACK ONLY", "NON-HISPANIC OTHER + MULTIPLE RACE")

D6Rlevels=c(0,1,2,3)
D6Rlabels=c("0", "1", "2", "3+")

FRSTBRNlevels=c(1,2,77,99)
FRSTBRNlabels=c("NO", "YES", "DON'T KNOW", "REFUSED")

CHARIDlevels=c( )
CHARIDlabels=c("MISSING")

BFFORM08Flevels=c(888)
BFFORM08Flabels=c("NEVER FED FORMULA")

RENTOWNlevels=c(1,2,3,77,99)
RENTOWNlabels=c("OWNED OR BEING BOUGHT", "RENTED", "OTHER ARRANGMENT", "DON'T KNOW", "REFUSED")

NUM_PHONlevels=c(1,2,3,4,77,99)
NUM_PHONlabels=c("ONE", "TWO", "THREE OR MORE", "NONE", "DON'T KNOW", "REFUSED")

INS_STATlevels=c(1,2,3)
INS_STATlabels=c("YES", "NO", "NOT ASCERTAINED")

ESTIAP09Flevels=c(1,10,11,12,13,14,15,16,17,18,19,2,20,22,25,27,28,29,30,31,34,35,36,37,38,4,40,41,44,46,47,49,5,50,51,52,53,54,55,56,57,58,59,6,60,61,62,63,64,65,66,68,69,7,72,73,74,75,76,77,774,8,95,96)
ESTIAP09Flabels=c("CT", "NY-REST OF STATE", "NY-CITY OF NEW YORK", "DC", "DE", "MD-REST OF STATE", "MD-CITY OF BALTIMORE", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA", "AL", "FL", "GA", "KY", "MS", "NC", "SC", "TN", "IL-REST OF STATE",
"IL-CITY OF CHICAGO", "IN-REST OF STATE", "IN-MARION COUNTY", "MI", "ME", "MN", "OH", "WI", "AR", "LA", "NM", "NH", "OK", "TX-REST OF STATE", "TX-DALLAS COUNTY", "TX-EL PASO COUNTY", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS", "MO", "NE", "RI",
"CO", "MT", "ND", "SD", "UT", "WY", "AZ", "CA-REST OF STATE", "CA-LOS ANGELES COUNTY", "VT", "HI", "NV", "AK", "ID", "OR", "WA-REST OF STATE", "WA-EASTERN/WESTERN WA", "NJ", "U.S. VIRGIN ISLANDS", "IN-LAKE COUNTY")

MAR_PUF2_levels=c(1,2)
MAR_PUF2_labels=c("MARRIED", "NEVER MARRIED/WIDOWED/DIVORCED/SEPARATED/DECEASED")


############################################################################
# Step 3:   READ THE FLAT DATA FILE                                        #
############################################################################

LIST.NAMEWIDTH <-
c("SEQNUMC",6,
"SEQNUMHH",5,
"PDAT",1,
"PROVWT",20,
"PROVWTVI",20,
"RDDWT",19,
"RDDWTVI",19,
"YEAR",4,
"AGECPOXR",1,
"SC_431",2,
"SC_4313",2,
"SC_43133",2,
"SC_DTP",2,
"SC_HEPB",2,
"SC_HIB",2,
"SC_MCV",2,
"SC_POL",2,
"SC_VRC",2,
"HH_DTP",2,
"HH_HEPB",2,
"HH_HIB",2,
"HH_MCV",2,
"HH_POL",2,
"HH_VRC",2,
"HAD_CPOX",2,
"SHOTCARD",1,
"AGEGRP",1,
"BF_ENDR06",8,
"BF_EXCLR06",8,
"BF_FORMR08",8,
"BFENDFL06",1,
"BFFORMFL06",1,
"C1R",1,
"C5R",2,
"CBF_01",2,
"CEN_REG",1,
"CHILDNM",1,
"CWIC_01",2,
"CWIC_02",2,
"EDUC1",1,
"FRSTBRN",1,
"I_HISP_K",1,
"INCPORAR",16,
"INCPOV1",1,
"INCQ298A",2,
"INOPHONR",1,
"INTRP",1,
"LANGUAGE",1,
"M_AGEGRP",1,
"MARITAL2",1,
"MOBIL_I",1,
"NUM_PHONE",2,
"NUM_CELLS_HH",2,
"NUM_CELLS_PARENTS",2,
"RACE_K",1,
"RACEETHK",1,
"RENT_OWN",2,
"SEX",1,
"ESTIAP09",3,
"STATE",2,
"D6R",1,
"D7",1,
"DISPCODE",2,
"N_PRVR",1,
"PROV_FAC",1,
"REGISTRY",1,
"VFC_ORDER",1,
"HEP_BRTH",1,
"HEP_FLAG",1,
"P_NUHEPX",1,
"P_NUHIBX",1,
"P_NUHPHB",1,
"P_NUMDAH",1,
"P_NUMDHI",1,
"P_NUMDIH",1,
"P_NUMDTA",1,
"P_NUMDTP",1,
"P_NUMFLU",1,
"P_NUMFLUL",1,
"P_NUMFLUM",1,
"P_NUMFLUN",1,
"P_NUMHEA",1,
"P_NUMHEN",1,
"P_NUMHEP",1,
"P_NUMHIB",1,
"P_NUMHIN",1,
"P_NUMHION",1,
"P_NUMHM",1,
"P_NUMH2",1,
"P_NUMIPV",1,
"P_NUMMCN",1,
"P_NUMMMR",1,
"P_NUMMMRX",1,
"P_NUMMMX",1,
"P_NUMMP",1,
"P_NUMMPR",1,
"P_NUMMRV",1,
"P_NUMMS",1,
"P_NUMMSM",1,
"P_NUMMSR",1,
"P_NUMOLN",1,
"P_NUMOPV",1,
"P_NUMPCC",1,
"P_NUMPCN",1,
"P_NUMPCP",1,
"P_NUMPCV",1,
"P_NUMPOL",1,
"P_NUMRB",1,
"P_NUMRG",1,
"P_NUMRM",1,
"P_NUMRO",1,
"P_NUMROT",1,
"P_NUMTPN",1,
"P_NUMVRC",1,
"P_NUMVRN",1,
"P_NUMVRX",1,
"P_U12VRC",1,
"P_UTD331",1,
"P_UTD431",1,
"P_UTDFL1",1,
"P_UTDFL2",1,
"P_UTDFL3",1,
"P_UTDHEP",1,
"P_UTDHIB",1,
"P_UTDHIB_ROUT_S",1,
"P_UTDHIB_SHORT_S",1,
"P_UTDMCV",1,
"P_UTDMMX",1,
"P_UTDPC3",1,
"P_UTDPCV",1,
"P_UTDPOL",1,
"P_UTDROT_S",1,
"P_UTDTP3",1,
"P_UTDTP4",1,
"PU431331",1,
"P_UTD431H31_ROUT_S",1,
"PU4313313",1,
"P_UTD431H313_ROUT_S",1,
"PU4313314",1,
"P_UTD431H314_ROUT_S",1,
"PUT43133",1,
"P_UTD431H3_ROUT_S",1,
"PUTD4313",1,
"P_UTD431H_ROUT_S",1,
"DDTP1",4,
"DDTP2",4,
"DDTP3",4,
"DDTP4",4,
"DDTP5",4,
"DDTP6",3,
"DDTP7",3,
"DDTP8",1,
"DDTP9",1,
"DFLU1",4,
"DFLU2",4,
"DFLU3",4,
"DFLU4",4,
"DFLU5",4,
"DFLU6",1,
"DFLU7",1,
"DFLU8",1,
"DFLU9",1,
"DHEPA1",4,
"DHEPA2",4,
"DHEPA3",4,
"DHEPA4",3,
"DHEPA5",1,
"DHEPA6",1,
"DHEPA7",1,
"DHEPA8",1,
"DHEPA9",1,
"DHEPB1",3,
"DHEPB2",4,
"DHEPB3",4,
"DHEPB4",4,
"DHEPB5",3,
"DHEPB6",4,
"DHEPB7",3,
"DHEPB8",1,
"DHEPB9",1,
"DHIB1",4,
"DHIB2",4,
"DHIB3",4,
"DHIB4",4,
"DHIB5",4,
"DHIB6",3,
"DHIB7",1,
"DHIB8",1,
"DHIB9",1,
"DMMR1",4,
"DMMR2",4,
"DMMR3",3,
"DMMR4",1,
"DMMR5",1,
"DMMR6",1,
"DMMR7",1,
"DMMR8",1,
"DMMR9",1,
"DMP1",3,
"DMP2",1,
"DMP3",1,
"DMP4",1,
"DMP5",1,
"DMP6",1,
"DMP7",1,
"DMP8",1,
"DMP9",1,
"DMPRB1",1,
"DMPRB2",1,
"DMPRB3",1,
"DMPRB4",1,
"DMPRB5",1,
"DMPRB6",1,
"DMPRB7",1,
"DMPRB8",1,
"DMPRB9",1,
"DPCV1",4,
"DPCV2",4,
"DPCV3",4,
"DPCV4",4,
"DPCV5",4,
"DPCV6",3,
"DPCV7",1,
"DPCV8",1,
"DPCV9",1,
"DPOLIO1",4,
"DPOLIO2",4,
"DPOLIO3",4,
"DPOLIO4",4,
"DPOLIO5",4,
"DPOLIO6",3,
"DPOLIO7",1,
"DPOLIO8",1,
"DPOLIO9",1,
"DRB1",4,
"DRB2",1,
"DRB3",1,
"DRB4",1,
"DRB5",1,
"DRB6",1,
"DRB7",1,
"DRB8",1,
"DRB9",1,
"DROT1",3,
"DROT2",3,
"DROT3",3,
"DROT4",3,
"DROT5",1,
"DROT6",1,
"DROT7",1,
"DROT8",1,
"DROT9",1,
"DTP1_AGE",2,
"DTP2_AGE",2,
"DTP3_AGE",2,
"DTP4_AGE",2,
"DTP5_AGE",2,
"DTP6_AGE",2,
"DTP7_AGE",2,
"DTP8_AGE",1,
"DTP9_AGE",1,
"DVRC1",4,
"DVRC2",4,
"DVRC3",1,
"DVRC4",1,
"DVRC5",1,
"DVRC6",1,
"DVRC7",1,
"DVRC8",1,
"DVRC9",1,
"FLU1_AGE",2,
"FLU2_AGE",2,
"FLU3_AGE",2,
"FLU4_AGE",2,
"FLU5_AGE",2,
"FLU6_AGE",1,
"FLU7_AGE",1,
"FLU8_AGE",1,
"FLU9_AGE",1,
"HEA1_AGE",2,
"HEA2_AGE",2,
"HEA3_AGE",2,
"HEA4_AGE",2,
"HEA5_AGE",1,
"HEA6_AGE",1,
"HEA7_AGE",1,
"HEA8_AGE",1,
"HEA9_AGE",1,
"HEP1_AGE",2,
"HEP2_AGE",2,
"HEP3_AGE",2,
"HEP4_AGE",2,
"HEP5_AGE",2,
"HEP6_AGE",2,
"HEP7_AGE",2,
"HEP8_AGE",1,
"HEP9_AGE",1,
"HIB1_AGE",2,
"HIB2_AGE",2,
"HIB3_AGE",2,
"HIB4_AGE",2,
"HIB5_AGE",2,
"HIB6_AGE",2,
"HIB7_AGE",1,
"HIB8_AGE",1,
"HIB9_AGE",1,
"MMR1_AGE",2,
"MMR2_AGE",2,
"MMR3_AGE",2,
"MMR4_AGE",1,
"MMR5_AGE",1,
"MMR6_AGE",1,
"MMR7_AGE",1,
"MMR8_AGE",1,
"MMR9_AGE",1,
"MP1_AGE",2,
"MP2_AGE",1,
"MP3_AGE",1,
"MP4_AGE",1,
"MP5_AGE",1,
"MP6_AGE",1,
"MP7_AGE",1,
"MP8_AGE",1,
"MP9_AGE",1,
"MPR1_AGE",1,
"MPR2_AGE",1,
"MPR3_AGE",1,
"MPR4_AGE",1,
"MPR5_AGE",1,
"MPR6_AGE",1,
"MPR7_AGE",1,
"MPR8_AGE",1,
"MPR9_AGE",1,
"PCV1_AGE",2,
"PCV2_AGE",2,
"PCV3_AGE",2,
"PCV4_AGE",2,
"PCV5_AGE",2,
"PCV6_AGE",2,
"PCV7_AGE",1,
"PCV8_AGE",1,
"PCV9_AGE",1,
"POL1_AGE",2,
"POL2_AGE",2,
"POL3_AGE",2,
"POL4_AGE",2,
"POL5_AGE",2,
"POL6_AGE",2,
"POL7_AGE",1,
"POL8_AGE",1,
"POL9_AGE",1,
"RB1_AGE",2,
"RB2_AGE",1,
"RB3_AGE",1,
"RB4_AGE",1,
"RB5_AGE",1,
"RB6_AGE",1,
"RB7_AGE",1,
"RB8_AGE",1,
"RB9_AGE",1,
"ROT1_AGE",2,
"ROT2_AGE",2,
"ROT3_AGE",2,
"ROT4_AGE",2,
"ROT5_AGE",1,
"ROT6_AGE",1,
"ROT7_AGE",1,
"ROT8_AGE",1,
"ROT9_AGE",1,
"VRC1_AGE",2,
"VRC2_AGE",2,
"VRC3_AGE",1,
"VRC4_AGE",1,
"VRC5_AGE",1,
"VRC6_AGE",1,
"VRC7_AGE",1,
"VRC8_AGE",1,
"VRC9_AGE",1,
"XDTPTY1",2,
"XDTPTY2",2,
"XDTPTY3",2,
"XDTPTY4",2,
"XDTPTY5",2,
"XDTPTY6",2,
"XDTPTY7",2,
"XDTPTY8",1,
"XDTPTY9",1,
"XFLUTY1",2,
"XFLUTY2",2,
"XFLUTY3",2,
"XFLUTY4",2,
"XFLUTY5",2,
"XFLUTY6",1,
"XFLUTY7",1,
"XFLUTY8",1,
"XFLUTY9",1,
"XHEPTY1",2,
"XHEPTY2",2,
"XHEPTY3",2,
"XHEPTY4",2,
"XHEPTY5",2,
"XHEPTY6",2,
"XHEPTY7",2,
"XHEPTY8",1,
"XHEPTY9",1,
"XHIBTY1",2,
"XHIBTY2",2,
"XHIBTY3",2,
"XHIBTY4",2,
"XHIBTY5",2,
"XHIBTY6",2,
"XHIBTY7",1,
"XHIBTY8",1,
"XHIBTY9",1,
"XMMRTY1",2,
"XMMRTY2",2,
"XMMRTY3",2,
"XMMRTY4",1,
"XMMRTY5",1,
"XMMRTY6",1,
"XMMRTY7",1,
"XMMRTY8",1,
"XMMRTY9",1,
"XPCVTY1",2,
"XPCVTY2",2,
"XPCVTY3",2,
"XPCVTY4",2,
"XPCVTY5",2,
"XPCVTY6",2,
"XPCVTY7",1,
"XPCVTY8",1,
"XPCVTY9",1,
"XPOLTY1",2,
"XPOLTY2",2,
"XPOLTY3",2,
"XPOLTY4",2,
"XPOLTY5",2,
"XPOLTY6",2,
"XPOLTY7",1,
"XPOLTY8",1,
"XPOLTY9",1,
"XROTTY1",2,
"XROTTY2",2,
"XROTTY3",2,
"XROTTY4",2,
"XROTTY5",1,
"XROTTY6",1,
"XROTTY7",1,
"XROTTY8",1,
"XROTTY9",1,
"XVRCTY1",2,
"XVRCTY2",2,
"XVRCTY3",1,
"XVRCTY4",1,
"XVRCTY5",1,
"XVRCTY6",1,
"XVRCTY7",1,
"XVRCTY8",1,
"XVRCTY9",1,
"INS_1",2,
"INS_2",2,
"INS_3",2,
"INS_3A",2,
"INS_4_5",2,
"INS_6",2,
"INS_11",2,
"VFC_I",1
)

NAMEWIDTH <- matrix(LIST.NAMEWIDTH, 467, 2, byrow=T, dimnames = list(NULL, c("VARIABLE","WIDTH")))
NA_STRING <- c(" ", ".", " .", "  .", "   .", "   .    ", " .              ", "    .              ", "     .              ", "     .             ")

NISPUF09 <- read.fwf(flatfile, widths= as.numeric(NAMEWIDTH[,2]), col.names = NAMEWIDTH[,1], na.strings= NA_STRING, as.is=TRUE)

NISPUF09$SEQNUMC <- as.character(NISPUF09$SEQNUMC)
NISPUF09$SEQNUMHH <- as.character(NISPUF09$SEQNUMHH)
NISPUF09$XDTPTY1 <- as.character(NISPUF09$XDTPTY1)
NISPUF09$XDTPTY2 <- as.character(NISPUF09$XDTPTY2)
NISPUF09$XDTPTY3 <- as.character(NISPUF09$XDTPTY3)
NISPUF09$XDTPTY4 <- as.character(NISPUF09$XDTPTY4)
NISPUF09$XDTPTY5 <- as.character(NISPUF09$XDTPTY5)
NISPUF09$XDTPTY6 <- as.character(NISPUF09$XDTPTY6)
NISPUF09$XDTPTY7 <- as.character(NISPUF09$XDTPTY7)
NISPUF09$XDTPTY8 <- as.character(NISPUF09$XDTPTY8)
NISPUF09$XDTPTY9 <- as.character(NISPUF09$XDTPTY9)
NISPUF09$XFLUTY1 <- as.character(NISPUF09$XFLUTY1)
NISPUF09$XFLUTY2 <- as.character(NISPUF09$XFLUTY2)
NISPUF09$XFLUTY3 <- as.character(NISPUF09$XFLUTY3)
NISPUF09$XFLUTY4 <- as.character(NISPUF09$XFLUTY4)
NISPUF09$XFLUTY5 <- as.character(NISPUF09$XFLUTY5)
NISPUF09$XFLUTY6 <- as.character(NISPUF09$XFLUTY6)
NISPUF09$XFLUTY7 <- as.character(NISPUF09$XFLUTY7)
NISPUF09$XFLUTY8 <- as.character(NISPUF09$XFLUTY8)
NISPUF09$XFLUTY9 <- as.character(NISPUF09$XFLUTY9)
NISPUF09$XHEPTY1 <- as.character(NISPUF09$XHEPTY1)
NISPUF09$XHEPTY2 <- as.character(NISPUF09$XHEPTY2)
NISPUF09$XHEPTY3 <- as.character(NISPUF09$XHEPTY3)
NISPUF09$XHEPTY4 <- as.character(NISPUF09$XHEPTY4)
NISPUF09$XHEPTY5 <- as.character(NISPUF09$XHEPTY5)
NISPUF09$XHEPTY6 <- as.character(NISPUF09$XHEPTY6)
NISPUF09$XHEPTY7 <- as.character(NISPUF09$XHEPTY7)
NISPUF09$XHEPTY8 <- as.character(NISPUF09$XHEPTY8)
NISPUF09$XHEPTY9 <- as.character(NISPUF09$XHEPTY9)
NISPUF09$XHIBTY1 <- as.character(NISPUF09$XHIBTY1)
NISPUF09$XHIBTY2 <- as.character(NISPUF09$XHIBTY2)
NISPUF09$XHIBTY3 <- as.character(NISPUF09$XHIBTY3)
NISPUF09$XHIBTY4 <- as.character(NISPUF09$XHIBTY4)
NISPUF09$XHIBTY5 <- as.character(NISPUF09$XHIBTY5)
NISPUF09$XHIBTY6 <- as.character(NISPUF09$XHIBTY6)
NISPUF09$XHIBTY7 <- as.character(NISPUF09$XHIBTY7)
NISPUF09$XHIBTY8 <- as.character(NISPUF09$XHIBTY8)
NISPUF09$XHIBTY9 <- as.character(NISPUF09$XHIBTY9)
NISPUF09$XMMRTY1 <- as.character(NISPUF09$XMMRTY1)
NISPUF09$XMMRTY2 <- as.character(NISPUF09$XMMRTY2)
NISPUF09$XMMRTY3 <- as.character(NISPUF09$XMMRTY3)
NISPUF09$XMMRTY4 <- as.character(NISPUF09$XMMRTY4)
NISPUF09$XMMRTY5 <- as.character(NISPUF09$XMMRTY5)
NISPUF09$XMMRTY6 <- as.character(NISPUF09$XMMRTY6)
NISPUF09$XMMRTY7 <- as.character(NISPUF09$XMMRTY7)
NISPUF09$XMMRTY8 <- as.character(NISPUF09$XMMRTY8)
NISPUF09$XMMRTY9 <- as.character(NISPUF09$XMMRTY9)
NISPUF09$XPCVTY1 <- as.character(NISPUF09$XPCVTY1)
NISPUF09$XPCVTY2 <- as.character(NISPUF09$XPCVTY2)
NISPUF09$XPCVTY3 <- as.character(NISPUF09$XPCVTY3)
NISPUF09$XPCVTY4 <- as.character(NISPUF09$XPCVTY4)
NISPUF09$XPCVTY5 <- as.character(NISPUF09$XPCVTY5)
NISPUF09$XPCVTY6 <- as.character(NISPUF09$XPCVTY6)
NISPUF09$XPCVTY7 <- as.character(NISPUF09$XPCVTY7)
NISPUF09$XPCVTY8 <- as.character(NISPUF09$XPCVTY8)
NISPUF09$XPCVTY9 <- as.character(NISPUF09$XPCVTY9)
NISPUF09$XPOLTY1 <- as.character(NISPUF09$XPOLTY1)
NISPUF09$XPOLTY2 <- as.character(NISPUF09$XPOLTY2)
NISPUF09$XPOLTY3 <- as.character(NISPUF09$XPOLTY3)
NISPUF09$XPOLTY4 <- as.character(NISPUF09$XPOLTY4)
NISPUF09$XPOLTY5 <- as.character(NISPUF09$XPOLTY5)
NISPUF09$XPOLTY6 <- as.character(NISPUF09$XPOLTY6)
NISPUF09$XPOLTY7 <- as.character(NISPUF09$XPOLTY7)
NISPUF09$XPOLTY8 <- as.character(NISPUF09$XPOLTY8)
NISPUF09$XPOLTY9 <- as.character(NISPUF09$XPOLTY9)
NISPUF09$XROTTY1 <- as.character(NISPUF09$XROTTY1)
NISPUF09$XROTTY2 <- as.character(NISPUF09$XROTTY2)
NISPUF09$XROTTY3 <- as.character(NISPUF09$XROTTY3)
NISPUF09$XROTTY4 <- as.character(NISPUF09$XROTTY4)
NISPUF09$XROTTY5 <- as.character(NISPUF09$XROTTY5)
NISPUF09$XROTTY6 <- as.character(NISPUF09$XROTTY6)
NISPUF09$XROTTY7 <- as.character(NISPUF09$XROTTY7)
NISPUF09$XROTTY8 <- as.character(NISPUF09$XROTTY8)
NISPUF09$XROTTY9 <- as.character(NISPUF09$XROTTY9)
NISPUF09$XVRCTY1 <- as.character(NISPUF09$XVRCTY1)
NISPUF09$XVRCTY2 <- as.character(NISPUF09$XVRCTY2)
NISPUF09$XVRCTY3 <- as.character(NISPUF09$XVRCTY3)
NISPUF09$XVRCTY4 <- as.character(NISPUF09$XVRCTY4)
NISPUF09$XVRCTY5 <- as.character(NISPUF09$XVRCTY5)
NISPUF09$XVRCTY6 <- as.character(NISPUF09$XVRCTY6)
NISPUF09$XVRCTY7 <- as.character(NISPUF09$XVRCTY7)
NISPUF09$XVRCTY8 <- as.character(NISPUF09$XVRCTY8)
NISPUF09$XVRCTY9 <- as.character(NISPUF09$XVRCTY9)

############################################################################
# Step 4:   ASSIGN VARIABLE LABELS                                         #
############################################################################

label(NISPUF09$SEQNUMC) <- "UNIQUE CHILD IDENTIFIER"
label(NISPUF09$SEQNUMHH) <- "UNIQUE HOUSEHOLD IDENTIFIER"
label(NISPUF09$PDAT) <- "CHILD HAS ADEQUATE PROVIDER DATA"
label(NISPUF09$PROVWT) <- "WEIGHT FOR CHILDREN WITH ADEQUATE PROVIDER DATA AND UNVACCINATED CHILDREN (EXCLUDING U.S. VIRGIN ISLANDS)"
label(NISPUF09$PROVWTVI) <- "WEIGHT FOR CHILDREN WITH ADEQUATE PROVIDER DATA AND UNVACCINATED CHILDREN (INCLUDING U.S. VIRGIN ISLANDS)"

label(NISPUF09$RDDWT) <- "HH-PHASE CHILD INTERVIEW WEIGHT (EXCLUDING U.S. VIRGIN ISLANDS)"
label(NISPUF09$RDDWTVI) <- "HH-PHASE CHILD INTERVIEW WEIGHT (INCLUDING U.S. VIRGIN ISLANDS)"
label(NISPUF09$YEAR) <- "YEAR OF INTERVIEW"
label(NISPUF09$AGECPOXR) <- "AGE IN MONTHS AT CHICKEN POX DISEASE (RECODE)"
label(NISPUF09$SC_431) <- "HH SHOT CARD REPORT OF 4:3:1 UP-TO-DATE"

label(NISPUF09$SC_4313) <- "HH SHOT CARD REPORT OF 4:3:1:3 UP-TO-DATE"
label(NISPUF09$SC_43133) <- "HH SHOT CARD REPORT OF 4:3:1:3:3 UP-TO-DATE"
label(NISPUF09$SC_DTP) <- "HH SHOT CARD REPORT OF 4+ DT-CONTAINING UP-TO-DATE"
label(NISPUF09$SC_HEPB) <- "HH SHOT CARD REPORT OF 3+ HEPATITIS B-CONTAINING UP-TO-DATE"
label(NISPUF09$SC_HIB) <- "HH SHOT CARD REPORT OF 3+ HIB-CONTAINING UP-TO-DATE"

label(NISPUF09$SC_MCV) <- "HH SHOT CARD REPORT OF 1+ MEASLES-CONTAINING UP-TO-DATE"
label(NISPUF09$SC_POL) <- "HH SHOT CARD REPORT OF 3+ POLIO-CONTAINING UP-TO-DATE"
label(NISPUF09$SC_VRC) <- "HH SHOT CARD REPORT OF 1+ VARICELLA-CONTAINING UP-TO-DATE"
label(NISPUF09$HH_DTP) <- "HH REPORT OF NUMBER OF DT-CONTAINING SHOTS RECEIVED"
label(NISPUF09$HH_HEPB) <- "HH REPORT OF NUMBER OF HEPATITIS B-CONTAINING SHOTS RECEIVED"

label(NISPUF09$HH_HIB) <- "HH REPORT OF NUMBER OF HIB-CONTAINING SHOTS RECEIVED"
label(NISPUF09$HH_MCV) <- "HH REPORT OF NUMBER OF MEASLES-CONTAINING SHOTS RECEIVED"
label(NISPUF09$HH_POL) <- "HH REPORT OF NUMBER OF POLIO-CONTAINING SHOTS RECEIVED"
label(NISPUF09$HH_VRC) <- "HH REPORT OF NUMBER OF VARICELLA-CONTAINING SHOTS RECEIVED"
label(NISPUF09$HAD_CPOX) <- "CHILD EVER HAD CHICKEN POX DISEASE?"

label(NISPUF09$SHOTCARD) <- "SHOT CARD USE FLAG"
label(NISPUF09$AGEGRP) <- "AGE CATEGORY OF CHILD (19-23, 24-29, 30-35 MO) (RECODE)"
label(NISPUF09$BF_ENDR06) <- "DURATION OF BREAST FEEDING IN DAYS (RECODE)"
label(NISPUF09$BF_EXCLR06) <- "DURATION OF EXCLUSIVE BREAST/FORMULA FEEDING IN DAYS (RECODE)"
label(NISPUF09$BF_FORMR08) <- "AGE IN DAYS WHEN CHILD FIRST FED FORMULA (RECODE)"

label(NISPUF09$BFENDFL06) <- "DURATION OF BREAST FEEDING EXCEEDS CHILD AGE IN DAYS, WITH BUFFER"
label(NISPUF09$BFFORMFL06) <- "AGE IN DAYS WHEN CHILD FIRST FED FORMULA EXCEEDS CHILD AGE IN DAYS, WITH BUFFER"
label(NISPUF09$C1R) <- "NUMBER OF PEOPLE IN HOUSEHOLD (RECODE)"
label(NISPUF09$C5R) <- "RELATIONSHIP OF RESPONDENT TO CHILD (RECODE)"
label(NISPUF09$CBF_01) <- "WAS CHILD EVER BREAST FED OR FED BREAST MILK?"

label(NISPUF09$CEN_REG) <- "CENSUS REGION BASED ON TRUE STATE OF RESIDENCE"
label(NISPUF09$CHILDNM) <- "NUMBER OF CHILDREN LESS THAN 18 YEARS IN HH (RECODE)"
label(NISPUF09$CWIC_01) <- "CHILD EVER RECEIVED WIC BENEFITS?"
label(NISPUF09$CWIC_02) <- "CHILD CURRENTLY RECEIVING WIC BENEFITS?"
label(NISPUF09$EDUC1) <- "EDUCATION OF MOTHER CATEGORIES (RECODE)"

label(NISPUF09$FRSTBRN) <- "FIRST BORN STATUS OF CHILD"
label(NISPUF09$I_HISP_K) <- "HISPANIC ORIGIN OF CHILD"
label(NISPUF09$INCPORAR) <- "INCOME TO POVERTY RATIO (RECODE)"
label(NISPUF09$INCPOV1) <- "POVERTY STATUS"
label(NISPUF09$INCQ298A) <- "FAMILY INCOME CATEGORIES (RECODE)"

label(NISPUF09$INOPHONR) <- "LENGTH OF INTERRUPTION IN TELEPHONE SERVICE IN DAYS (RECODE)"
label(NISPUF09$INTRP) <- "PHONE INTERRUPTION OF 7 DAYS OR MORE IN PAST YEAR?"
label(NISPUF09$LANGUAGE) <- "LANGUAGE IN WHICH INTERVIEW WAS CONDUCTED"
label(NISPUF09$M_AGEGRP) <- "AGE OF MOTHER CATEGORIES (RECODE)"
label(NISPUF09$MARITAL2) <- "MARITAL STATUS OF MOTHER (RECODE)"

label(NISPUF09$MOBIL_I) <- "GEOGRAPHIC MOBILITY STATUS: STATE OF RESIDENCE OF CHILD AT BIRTH VERSUS CURRENT STATE"
label(NISPUF09$NUM_PHONE) <- "NUMBER OF RESIDENTIAL TELEPHONE NUMBERS IN HOUSEHOLD (EXCLUDING CELL PHONES)"
label(NISPUF09$NUM_CELLS_HH) <- "NUMBER OF WORKING CELL PHONES HOUSEHOLD MEMBERS HAVE AVAILABLE FOR PERSONAL USE"
label(NISPUF09$NUM_CELLS_PARENTS) <- "NUMBER OF WORKING CELL PHONES USUALLY USED BY PARENTS OR GUARDIANS"
label(NISPUF09$RACE_K) <- "RACE OF CHILD (RECODE)"

label(NISPUF09$RACEETHK) <- "RACE/ETHNICITY OF CHILD (RECODE)"
label(NISPUF09$RENT_OWN) <- "IS HOME OWNED/BEING BOUGHT, RENTED, OR OCCUPIED BY SOME OTHER ARRANGEMENT?"
label(NISPUF09$SEX) <- "GENDER OF CHILD"
label(NISPUF09$ESTIAP09) <- "ESTIMATION AREA OF RESIDENCE"
label(NISPUF09$STATE) <- "TRUE STATE OF RESIDENCE (STATE FIPS CODE)"

label(NISPUF09$D6R) <- "NUMBER OF VACCINATION PROVIDERS IDENTIFIED BY RESPONDENT (RECODE)"
label(NISPUF09$D7) <- "CONSENT TO OBTAIN CHILD'S IMMUNIZATION RECORDS FROM PROVIDERS"
label(NISPUF09$DISPCODE) <- "NIS PROVIDER RECORD-CHECK DISPOSITION CODE"
label(NISPUF09$N_PRVR) <- "NUMBER OF PROVIDERS RESPONDING WITH VACCINATION DATA FOR CHILD (RECODE)"
label(NISPUF09$PROV_FAC) <- "PROVIDER FACILITY TYPES"

label(NISPUF09$REGISTRY) <- "CHILD'S PROVIDERS REPORTED CHILD'S VACCINATIONS TO IMMUNIZATION REGISTRY"
label(NISPUF09$VFC_ORDER) <- "DO CHILD'S PROVIDERS ORDER VACCINES FROM STATE/LOCAL HEALTH DEPT?"
label(NISPUF09$HEP_BRTH) <- "HEPATITIS B-CONTAINING SHOT GIVEN AT BIRTH FLAG"
label(NISPUF09$HEP_FLAG) <- "HEPATITIS B BIRTH SHOT DATE IMPUTATION FLAG"
label(NISPUF09$P_NUHEPX) <- "NUMBER OF HEPATITIS B-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF09$P_NUHIBX) <- "NUMBER OF HIB-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUHPHB) <- "NUMBER OF HEPATITIS B/HIB COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMDAH) <- "NUMBER OF DTAP/HIB COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMDHI) <- "NUMBER OF DTAP/HEPB/IPV COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMDIH) <- "NUMBER OF DTAP/IPV/HIB COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF09$P_NUMDTA) <- "NUMBER OF DTAP-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMDTP) <- "NUMBER OF DT-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMFLU) <- "NUMBER OF SEASONAL FLU-CONTAINING VACCINATIONS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMFLUL) <- "NUMBER OF SEASONAL FLU-CONTAINING VACCINATIONS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMFLUM) <- "NUMBER OF SEASONAL FLU SPRAY VACCINATIONS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF09$P_NUMFLUN) <- "NUMBER OF INJECTED SEASONAL FLU VACCINATIONS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMHEA) <- "NUMBER OF HEPATITIS A-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMHEN) <- "NUMBER OF HEPATITIS B-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMHEP) <- "NUMBER OF HEPATITIS B-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMHIB) <- "NUMBER OF HIB-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF09$P_NUMHIN) <- "NUMBER OF HIB-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMHION) <- "NUMBER OF HIB-ONLY SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_NUMHM) <- "NUMBER OF HIB-MERCK SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_NUMH2) <- "NUMBER OF HIB-SANOFI or HIB-GLAXOSMITHKLINE SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_NUMIPV) <- "NUMBER OF IPV-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF09$P_NUMMCN) <- "NUMBER OF MEASLES-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMMMR) <- "NUMBER OF MEASLES-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMMMRX) <- "NUMBER OF MMR-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMMMX) <- "NUMBER OF MMR-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMMP) <- "NUMBER OF MUMPS-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF09$P_NUMMPR) <- "NUMBER OF (MUMPS/RUBELLA)-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMMRV) <- "NUMBER OF MMR/VARICELLA COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMMS) <- "NUMBER OF MEASLES-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMMSM) <- "NUMBER OF MEASLES/MUMPS COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMMSR) <- "NUMBER OF MEASLES/RUBELLA COMBO SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF09$P_NUMOLN) <- "NUMBER OF POLIO SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMOPV) <- "NUMBER OF OPV-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMPCC) <- "NUMBER OF PCV CONJUGATE SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMPCN) <- "NUMBER OF PCV SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMPCP) <- "NUMBER OF PCV POLYSACCHARIDE SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF09$P_NUMPCV) <- "NUMBER OF PNEUMOCOCCAL-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMPOL) <- "NUMBER OF POLIO-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMRB) <- "NUMBER OF RUBELLA-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMRG) <- "NUMBER OF ROTARIX-GSK SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_NUMRM) <- "NUMBER OF ROTATEQ-MERCK SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF09$P_NUMRO) <- "NUMBER OF ROTAVIRUS SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_NUMROT) <- "NUMBER OF ROTAVIRUS-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMTPN) <- "NUMBER OF DT-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMVRC) <- "NUMBER OF VARICELLA-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_NUMVRN) <- "NUMBER OF VARICELLA-CONTAINING SHOTS OF UNKNOWN TYPE BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF09$P_NUMVRX) <- "NUMBER OF VARICELLA-ONLY SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF09$P_U12VRC) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ VARICELLA-CONTAINING SHOT AT 12+ MONTHS OF AGE, BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTD331) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3:3:1 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTD431) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDFL1) <- "UTD FLAG FOR PROVIDER SEASONAL INFLUENZA VARIABLE 1 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF09$P_UTDFL2) <- "UTD FLAG FOR PROVIDER SEASONAL INFLUENZA VARIABLE 2 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDFL3) <- "UTD FLAG FOR PROVIDER SEASONAL INFLUENZA VARIABLE 3 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDHEP) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HEPATITIS B-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDHIB) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HIB-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDHIB_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HIB DOSES BY 36 MONTHS OF AGE, BASED ON THE ROUTINE (NON-SHORTAGE) HIB RECOMMENDATIONS AND A STRICT TREATMENT OF HIB SHOTS OF UNKNOWN TYPE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSE
HOLD INTERVIEW DATE."

label(NISPUF09$P_UTDHIB_SHORT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HIB DOSES BY 36 MONTHS OF AGE, BASED ON THE HIB SHORTAGE RECOMMENDATIONS AND A STRICT TREATMENT OF HIB SHOTS OF UNKNOWN TYPE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIE
W DATE."
label(NISPUF09$P_UTDMCV) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ MEASLES-CONTAINING SHOT BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDMMX) <- "UTD FLAG FOR PROVIDER 1+ MMR COMBO SHOT BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDPC3) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ PNEUMOCOCCAL-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDPCV) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4+ PNEUMOCOCCAL-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF09$P_UTDPOL) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ POLIO-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDROT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ ROTAVIRUS DOSES BY 36 MONTHS OF AGE, BASED ON A STRICT TREATMENT OF ROTAVIRUS VACCINATIONS OF UNKNOWN TYPE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDTP3) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ DT-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTDTP4) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4+ DT-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$PU431331) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3:1 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS) BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."

label(NISPUF09$P_UTD431H31_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1 BY 36 MONTHS OF AGE (INCLUDES 1+ VARICELLA-CONTAINING AT AGE 12+ MTHS) USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INT
ERVIEW DATE."
label(NISPUF09$PU4313313) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3:1:3 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS) BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTD431H313_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1:3 BY 36 MONTHS OF AGE (INCLUDES 1+ VARICELLA-CONTAINING AT AGE 12+ MTHS) USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD 
INTERVIEW DATE."
label(NISPUF09$PU4313314) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3:1:4 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS) BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTD431H314_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1:4 BY 36 MONTHS OF AGE (INCLUDES 1+ VARICELLA-CONTAINING AT AGE 12+ MTHS) USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD 
INTERVIEW DATE."

label(NISPUF09$PUT43133) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTD431H3_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3 BY 36 MONTHS OF AGE, USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$PUTD4313) <- "UTD FLAG FOR PROVIDER 4:3:1:3 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$P_UTD431H_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3 BY 36 MONTHS OF AGE, USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
label(NISPUF09$DDTP1) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #1"

label(NISPUF09$DDTP2) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #2"
label(NISPUF09$DDTP3) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #3"
label(NISPUF09$DDTP4) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #4"
label(NISPUF09$DDTP5) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #5"
label(NISPUF09$DDTP6) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #6"

label(NISPUF09$DDTP7) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #7"
label(NISPUF09$DDTP8) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #8"
label(NISPUF09$DDTP9) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #9"
label(NISPUF09$DFLU1) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #1"
label(NISPUF09$DFLU2) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #2"

label(NISPUF09$DFLU3) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #3"
label(NISPUF09$DFLU4) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #4"
label(NISPUF09$DFLU5) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #5"
label(NISPUF09$DFLU6) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #6"
label(NISPUF09$DFLU7) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #7"

label(NISPUF09$DFLU8) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #8"
label(NISPUF09$DFLU9) <- "AGE IN DAYS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #9"
label(NISPUF09$DHEPA1) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #1"
label(NISPUF09$DHEPA2) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #2"
label(NISPUF09$DHEPA3) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #3"

label(NISPUF09$DHEPA4) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #4"
label(NISPUF09$DHEPA5) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #5"
label(NISPUF09$DHEPA6) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #6"
label(NISPUF09$DHEPA7) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #7"
label(NISPUF09$DHEPA8) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #8"

label(NISPUF09$DHEPA9) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #9"
label(NISPUF09$DHEPB1) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #1"
label(NISPUF09$DHEPB2) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #2"
label(NISPUF09$DHEPB3) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #3"
label(NISPUF09$DHEPB4) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #4"

label(NISPUF09$DHEPB5) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #5"
label(NISPUF09$DHEPB6) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #6"
label(NISPUF09$DHEPB7) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #7"
label(NISPUF09$DHEPB8) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #8"
label(NISPUF09$DHEPB9) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #9"

label(NISPUF09$DHIB1) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #1"
label(NISPUF09$DHIB2) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #2"
label(NISPUF09$DHIB3) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #3"
label(NISPUF09$DHIB4) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #4"
label(NISPUF09$DHIB5) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #5"

label(NISPUF09$DHIB6) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #6"
label(NISPUF09$DHIB7) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #7"
label(NISPUF09$DHIB8) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #8"
label(NISPUF09$DHIB9) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #9"
label(NISPUF09$DMMR1) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #1"

label(NISPUF09$DMMR2) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #2"
label(NISPUF09$DMMR3) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #3"
label(NISPUF09$DMMR4) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #4"
label(NISPUF09$DMMR5) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #5"
label(NISPUF09$DMMR6) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #6"

label(NISPUF09$DMMR7) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #7"
label(NISPUF09$DMMR8) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #8"
label(NISPUF09$DMMR9) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #9"
label(NISPUF09$DMP1) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #1"
label(NISPUF09$DMP2) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #2"

label(NISPUF09$DMP3) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #3"
label(NISPUF09$DMP4) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #4"
label(NISPUF09$DMP5) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #5"
label(NISPUF09$DMP6) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #6"
label(NISPUF09$DMP7) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #7"

label(NISPUF09$DMP8) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #8"
label(NISPUF09$DMP9) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #9"
label(NISPUF09$DMPRB1) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #1"
label(NISPUF09$DMPRB2) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #2"
label(NISPUF09$DMPRB3) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #3"

label(NISPUF09$DMPRB4) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #4"
label(NISPUF09$DMPRB5) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #5"
label(NISPUF09$DMPRB6) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #6"
label(NISPUF09$DMPRB7) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #7"
label(NISPUF09$DMPRB8) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #8"

label(NISPUF09$DMPRB9) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #9"
label(NISPUF09$DPCV1) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #1"
label(NISPUF09$DPCV2) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #2"
label(NISPUF09$DPCV3) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #3"
label(NISPUF09$DPCV4) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #4"

label(NISPUF09$DPCV5) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #5"
label(NISPUF09$DPCV6) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #6"
label(NISPUF09$DPCV7) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #7"
label(NISPUF09$DPCV8) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #8"
label(NISPUF09$DPCV9) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #9"

label(NISPUF09$DPOLIO1) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #1"
label(NISPUF09$DPOLIO2) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #2"
label(NISPUF09$DPOLIO3) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #3"
label(NISPUF09$DPOLIO4) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #4"
label(NISPUF09$DPOLIO5) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #5"

label(NISPUF09$DPOLIO6) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #6"
label(NISPUF09$DPOLIO7) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #7"
label(NISPUF09$DPOLIO8) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #8"
label(NISPUF09$DPOLIO9) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #9"
label(NISPUF09$DRB1) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #1"

label(NISPUF09$DRB2) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #2"
label(NISPUF09$DRB3) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #3"
label(NISPUF09$DRB4) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #4"
label(NISPUF09$DRB5) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #5"
label(NISPUF09$DRB6) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #6"

label(NISPUF09$DRB7) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #7"
label(NISPUF09$DRB8) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #8"
label(NISPUF09$DRB9) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #9"
label(NISPUF09$DROT1) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #1"
label(NISPUF09$DROT2) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #2"

label(NISPUF09$DROT3) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #3"
label(NISPUF09$DROT4) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #4"
label(NISPUF09$DROT5) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #5"
label(NISPUF09$DROT6) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #6"
label(NISPUF09$DROT7) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #7"

label(NISPUF09$DROT8) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #8"
label(NISPUF09$DROT9) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #9"
label(NISPUF09$DTP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #1"
label(NISPUF09$DTP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #2"
label(NISPUF09$DTP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #3"

label(NISPUF09$DTP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #4"
label(NISPUF09$DTP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #5"
label(NISPUF09$DTP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #6"
label(NISPUF09$DTP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #7"
label(NISPUF09$DTP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #8"

label(NISPUF09$DTP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #9"
label(NISPUF09$DVRC1) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #1"
label(NISPUF09$DVRC2) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #2"
label(NISPUF09$DVRC3) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #3"
label(NISPUF09$DVRC4) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #4"

label(NISPUF09$DVRC5) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #5"
label(NISPUF09$DVRC6) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #6"
label(NISPUF09$DVRC7) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #7"
label(NISPUF09$DVRC8) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #8"
label(NISPUF09$DVRC9) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #9"

label(NISPUF09$FLU1_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #1"
label(NISPUF09$FLU2_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #2"
label(NISPUF09$FLU3_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #3"
label(NISPUF09$FLU4_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #4"
label(NISPUF09$FLU5_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #5"

label(NISPUF09$FLU6_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #6"
label(NISPUF09$FLU7_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #7"
label(NISPUF09$FLU8_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #8"
label(NISPUF09$FLU9_AGE) <- "AGE IN MONTHS OF PROV-REPTD SEASONAL FLU-CONTAINING VACCINATION #9"
label(NISPUF09$HEA1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #1"

label(NISPUF09$HEA2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #2"
label(NISPUF09$HEA3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #3"
label(NISPUF09$HEA4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #4"
label(NISPUF09$HEA5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #5"
label(NISPUF09$HEA6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #6"

label(NISPUF09$HEA7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #7"
label(NISPUF09$HEA8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #8"
label(NISPUF09$HEA9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #9"
label(NISPUF09$HEP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #1"
label(NISPUF09$HEP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #2"

label(NISPUF09$HEP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #3"
label(NISPUF09$HEP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #4"
label(NISPUF09$HEP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #5"
label(NISPUF09$HEP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #6"
label(NISPUF09$HEP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #7"

label(NISPUF09$HEP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #8"
label(NISPUF09$HEP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #9"
label(NISPUF09$HIB1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #1"
label(NISPUF09$HIB2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #2"
label(NISPUF09$HIB3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #3"

label(NISPUF09$HIB4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #4"
label(NISPUF09$HIB5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #5"
label(NISPUF09$HIB6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #6"
label(NISPUF09$HIB7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #7"
label(NISPUF09$HIB8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #8"

label(NISPUF09$HIB9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #9"
label(NISPUF09$MMR1_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #1"
label(NISPUF09$MMR2_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #2"
label(NISPUF09$MMR3_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #3"
label(NISPUF09$MMR4_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #4"

label(NISPUF09$MMR5_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #5"
label(NISPUF09$MMR6_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #6"
label(NISPUF09$MMR7_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #7"
label(NISPUF09$MMR8_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #8"
label(NISPUF09$MMR9_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #9"

label(NISPUF09$MP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #1"
label(NISPUF09$MP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #2"
label(NISPUF09$MP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #3"
label(NISPUF09$MP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #4"
label(NISPUF09$MP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #5"

label(NISPUF09$MP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #6"
label(NISPUF09$MP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #7"
label(NISPUF09$MP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #8"
label(NISPUF09$MP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #9"
label(NISPUF09$MPR1_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #1"

label(NISPUF09$MPR2_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #2"
label(NISPUF09$MPR3_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #3"
label(NISPUF09$MPR4_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #4"
label(NISPUF09$MPR5_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #5"
label(NISPUF09$MPR6_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #6"

label(NISPUF09$MPR7_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #7"
label(NISPUF09$MPR8_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #8"
label(NISPUF09$MPR9_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #9"
label(NISPUF09$PCV1_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #1"
label(NISPUF09$PCV2_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #2"

label(NISPUF09$PCV3_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #3"
label(NISPUF09$PCV4_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #4"
label(NISPUF09$PCV5_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #5"
label(NISPUF09$PCV6_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #6"
label(NISPUF09$PCV7_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #7"

label(NISPUF09$PCV8_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #8"
label(NISPUF09$PCV9_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #9"
label(NISPUF09$POL1_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #1"
label(NISPUF09$POL2_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #2"
label(NISPUF09$POL3_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #3"

label(NISPUF09$POL4_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #4"
label(NISPUF09$POL5_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #5"
label(NISPUF09$POL6_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #6"
label(NISPUF09$POL7_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #7"
label(NISPUF09$POL8_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #8"

label(NISPUF09$POL9_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #9"
label(NISPUF09$RB1_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #1"
label(NISPUF09$RB2_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #2"
label(NISPUF09$RB3_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #3"
label(NISPUF09$RB4_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #4"

label(NISPUF09$RB5_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #5"
label(NISPUF09$RB6_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #6"
label(NISPUF09$RB7_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #7"
label(NISPUF09$RB8_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #8"
label(NISPUF09$RB9_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #9"

label(NISPUF09$ROT1_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #1"
label(NISPUF09$ROT2_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #2"
label(NISPUF09$ROT3_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #3"
label(NISPUF09$ROT4_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #4"
label(NISPUF09$ROT5_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #5"

label(NISPUF09$ROT6_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #6"
label(NISPUF09$ROT7_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #7"
label(NISPUF09$ROT8_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #8"
label(NISPUF09$ROT9_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #9"
label(NISPUF09$VRC1_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #1"

label(NISPUF09$VRC2_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #2"
label(NISPUF09$VRC3_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #3"
label(NISPUF09$VRC4_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #4"
label(NISPUF09$VRC5_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #5"
label(NISPUF09$VRC6_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #6"

label(NISPUF09$VRC7_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #7"
label(NISPUF09$VRC8_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #8"
label(NISPUF09$VRC9_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #9"
label(NISPUF09$XDTPTY1) <- "DT-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF09$XDTPTY2) <- "DT-CONTAINING VACCINATION #2 TYPE CODE"

label(NISPUF09$XDTPTY3) <- "DT-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF09$XDTPTY4) <- "DT-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF09$XDTPTY5) <- "DT-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF09$XDTPTY6) <- "DT-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF09$XDTPTY7) <- "DT-CONTAINING VACCINATION #7 TYPE CODE"

label(NISPUF09$XDTPTY8) <- "DT-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF09$XDTPTY9) <- "DT-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF09$XFLUTY1) <- "SEASONAL FLU-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF09$XFLUTY2) <- "SEASONAL FLU-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF09$XFLUTY3) <- "SEASONAL FLU-CONTAINING VACCINATION #3 TYPE CODE"

label(NISPUF09$XFLUTY4) <- "SEASONAL FLU-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF09$XFLUTY5) <- "SEASONAL FLU-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF09$XFLUTY6) <- "SEASONAL FLU-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF09$XFLUTY7) <- "SEASONAL FLU-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF09$XFLUTY8) <- "SEASONAL FLU-CONTAINING VACCINATION #8 TYPE CODE"

label(NISPUF09$XFLUTY9) <- "SEASONAL FLU-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF09$XHEPTY1) <- "HEPATITIS B-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF09$XHEPTY2) <- "HEPATITIS B-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF09$XHEPTY3) <- "HEPATITIS B-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF09$XHEPTY4) <- "HEPATITIS B-CONTAINING VACCINATION #4 TYPE CODE"

label(NISPUF09$XHEPTY5) <- "HEPATITIS B-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF09$XHEPTY6) <- "HEPATITIS B-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF09$XHEPTY7) <- "HEPATITIS B-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF09$XHEPTY8) <- "HEPATITIS B-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF09$XHEPTY9) <- "HEPATITIS B-CONTAINING VACCINATION #9 TYPE CODE"

label(NISPUF09$XHIBTY1) <- "HIB-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF09$XHIBTY2) <- "HIB-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF09$XHIBTY3) <- "HIB-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF09$XHIBTY4) <- "HIB-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF09$XHIBTY5) <- "HIB-CONTAINING VACCINATION #5 TYPE CODE"

label(NISPUF09$XHIBTY6) <- "HIB-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF09$XHIBTY7) <- "HIB-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF09$XHIBTY8) <- "HIB-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF09$XHIBTY9) <- "HIB-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF09$XMMRTY1) <- "MEASLES-CONTAINING VACCINATION #1 TYPE CODE"

label(NISPUF09$XMMRTY2) <- "MEASLES-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF09$XMMRTY3) <- "MEASLES-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF09$XMMRTY4) <- "MEASLES-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF09$XMMRTY5) <- "MEASLES-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF09$XMMRTY6) <- "MEASLES-CONTAINING VACCINATION #6 TYPE CODE"

label(NISPUF09$XMMRTY7) <- "MEASLES-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF09$XMMRTY8) <- "MEASLES-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF09$XMMRTY9) <- "MEASLES-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF09$XPCVTY1) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF09$XPCVTY2) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #2 TYPE CODE"

label(NISPUF09$XPCVTY3) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF09$XPCVTY4) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF09$XPCVTY5) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF09$XPCVTY6) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF09$XPCVTY7) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #7 TYPE CODE"

label(NISPUF09$XPCVTY8) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF09$XPCVTY9) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF09$XPOLTY1) <- "POLIO-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF09$XPOLTY2) <- "POLIO-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF09$XPOLTY3) <- "POLIO-CONTAINING VACCINATION #3 TYPE CODE"

label(NISPUF09$XPOLTY4) <- "POLIO-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF09$XPOLTY5) <- "POLIO-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF09$XPOLTY6) <- "POLIO-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF09$XPOLTY7) <- "POLIO-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF09$XPOLTY8) <- "POLIO-CONTAINING VACCINATION #8 TYPE CODE"

label(NISPUF09$XPOLTY9) <- "POLIO-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF09$XROTTY1) <- "ROTAVIRUS-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF09$XROTTY2) <- "ROTAVIRUS-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF09$XROTTY3) <- "ROTAVIRUS-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF09$XROTTY4) <- "ROTAVIRUS-CONTAINING VACCINATION #4 TYPE CODE"

label(NISPUF09$XROTTY5) <- "ROTAVIRUS-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF09$XROTTY6) <- "ROTAVIRUS-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF09$XROTTY7) <- "ROTAVIRUS-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF09$XROTTY8) <- "ROTAVIRUS-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF09$XROTTY9) <- "ROTAVIRUS-CONTAINING VACCINATION #9 TYPE CODE"

label(NISPUF09$XVRCTY1) <- "VARICELLA-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF09$XVRCTY2) <- "VARICELLA-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF09$XVRCTY3) <- "VARICELLA-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF09$XVRCTY4) <- "VARICELLA-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF09$XVRCTY5) <- "VARICELLA-CONTAINING VACCINATION #5 TYPE CODE"

label(NISPUF09$XVRCTY6) <- "VARICELLA-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF09$XVRCTY7) <- "VARICELLA-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF09$XVRCTY8) <- "VARICELLA-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF09$XVRCTY9) <- "VARICELLA-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF09$INS_1) <- "IS CHILD COVERED BY HEALTH INSURANCE PROVIDED THROUGH EMPLOYER OR UNION?"

label(NISPUF09$INS_2) <- "IS CHILD COVERED BY ANY MEDICAID PLAN?"
label(NISPUF09$INS_3) <- "IS CHILD COVERED BY S-CHIP?"
label(NISPUF09$INS_3A) <- "IS CHILD COVERED BY ANY MEDICAID PLAN OR S-CHIP?"
label(NISPUF09$INS_4_5) <- "IS CHILD COVERED BY INDIAN HEALTH SERVICE, MILITARY HEALTH CARE, TRICARE, CHAMPUS, OR CHAMP-VA?"
label(NISPUF09$INS_6) <- "IS CHILD COVERED BY ANY OTHER HEALTH INSURANCE OR HEALTH CARE PLAN?"

label(NISPUF09$INS_11) <- "ANY TIME WHEN CHILD WAS NOT COVERED BY ANY HEALTH INSURANCE?"
label(NISPUF09$VFC_I) <- "DERIVED: IS CHILD VFC ELIGIBLE?"

############################################################################
# Step 5:   CREATE A PERMANENT R DATASET                                   #
############################################################################

save(NISPUF09, file=paste(PUF, "/NISPUF09.RData", sep=""))

############################################################################
# Step 6:   ASSIGN FORMATS                                                 #
#	  FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES IN R     	   #
############################################################################

NISPUF09$AGEGRP <- factor(NISPUF09$AGEGRP, levels=AGEGRPlevels, labels=AGEGRPlabels)
NISPUF09$LANGUAGE <- factor(NISPUF09$LANGUAGE, levels=LANGUAGElevels, labels=LANGUAGElabels)
NISPUF09$HAD_CPOX <- factor(NISPUF09$HAD_CPOX, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF09$CBF_01 <- factor(NISPUF09$CBF_01, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF09$CWIC_02 <- factor(NISPUF09$CWIC_02, levels=YNDKRFlevels, labels=YNDKRFlabels)

NISPUF09$INTRP <- factor(NISPUF09$INTRP, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF09$INS_1 <- factor(NISPUF09$INS_1, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF09$INS_2 <- factor(NISPUF09$INS_2, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF09$INS_3 <- factor(NISPUF09$INS_3, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF09$INS_3A <- factor(NISPUF09$INS_3A, levels=YNDKRFlevels, labels=YNDKRFlabels)

NISPUF09$INS_4_5 <- factor(NISPUF09$INS_4_5, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF09$INS_6 <- factor(NISPUF09$INS_6, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF09$INS_11 <- factor(NISPUF09$INS_11, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF09$P_NUHEPX <- factor(NISPUF09$P_NUHEPX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUHIBX <- factor(NISPUF09$P_NUHIBX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$P_NUHPHB <- factor(NISPUF09$P_NUHPHB, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMDAH <- factor(NISPUF09$P_NUMDAH, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMDHI <- factor(NISPUF09$P_NUMDHI, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMDIH <- factor(NISPUF09$P_NUMDIH, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMDTA <- factor(NISPUF09$P_NUMDTA, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$P_NUMDTP <- factor(NISPUF09$P_NUMDTP, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMFLU <- factor(NISPUF09$P_NUMFLU, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMFLUL <- factor(NISPUF09$P_NUMFLUL, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMFLUM <- factor(NISPUF09$P_NUMFLUM, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMFLUN <- factor(NISPUF09$P_NUMFLUN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$P_NUMHEA <- factor(NISPUF09$P_NUMHEA, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMHEN <- factor(NISPUF09$P_NUMHEN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMHEP <- factor(NISPUF09$P_NUMHEP, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMHIB <- factor(NISPUF09$P_NUMHIB, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMHIN <- factor(NISPUF09$P_NUMHIN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$P_NUMHION <- factor(NISPUF09$P_NUMHION, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMHM <- factor(NISPUF09$P_NUMHM, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMH2 <- factor(NISPUF09$P_NUMH2, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMIPV <- factor(NISPUF09$P_NUMIPV, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMMCN <- factor(NISPUF09$P_NUMMCN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$P_NUMMMR <- factor(NISPUF09$P_NUMMMR, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMMMRX <- factor(NISPUF09$P_NUMMMRX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMMMX <- factor(NISPUF09$P_NUMMMX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMMP <- factor(NISPUF09$P_NUMMP, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMMPR <- factor(NISPUF09$P_NUMMPR, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$P_NUMMRV <- factor(NISPUF09$P_NUMMRV, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMMS <- factor(NISPUF09$P_NUMMS, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMMSM <- factor(NISPUF09$P_NUMMSM, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMMSR <- factor(NISPUF09$P_NUMMSR, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMOLN <- factor(NISPUF09$P_NUMOLN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$P_NUMOPV <- factor(NISPUF09$P_NUMOPV, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMPCC <- factor(NISPUF09$P_NUMPCC, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMPCN <- factor(NISPUF09$P_NUMPCN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMPCP <- factor(NISPUF09$P_NUMPCP, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMPCV <- factor(NISPUF09$P_NUMPCV, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$P_NUMPOL <- factor(NISPUF09$P_NUMPOL, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMRB <- factor(NISPUF09$P_NUMRB, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMRG <- factor(NISPUF09$P_NUMRG, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMRM <- factor(NISPUF09$P_NUMRM, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMRO <- factor(NISPUF09$P_NUMRO, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$P_NUMROT <- factor(NISPUF09$P_NUMROT, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMTPN <- factor(NISPUF09$P_NUMTPN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMVRC <- factor(NISPUF09$P_NUMVRC, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMVRN <- factor(NISPUF09$P_NUMVRN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF09$P_NUMVRX <- factor(NISPUF09$P_NUMVRX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF09$SC_431 <- factor(NISPUF09$SC_431, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF09$SC_4313 <- factor(NISPUF09$SC_4313, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF09$SC_43133 <- factor(NISPUF09$SC_43133, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF09$SC_DTP <- factor(NISPUF09$SC_DTP, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF09$SC_HEPB <- factor(NISPUF09$SC_HEPB, levels=SCUTDlevels, labels=SCUTDlabels)

NISPUF09$SC_HIB <- factor(NISPUF09$SC_HIB, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF09$SC_MCV <- factor(NISPUF09$SC_MCV, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF09$SC_POL <- factor(NISPUF09$SC_POL, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF09$SC_VRC <- factor(NISPUF09$SC_VRC, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF09$HH_DTP <- factor(NISPUF09$HH_DTP, levels=HHNUMlevels, labels=HHNUMlabels)

NISPUF09$HH_HEPB <- factor(NISPUF09$HH_HEPB, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF09$HH_HIB <- factor(NISPUF09$HH_HIB, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF09$HH_MCV <- factor(NISPUF09$HH_MCV, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF09$HH_POL <- factor(NISPUF09$HH_POL, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF09$HH_VRC <- factor(NISPUF09$HH_VRC, levels=HHNUMlevels, labels=HHNUMlabels)

NISPUF09$D7 <- factor(NISPUF09$D7, levels=YNlevels, labels=YNlabels)
NISPUF09$SHOTCARD <- factor(NISPUF09$SHOTCARD, levels=SHOTCARDlevels, labels=SHOTCARDlabels)
NISPUF09$BFENDFL06 <- factor(NISPUF09$BFENDFL06, levels=Ylevels, labels=Ylabels)
NISPUF09$BFFORMFL06 <- factor(NISPUF09$BFFORMFL06, levels=Ylevels, labels=Ylabels)
NISPUF09$CHILDNM <- factor(NISPUF09$CHILDNM, levels=CHILDNMlevels, labels=CHILDNMlabels)

NISPUF09$CWIC_01 <- factor(NISPUF09$CWIC_01, levels=CWIClevels, labels=CWIClabels)
NISPUF09$EDUC1 <- factor(NISPUF09$EDUC1, levels=EDUC1_levels, labels=EDUC1_labels)
NISPUF09$I_HISP_K <- factor(NISPUF09$I_HISP_K, levels=HISPlevels, labels=HISPlabels)
NISPUF09$M_AGEGRP <- factor(NISPUF09$M_AGEGRP, levels=MAGEGRPlevels, labels=MAGEGRPlabels)
NISPUF09$MOBIL_I <- factor(NISPUF09$MOBIL_I, levels=MOBILlevels, labels=MOBILlabels)

NISPUF09$SEX <- factor(NISPUF09$SEX, levels=SEXlevels, labels=SEXlabels)
NISPUF09$INCPOV1 <- factor(NISPUF09$INCPOV1, levels=INCPOVlevels, labels=INCPOVlabels)
NISPUF09$DISPCODE <- factor(NISPUF09$DISPCODE, levels=DISPlevels, labels=DISPlabels)
NISPUF09$PDAT <- factor(NISPUF09$PDAT, levels=HASPDA2Flevels, labels=HASPDA2Flabels)
NISPUF09$PROV_FAC <- factor(NISPUF09$PROV_FAC, levels=PROVIDlevels, labels=PROVIDlabels)

NISPUF09$REGISTRY <- factor(NISPUF09$REGISTRY, levels=REGISTRYlevels, labels=REGISTRYlabels)
NISPUF09$VFC_ORDER <- factor(NISPUF09$VFC_ORDER, levels=REGISTRYlevels, labels=REGISTRYlabels)
NISPUF09$XDTPTY1 <- factor(NISPUF09$XDTPTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XDTPTY2 <- factor(NISPUF09$XDTPTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XDTPTY3 <- factor(NISPUF09$XDTPTY3, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XDTPTY4 <- factor(NISPUF09$XDTPTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XDTPTY5 <- factor(NISPUF09$XDTPTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XDTPTY6 <- factor(NISPUF09$XDTPTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XDTPTY7 <- factor(NISPUF09$XDTPTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XDTPTY8 <- factor(NISPUF09$XDTPTY8, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XDTPTY9 <- factor(NISPUF09$XDTPTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XFLUTY1 <- factor(NISPUF09$XFLUTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XFLUTY2 <- factor(NISPUF09$XFLUTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XFLUTY3 <- factor(NISPUF09$XFLUTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XFLUTY4 <- factor(NISPUF09$XFLUTY4, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XFLUTY5 <- factor(NISPUF09$XFLUTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XFLUTY6 <- factor(NISPUF09$XFLUTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XFLUTY7 <- factor(NISPUF09$XFLUTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XFLUTY8 <- factor(NISPUF09$XFLUTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XFLUTY9 <- factor(NISPUF09$XFLUTY9, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XHEPTY1 <- factor(NISPUF09$XHEPTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHEPTY2 <- factor(NISPUF09$XHEPTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHEPTY3 <- factor(NISPUF09$XHEPTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHEPTY4 <- factor(NISPUF09$XHEPTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHEPTY5 <- factor(NISPUF09$XHEPTY5, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XHEPTY6 <- factor(NISPUF09$XHEPTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHEPTY7 <- factor(NISPUF09$XHEPTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHEPTY8 <- factor(NISPUF09$XHEPTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHEPTY9 <- factor(NISPUF09$XHEPTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHIBTY1 <- factor(NISPUF09$XHIBTY1, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XHIBTY2 <- factor(NISPUF09$XHIBTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHIBTY3 <- factor(NISPUF09$XHIBTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHIBTY4 <- factor(NISPUF09$XHIBTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHIBTY5 <- factor(NISPUF09$XHIBTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHIBTY6 <- factor(NISPUF09$XHIBTY6, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XHIBTY7 <- factor(NISPUF09$XHIBTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHIBTY8 <- factor(NISPUF09$XHIBTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XHIBTY9 <- factor(NISPUF09$XHIBTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XMMRTY1 <- factor(NISPUF09$XMMRTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XMMRTY2 <- factor(NISPUF09$XMMRTY2, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XMMRTY3 <- factor(NISPUF09$XMMRTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XMMRTY4 <- factor(NISPUF09$XMMRTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XMMRTY5 <- factor(NISPUF09$XMMRTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XMMRTY6 <- factor(NISPUF09$XMMRTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XMMRTY7 <- factor(NISPUF09$XMMRTY7, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XMMRTY8 <- factor(NISPUF09$XMMRTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XMMRTY9 <- factor(NISPUF09$XMMRTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPCVTY1 <- factor(NISPUF09$XPCVTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPCVTY2 <- factor(NISPUF09$XPCVTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPCVTY3 <- factor(NISPUF09$XPCVTY3, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XPCVTY4 <- factor(NISPUF09$XPCVTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPCVTY5 <- factor(NISPUF09$XPCVTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPCVTY6 <- factor(NISPUF09$XPCVTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPCVTY7 <- factor(NISPUF09$XPCVTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPCVTY8 <- factor(NISPUF09$XPCVTY8, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XPCVTY9 <- factor(NISPUF09$XPCVTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPOLTY1 <- factor(NISPUF09$XPOLTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPOLTY2 <- factor(NISPUF09$XPOLTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPOLTY3 <- factor(NISPUF09$XPOLTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPOLTY4 <- factor(NISPUF09$XPOLTY4, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XPOLTY5 <- factor(NISPUF09$XPOLTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPOLTY6 <- factor(NISPUF09$XPOLTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPOLTY7 <- factor(NISPUF09$XPOLTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPOLTY8 <- factor(NISPUF09$XPOLTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XPOLTY9 <- factor(NISPUF09$XPOLTY9, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XROTTY1 <- factor(NISPUF09$XROTTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XROTTY2 <- factor(NISPUF09$XROTTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XROTTY3 <- factor(NISPUF09$XROTTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XROTTY4 <- factor(NISPUF09$XROTTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XROTTY5 <- factor(NISPUF09$XROTTY5, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XROTTY6 <- factor(NISPUF09$XROTTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XROTTY7 <- factor(NISPUF09$XROTTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XROTTY8 <- factor(NISPUF09$XROTTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XROTTY9 <- factor(NISPUF09$XROTTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XVRCTY1 <- factor(NISPUF09$XVRCTY1, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XVRCTY2 <- factor(NISPUF09$XVRCTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XVRCTY3 <- factor(NISPUF09$XVRCTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XVRCTY4 <- factor(NISPUF09$XVRCTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XVRCTY5 <- factor(NISPUF09$XVRCTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XVRCTY6 <- factor(NISPUF09$XVRCTY6, levels=TYPElevels, labels=TYPElabels)

NISPUF09$XVRCTY7 <- factor(NISPUF09$XVRCTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XVRCTY8 <- factor(NISPUF09$XVRCTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF09$XVRCTY9 <- factor(NISPUF09$XVRCTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF09$HEP_BRTH <- factor(NISPUF09$HEP_BRTH, levels=HEPBRTlevels, labels=HEPBRTlabels)
NISPUF09$HEP_FLAG <- factor(NISPUF09$HEP_FLAG, levels=HEPFLGlevels, labels=HEPFLGlabels)

NISPUF09$P_U12VRC <- factor(NISPUF09$P_U12VRC, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTD331 <- factor(NISPUF09$P_UTD331, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTD431 <- factor(NISPUF09$P_UTD431, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDHEP <- factor(NISPUF09$P_UTDHEP, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDHIB <- factor(NISPUF09$P_UTDHIB, levels=UTDlevels, labels=UTDlabels)

NISPUF09$P_UTDHIB_ROUT_S <- factor(NISPUF09$P_UTDHIB_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDHIB_SHORT_S <- factor(NISPUF09$P_UTDHIB_SHORT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDMCV <- factor(NISPUF09$P_UTDMCV, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDMMX <- factor(NISPUF09$P_UTDMMX, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDPC3 <- factor(NISPUF09$P_UTDPC3, levels=UTDlevels, labels=UTDlabels)

NISPUF09$P_UTDPCV <- factor(NISPUF09$P_UTDPCV, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDPOL <- factor(NISPUF09$P_UTDPOL, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDROT_S <- factor(NISPUF09$P_UTDROT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDTP3 <- factor(NISPUF09$P_UTDTP3, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTDTP4 <- factor(NISPUF09$P_UTDTP4, levels=UTDlevels, labels=UTDlabels)

NISPUF09$PU431331 <- factor(NISPUF09$PU431331, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTD431H31_ROUT_S <- factor(NISPUF09$P_UTD431H31_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF09$PU4313313 <- factor(NISPUF09$PU4313313, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTD431H313_ROUT_S <- factor(NISPUF09$P_UTD431H313_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF09$PU4313314 <- factor(NISPUF09$PU4313314, levels=UTDlevels, labels=UTDlabels)

NISPUF09$P_UTD431H314_ROUT_S <- factor(NISPUF09$P_UTD431H314_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF09$PUT43133 <- factor(NISPUF09$PUT43133, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTD431H3_ROUT_S <- factor(NISPUF09$P_UTD431H3_ROUT_S, levels=UTDlevels, labels=UTDlabels)
NISPUF09$PUTD4313 <- factor(NISPUF09$PUTD4313, levels=UTDlevels, labels=UTDlabels)
NISPUF09$P_UTD431H_ROUT_S <- factor(NISPUF09$P_UTD431H_ROUT_S, levels=UTDlevels, labels=UTDlabels)

NISPUF09$CEN_REG <- factor(NISPUF09$CEN_REG, levels=CENREGlevels, labels=CENREGlabels)
NISPUF09$STATE <- factor(NISPUF09$STATE, levels=STATElevels, labels=STATElabels)
NISPUF09$P_UTDFL1 <- factor(NISPUF09$P_UTDFL1, levels=FLUUTDlevels, labels=FLUUTDlabels)
NISPUF09$P_UTDFL2 <- factor(NISPUF09$P_UTDFL2, levels=FLUUTDlevels, labels=FLUUTDlabels)
NISPUF09$P_UTDFL3 <- factor(NISPUF09$P_UTDFL3, levels=FLUUTDlevels, labels=FLUUTDlabels)

NISPUF09$RACE_K <- factor(NISPUF09$RACE_K, levels=RACE_PUFlevels, labels=RACE_PUFlabels)
NISPUF09$AGECPOXR <- factor(NISPUF09$AGECPOXR, levels=AGECPOXRlevels, labels=AGECPOXRlabels)
NISPUF09$C1R <- factor(NISPUF09$C1R, levels=C1Rlevels, labels=C1Rlabels)
NISPUF09$C5R <- factor(NISPUF09$C5R, levels=C5Rlevels, labels=C5Rlabels)
NISPUF09$INOPHONR <- factor(NISPUF09$INOPHONR, levels=INOPHONRlevels, labels=INOPHONRlabels)

NISPUF09$INCQ298A <- factor(NISPUF09$INCQ298A, levels=INCQ298Alevels, labels=INCQ298Alabels)
NISPUF09$RACEETHK <- factor(NISPUF09$RACEETHK, levels=RACEETHKlevels, labels=RACEETHKlabels)
NISPUF09$D6R <- factor(NISPUF09$D6R, levels=D6Rlevels, labels=D6Rlabels)
NISPUF09$N_PRVR <- factor(NISPUF09$N_PRVR, levels=D6Rlevels, labels=D6Rlabels)
NISPUF09$FRSTBRN <- factor(NISPUF09$FRSTBRN, levels=FRSTBRNlevels, labels=FRSTBRNlabels)

NISPUF09$SEQNUMC <- factor(NISPUF09$SEQNUMC, levels=CHARIDlevels, labels=CHARIDlabels)
NISPUF09$SEQNUMHH <- factor(NISPUF09$SEQNUMHH, levels=CHARIDlevels, labels=CHARIDlabels)
NISPUF09$BF_FORMR08 <- factor(NISPUF09$BF_FORMR08, levels=BFFORM08Flevels, labels=BFFORM08Flabels)
NISPUF09$RENT_OWN <- factor(NISPUF09$RENT_OWN, levels=RENTOWNlevels, labels=RENTOWNlabels)
NISPUF09$NUM_PHONE <- factor(NISPUF09$NUM_PHONE, levels=NUM_PHONlevels, labels=NUM_PHONlabels)

NISPUF09$NUM_CELLS_HH <- factor(NISPUF09$NUM_CELLS_HH, levels=NUM_PHONlevels, labels=NUM_PHONlabels)
NISPUF09$NUM_CELLS_PARENTS <- factor(NISPUF09$NUM_CELLS_PARENTS, levels=NUM_PHONlevels, labels=NUM_PHONlabels)
NISPUF09$VFC_I <- factor(NISPUF09$VFC_I, levels=INS_STATlevels, labels=INS_STATlabels)
NISPUF09$ESTIAP09 <- factor(NISPUF09$ESTIAP09, levels=ESTIAP09Flevels, labels=ESTIAP09Flabels)
NISPUF09$MARITAL2 <- factor(NISPUF09$MARITAL2, levels=MAR_PUF2_levels, labels=MAR_PUF2_labels)


##########################################################################
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE        #
##########################################################################

#---CONTENTS---#
NISPUF09.CONTENTS <- contents(NISPUF09)$contents

print(NISPUF09.CONTENTS)

#IN CASE THAT THE R CONSOLE CANNOT DISPLAY WHOLE CONTENTS,
#YOU CAN SAVE CONTENTS INTO A FILE
#write.table(NISPUF09.CONTENTS, file=paste(PUF,"/file-name",sep=""))

#---UNWEIGHTED FREQUENCY---#
unwt_freq <- function(UNWT.VAR){#FUNCTION TO PRINT UNWEIGHTED FREQUENCIES

unwt.tab <- wtd.table(UNWT.VAR, weights= NULL, type='table')
unwtd.freq <- data.frame(cbind(
unwt.tab, round(unwt.tab/sum(unwt.tab)*100,2),
cumsum(unwt.tab), cumsum(round(unwt.tab/sum(unwt.tab)*100,2))))
names(unwtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
unwtd.title <- paste('2009 NIS', 'UNWEIGHTED FREQUENCIES', label(UNWT.VAR), sep="\n")
label(unwtd.freq) <- unwtd.title

print(unwtd.freq)
}

UNWT.VAR <- NISPUF09$AGEGRP	#INPUT A VARIABLE OF INTEREST
unwt_freq(UNWT.VAR)

#---WEIGHTED FREQUENCY---#
WT <- NISPUF09$RDDWT		#INPUT A WEIGHT VARIABLE
WT.VAR <- NISPUF09$AGEGRP 	#INPUT A VARIABLE OF INTEREST

wt.tab <- wtd.table(WT.VAR, weights= WT, type='table')
wtd.freq <- data.frame(cbind(
wt.tab, round(wt.tab/sum(wt.tab)*100,2),
cumsum(wt.tab), cumsum(round(wt.tab/sum(wt.tab)*100,2))))
names(wtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
wtd.title <- paste('2009 NIS PUBLIC USE FILE', 'WEIGHTED FREQUENCIES (EXCLUDING U.S. VIRGIN ISLANDS)', label(WT.VAR), sep="\n")
label(wtd.freq) <- wtd.title

print(wtd.freq)
