############################################################################
# PROGRAM:  NISPUF08.R                                                     #
#                                                                          #
# PURPOSE:  THIS R   PROGRAM CREATES A PERMANENT R DATASET                 #
#                FROM THE 2008 NIS PUBLIC-USE ASCII FILE                   #
#                                                                          #
# NOTES:    THIS PROGRAM IS DIVIDED INTO SEVEN STEPS AS FOLLOWS:           #
#                                                                          #
# STEP 1:   LOAD AN R PACKAGE AND ASSIGN FILE NAMES                        #
#                                                                          #
#		 ONE R PACKAGE FOR TWO FUNCTIONS (CONTENTS, WTD.TABLE)         #
#		 WILL BE LOADED	                                             #
#		 THE USER CAN ENTER THE PATH TO THE ASCII DATA FILE AND        #
#		 THE PATH WHERE THE R DATASET WILL BE CREATED                  #
#                                                                          #
# STEP 2:   CREATE FORMATS                                                 #
#                                                                          #
# STEP 3:   READ THE FLAT DATA FILE                                        #
#                                                                          #
# STEP 4:   ASSIGN VARIABLE LABELS                                         #
#                                                                          #
# STEP 5:   CREATE A PERMANENT R DATASET                                   #
#                                                                          #
# STEP 6:   ASSIGN FORMATS                                                 #
#                                                                          #
#	   FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES IN R	   #
#                                                                          #
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE          #
#                                                                          #
############################################################################

############################################################################
# Step 1:   LOAD R PACKAGES AND ASSIGN FILE NAMES                          #
############################################################################
#Users may need to install the Hmisc library before invoking it.
library(Hmisc) #TO USE contents()

#---USE SLASH(/) TO SEPERATE A FILE PATH---#
PUF <- "path-to-data"

flatfile <- "path-to-file/NISPUF08.DAT"



############################################################################
# Step 2:   CREATE FORMATS                                                 #
############################################################################

AGEGRPlevels=c(1, 2, 3)
AGEGRPlabels=c("19 - 23 MONTHS", "24 - 29 MONTHS", "30 - 35 MONTHS")

LANGUAGElevels=c(1, 2, 3)
LANGUAGElabels=c("ENGLISH", "SPANISH", "OTHER")

YNDKRFlevels=c(1, 2, 77, 99)
YNDKRFlabels=c("YES", "NO", "DON'T KNOW", "REFUSED")

SHOTCOUNlevels=c(77, 88, 99)
SHOTCOUNlabels=c("DON'T KNOW", "1+ BUT UNKNOWN NUMBER", "REFUSED")

YNDKUKRFlevels=c(1, 2, 77, 88, 99)
YNDKUKRFlabels=c("YES", "NO", "DON'T KNOW", "UNKNOWN", "REFUSED")

SCUTDlevels=c(1, 2, 77, 88, 99)
SCUTDlabels=c("UTD / SC", "NOT UTD / SC", "DON'T KNOW", "UNKNOWN", "REFUSED")

HHNUMlevels=c(0, 1, 50, 77, 99)
HHNUMlabels=c("NONE", "AT LEAST ONE", "ALL", "DON'T KNOW", "REFUSED")

CDTPlevels=c(1, 2, 3, 4, 5)
CDTPlabels=c("UTD DTP / SC", "NOT UTD DTP / SC", "UTD DTP / NSC", "NOT UTD DTP / NSC", "MISSING / SC / NSC")

CHEPlevels=c(1, 2, 3, 4, 5)
CHEPlabels=c("UTD HEPB / SC", "NOT UTD HEPB / SC", "UTD HEPB / NSC", "NOT UTD HEPB / NSC", "MISSING / SC / NSC")

CHIBlevels=c(1, 2, 3, 4, 5)
CHIBlabels=c("UTD HIB / SC", "NOT UTD HIB / SC", "UTD HIB / NSC", "NOT UTD HIB / NSC", "MISSING / SC / NSC")

CMMRlevels=c(1, 2, 3, 4, 5)
CMMRlabels=c("UTD MCV / SC", "NOT UTD MCV / SC", "UTD MCV / NSC", "NOT UTD MCV / NSC", "MISSING / SC / NSC")

CPOLlevels=c(1, 2, 3, 4, 5)
CPOLlabels=c("UTD POL / SC", "NOT UTD POL / SC", "UTD POL / NSC", "NOT UTD POL / NSC", "MISSING / SC / NSC")

CVRClevels=c(1, 2, 3, 4, 5)
CVRClabels=c("UTD VRC / SC", "NOT UTD VRC / SC", "UTD VRC / NSC", "NOT UTD VRC / NSC", "MISSING / SC / NSC")

YNlevels=c(1, 2)
YNlabels=c("YES", "NO")

SHOTCARDlevels=c(1, 2)
SHOTCARDlabels=c("SHOTCARD", "NO SHOTCARD")

Ylevels=c(1)
Ylabels=c("YES")

CHILDNMlevels=c(1, 2, 3, 77, 99)
CHILDNMlabels=c("ONE", "TWO OR THREE", "FOUR OR MORE", "DON'T KNOW", "REFUSED")

CWIClevels=c(1, 2, 3, 77, 99)
CWIClabels=c("YES", "NO", "NEVER HEARD OF WIC", "DON'T KNOW", "REFUSED")

EDUC1_levels=c(1, 2, 3, 4, 77, 99)
EDUC1_labels=c("< 12 YEARS", "12 YEARS", "> 12 YEARS, NON-COLLEGE GRAD", "COLLEGE GRAD", "DON'T KNOW", "REFUSED")

HISPlevels=c(1, 2, 3, 4, 5)
HISPlabels=c("HISPANIC", "NON-HISPANIC", "OTHER", "DON'T KNOW", "REFUSED")

MAGEGRPlevels=c(1, 2, 3, 77, 99)
MAGEGRPlabels=c("<= 19 YEARS", "20 - 29 YEARS", ">= 30 YEARS", "DON'T KNOW", "REFUSED")

MOBILlevels=c(1, 2, 77, 99)
MOBILlabels=c("MOVED FROM DIFFERENT STATE", "DID NOT MOVE FROM DIFFERENT STATE", "DON'T KNOW", "REFUSED")

SEXlevels=c(1, 2, 77, 99)
SEXlabels=c("MALE", "FEMALE", "DON'T KNOW", "REFUSED")

INCPOVlevels=c(1, 2, 3, 4)
INCPOVlabels=c("ABOVE POVERTY, > $75K", "ABOVE POVERTY, <= $75K", "BELOW POVERTY", "UNKNOWN")

DISPlevels=c(1, 10, 11, 2, 3, 4, 5, 6, 7, 8, 9)
DISPlabels=c("COMPLETE PROVIDER INFO, NO PROBLEMS", "INCOMPLETE PROVIDER RESP, HH NOT EXACT", "INCOMPLETE PROVIDER RESP, HH WITHOUT SHOT CARD", "COMPLETE PROVIDER INFO, NO SHOT CARD", "COMPLETE PROVIDER INFO, POOR HISTORY",
"COMPLETE PROVIDER INFO, POOR HIST/OTHER", "INCOMPLETE PROVIDER RESP, BUT 4:3:1:3:3 INDICATED", "INCOMPLETE PROVIDER RESP, INFO MATCHES", "INCOMPLETE PROVIDER RESP, HISTORY UNKNOWN", "INCOMPLETE PROVIDER RESP, 4:3:1:3:3 WITH HH",
"INCOMPLETE PROVIDER RESP, MATCHES HH")

HASPDA2Flevels=c(1, 2)
HASPDA2Flabels=c("CHILD HAS ADEQUATE PROVIDER DATA OR ZERO VACCINATIONS", "CHILD DOES NOT HAVE ADEQUATE PROVIDER DATA")

PROVIDlevels=c(1, 2, 3, 4, 5, 6, 7)
PROVIDlabels=c("ALL PUBLIC FACILITIES", "ALL HOSPITAL FACILITIES", "ALL PRIVATE FACILITIES", "ALL MILITARY/OTHER FACILITIES", "MIXED", "TYPE OF PROVIDER UNKNOWN", "ALL WIC CLINIC PROVIDERS")

REGISTRYlevels=c(1, 2, 3, 4)
REGISTRYlabels=c("ALL PROVIDERS", "SOME BUT POSSIBLY OR DEFINITELY NOT ALL PROVIDERS", "NO PROVIDERS", "UNKNOWN/DON'T KNOW")

TYPElevels=c("", "01", "02", "03", "04", "05", "07", "08", "20", "21", "22", "30", "31", "32", "33", "43", "44", "60", "70", "71", "72", "BC", "DH", "DK", "FL", "FM", "FN", "FO", "HA", "HB", "HI", "MA", "MB", "MM", "MP", "NC", "OT", "RB", "RO", "TY", "UN",
"VA", "VM", "VO", "YF")
TYPElabels=c("MISSING", "DT", "DTP", "DTP-UNKNOWN", "DTAP", "DTP-HIB", "DTAP-HIB", "DTAP-HEPB-IPV", "OPV", "IPV", "POLIO-UNKNOWN", "MMR", "MEASLES ONLY", "MEASLES-MUMPS", "MEASLES-RUBELLA", "HEPB-HIB", "HIB ONLY", "HEPB ONLY", "CONJUGATE",
"POLYSACCHARIDE", "PCV-UNKNOWN", "BCG (TUBERCULOSIS)", "DTP-HEPB", "DON'T KNOW", "FLU-UNKNOWN", "FLU SPRAY", "FLU INJECTED", "FOUR-IN-ONE", "HEPA", "HEPB-UNKNOWN", "HIB-UNKNOWN", "MALARIA", "MUMPS-RUBELLA", "MCV-UNKNOWN", "MUMPS", "NEVER CODABLE",
"OTHER (SPECIFY)", "RUBELLA", "ROTAVIRUS", "TYPHOID", "UNCODABLE", "VARICELLA-UNKNOWN", "MMR-VARICELLA", "VARICELLA-ONLY", "YELLOW FEVER")

HEPBRTlevels=c(1, 2)
HEPBRTlabels=c("AT LEAST ONE PROVIDER CHECKED GIVEN AT BIRTH", "NO PROVIDERS CHECKED GIVEN AT BIRTH")

HEPFLGlevels=c(1, 2)
HEPFLGlabels=c("HEPB BIRTH SHOT DATE IMPUTED FROM SHOTCARD", "HEPB BIRTH SHOT DATE IMPUTED FROM DISTRIBUTION OF BIRTH DOSE DATES")

UTDlevels=c(0, 1)
UTDlabels=c("NOT UTD", "UTD")

CENREGlevels=c(1, 2, 3, 4)
CENREGlabels=c("NORTHEAST", "MIDWEST", "SOUTH", "WEST")

STATElevels=c(1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 4, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 5, 50, 51, 52, 53, 54, 55, 56, 6, 7, 8, 9)
STATElabels=c("ALABAMA", "DELAWARE", "DISTRICT OF COLUMBIA", "FLORIDA", "GEORGIA", "", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "ALASKA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA",
"MISSISSIPPI", "MISSOURI", "", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", "ARIZONA", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "", "RHODE ISLAND", "SOUTH CAROLINA",
"SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH", "ARKANSAS", "VERMONT", "VIRGINIA", "", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING", "CALIFORNIA", "", "COLORADO", "CONNECTICUT")

FLUUTDlevels=c(1, 2, 3)
FLUUTDlabels=c("VACCINATED", "NOT VACCINATED", "NOT ELIGIBLE")

RACE_PUFlevels=c(1, 2, 3)
RACE_PUFlabels=c("WHITE ONLY", "BLACK ONLY", "OTHER + MULTIPLE RACE")

MAR_PUFlevels=c(1, 2, 3)
MAR_PUFlabels=c("WIDOWED/DIVORCED/SEPARATED/DECEASED", "NEVER MARRIED", "MARRIED")

AGECPOXRlevels=c(1, 2, 3, 4)
AGECPOXRlabels=c("0 TO 6 MONTHS OLD", "7 TO 12 MONTHS OLD", "13 TO 18 MONTHS OLD", "19+ MONTHS OLD")

C1Rlevels=c(1, 2, 3, 4, 5, 6, 7, 8)
C1Rlabels=c("1", "2", "3", "4", "5", "6", "7", "8+")

C5Rlevels=c(1, 2, 3, 4, 77, 99)
C5Rlabels=c("MOTHER (STEP, FOSTER, ADOPTIVE) OR FEMALE GUARDIAN", "FATHER (STEP, FOSTER, ADOPTIVE) OR MALE GUARDIAN", "GRANDPARENT", "OTHER FAMILY MEMBER/FRIEND", "DON'T KNOW", "REFUSED")

INOPHONRlevels=c(1, 2, 3)
INOPHONRlabels=c("7 TO 14 DAYS", "15 TO 30 DAYS", "31 TO 365 DAYS")

INCQ298Alevels=c(10, 11, 12, 13, 14, 3, 4, 5, 6, 7, 77, 8, 9, 99)
INCQ298Alabels=c("$35001 - $40000", "$40001 - $50000", "$50001 - $60000", "$60001 - $75000", "$75001+", "$0 - $7500", "$7501 - $10000", "$10001 - $17500", "$17501 - $20000", "$20001 - $25000", "DON'T KNOW", "$25001 - $30000", "$30001 - $35000", "REFUSED")

RACEETHKlevels=c(1, 2, 3, 4)
RACEETHKlabels=c("HISPANIC", "NON-HISPANIC WHITE ONLY", "NON-HISPANIC BLACK ONLY", "NON-HISPANIC OTHER + MULTIPLE RACE")

D6Rlevels=c(0, 1, 2, 3)
D6Rlabels=c("0", "1", "2", "3+")

FRSTBRNlevels=c(1, 2, 77, 99)
FRSTBRNlabels=c("NO", "YES", "DON'T KNOW", "REFUSED")

ESTIAPlevels=c(1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 4, 40, 41, 42, 43, 44, 45, 46, 47, 49, 5, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 6, 60, 61, 62, 63, 64, 65, 66,
67, 68, 69, 7, 70, 71, 72, 73, 74, 75, 76, 771, 772, 78, 79, 8, 80, 81, 82, 83, 84, 85, 86, 87, 88, 9)
ESTIAPlabels=c("CT", "NY-REST OF STATE", "NY-CITY OF NEW YORK", "DISTRICT OF COLUMBIA", "DE", "MD-REST OF STATE", "MD-CITY OF BALTIMORE", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA-REST OF STATE", "AL-REST OF STATE",
"AL-JEFFERSON COUNTY", "FL-REST OF STATE", "FL-DUVAL COUNTY", "FL-MIAMI-DADE COUNTY", "GA-REST OF STATE", "GA-FULTON/DEKALB COUNTIES", "KY", "MS", "NC", "MA-CITY OF BOSTON", "SC", "TN-REST OF STATE", "TN-SHELBY COUNTY", "TN-DAVIDSON COUNTY",
"IL-REST OF STATE", "IL-CITY OF CHICAGO", "IN-REST OF STATE", "IN-MARION COUNTY", "MI-REST OF STATE", "MI-CITY OF DETROIT", "ME", "MN", "OH-REST OF STATE", "OH-CUYAHOGA COUNTY", "OH-FRANKLIN COUNTY", "WI-REST OF STATE", "WI-MILWAUKEE COUNTY", "AR", "LA",
"NM-REST OF STATE", "NH", "OK", "TX-REST OF STATE", "TX-DALLAS COUNTY", "TX-EL PASO COUNTY", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS-REST OF STATE", "MO-REST OF STATE", "NE", "RI", "CO-REST OF STATE", "MT", "ND", "SD", "UT", "WY",
"AZ-REST OF STATE", "AZ-MARICOPA COUNTY", "CA-REST OF STATE", "CA-LOS ANGELES COUNTY", "VT", "CA-SANTA CLARA COUNTY", "CA-SAN DIEGO COUNTY", "HI", "NV-REST OF STATE", "AK", "ID", "OR", "WA-EASTERN WA", "WA-REST OF STATE", "WA-KING COUNTY",
"CA-ALAMEDA COUNTY", "NJ-REST OF STATE", "CA-SAN BERNARDINO COUNTY", "CO-DENVER", "MO-ST. LOUIS COUNTY/CITY", "NV-CLARK COUNTY", "CA-FRESNO COUNTY", "CA-NORTHERN CA", "KS-EASTERN KS", "PA-ALLEGHENY COUNTY", "NM-SOUTHERN NM", "NJ-CITY OF NEWARK")

CHARIDlevels=c( )
CHARIDlabels=c("MISSING")

ESTIAP07Flevels=c(1, 10, 11, 12, 13, 14, 16, 17, 18, 19, 2, 20, 22, 24, 25, 27, 28, 29, 30, 31, 34, 35, 36, 37, 38, 4, 40, 41, 44, 46, 47, 49, 5, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 6, 60, 61, 62, 63, 64, 65, 66, 68, 69, 7, 72, 73, 74, 75, 76, 77, 773,
79, 8, 80)
ESTIAP07Flabels=c("CT", "NY-REST OF STATE", "NY-CITY OF NEW YORK", "DISTRICT OF COLUMBIA", "DE", "MD", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA", "AL", "FL-REST OF STATE", "FL-DADE COUNTY", "GA", "KY", "MS", "NC", "SC", "TN",
"IL-REST OF STATE", "IL-CITY OF CHICAGO", "IN-REST OF STATE", "IN-MARION COUNTY", "MI", "ME", "MN", "OH", "WI", "AR", "LA", "NM", "NH", "OK", "TX-REST OF STATE", "TX-DALLAS COUNTY", "TX-EL PASO COUNTY", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS",
"MO", "NE", "RI", "CO", "MT", "ND", "SD", "UT", "WY", "AZ", "CA-REST OF STATE", "CA-LOS ANGELES COUNTY", "VT", "HI", "NV", "AK", "ID", "OR", "WA-REST OF STATE", "WA-WESTERN WASHINGTON", "CA-ALAMEDA COUNTY", "NJ", "CA-SAN BERNARDINO COUNTY")

BFFORM08Flevels=c(888)
BFFORM08Flabels=c("NEVER FED FORMULA")

ESTIAP08Flevels=c(1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 22, 24, 25, 27, 28, 29, 30, 31, 34, 35, 36, 38, 4, 40, 41, 44, 46, 47, 49, 5, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 6, 60, 61, 62, 63, 64, 65, 66, 68, 69, 7, 70, 72, 73, 74, 75, 76, 77,
774, 8, 85, 91, 92, 93)
ESTIAP08Flabels=c("CT", "NY-REST OF STATE", "NY-CITY OF NEW YORK", "DC", "DE", "MD-REST OF STATE", "MD-CITY OF BALTIMORE", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA", "AL", "FL-REST OF STATE", "FL-MIAMI-DADE COUNTY", "GA", "KY", "MS",
"NC", "SC", "TN", "IL-REST OF STATE", "IL-CITY OF CHICAGO", "IN", "MI", "ME", "MN-REST OF STATE", "OH", "WI", "AR", "LA", "NM", "NH", "OK", "TX-REST OF STATE", "TX-DALLAS COUNTY", "TX-EL PASO COUNTY", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS",
"MO", "NE", "RI", "CO", "MT", "ND", "SD", "UT", "WY", "AZ", "CA-REST OF STATE", "CA-LOS ANGELES COUNTY", "VT", "CA-SANTA CLARA COUNTY", "HI", "NV", "AK", "ID", "OR", "WA-REST OF STATE", "WA-EASTERN/WESTERN WA", "NJ", "CA-NORTHERN CA", "FL-ORANGE COUNTY",
"IL-MADISON/ST. CLAIR COUNTIES", "MN-TWIN CITIES")


############################################################################
# Step 3:   READ THE FLAT DATA FILE                                        #
############################################################################

LIST.NAMEWIDTH <-
c("SEQNUMC",6,
"SEQNUMHH",5,
"PDAT",1,
"PROVWT",19,
"RDDWT",19,
"YEAR",4,
"AGECPOXR",1,
"SC_431",2,
"SC_4313",2,
"SC_43133",2,
"SC_DTP",2,
"SC_HEPB",2,
"SC_HIB",2,
"SC_MCV",2,
"SC_POL",2,
"SC_VRC",2,
"HH_DTP",2,
"HH_FLU",2,
"HH_HEPB",2,
"HH_HIB",2,
"HH_MCV",2,
"HH_POL",2,
"HH_VRC",2,
"HAD_CPOX",2,
"SHOTCARD",1,
"AGEGRP",1,
"BF_ENDR06",8,
"BF_EXCLR06",8,
"BF_FORMR08",8,
"BFENDFL06",1,
"BFFORMFL06",1,
"C1R",1,
"C5R",2,
"CBF_01",2,
"CEN_REG",1,
"CHILDNM",1,
"CWIC_01",2,
"CWIC_02",2,
"EDUC1",1,
"FRSTBRN",1,
"I_HISP_K",1,
"INCPORAR",16,
"INCPOV1",1,
"INCQ298A",2,
"INOPHONR",1,
"INTRP",1,
"LANGUAGE",1,
"M_AGEGRP",1,
"MARITAL",1,
"MOBIL_I",1,
"RACE_K",1,
"RACEETHK",1,
"SEX",1,
"ESTIAP08",3,
"STATE",2,
"D6R",1,
"D7",1,
"DISPCODE",2,
"N_PRVR",1,
"PROV_FAC",1,
"REGISTRY",1,
"VFC_ORDER",1,
"HEP_BRTH",1,
"HEP_FLAG",1,
"P_NUHEPX",1,
"P_NUHIBX",1,
"P_NUHPHB",1,
"P_NUMDAH",1,
"P_NUMDHB",1,
"P_NUMDHI",1,
"P_NUMDHM",1,
"P_NUMDTA",1,
"P_NUMDTM",1,
"P_NUMDTP",1,
"P_NUMFLU",1,
"P_NUMFLUL",1,
"P_NUMFLUM",1,
"P_NUMFLUN",1,
"P_NUMHEA",1,
"P_NUMHEN",1,
"P_NUMHEP",1,
"P_NUMHIB",1,
"P_NUMHIN",1,
"P_NUMIPV",1,
"P_NUMMCN",1,
"P_NUMMMR",1,
"P_NUMMMRX",1,
"P_NUMMMX",1,
"P_NUMMP",1,
"P_NUMMPR",1,
"P_NUMMRV",1,
"P_NUMMS",1,
"P_NUMMSM",1,
"P_NUMMSR",1,
"P_NUMOLN",1,
"P_NUMOPV",1,
"P_NUMPCC",1,
"P_NUMPCN",1,
"P_NUMPCP",1,
"P_NUMPCV",1,
"P_NUMPOL",1,
"P_NUMRB",1,
"P_NUMROT",1,
"P_NUMTPM",1,
"P_NUMTPN",1,
"P_NUMVRC",1,
"P_NUMVRN",1,
"P_NUMVRX",1,
"P_U12VRC",1,
"P_UTD331",1,
"P_UTD431",1,
"P_UTDFL1",1,
"P_UTDFL2",1,
"P_UTDFL3",1,
"P_UTDHEP",1,
"P_UTDHIB",1,
"P_UTDMCV",1,
"P_UTDMMX",1,
"P_UTDPC3",1,
"P_UTDPCV",1,
"P_UTDPOL",1,
"P_UTDTP3",1,
"P_UTDTP4",1,
"PU431331",1,
"PU4313313",1,
"PU4313314",1,
"PUT43133",1,
"PUTD4313",1,
"DDTP1",4,
"DDTP2",4,
"DDTP3",4,
"DDTP4",4,
"DDTP5",4,
"DDTP6",4,
"DDTP7",3,
"DDTP8",3,
"DDTP9",1,
"DFLU1",4,
"DFLU2",4,
"DFLU3",4,
"DFLU4",4,
"DFLU5",4,
"DFLU6",3,
"DFLU7",1,
"DFLU8",1,
"DFLU9",1,
"DHEPA1",4,
"DHEPA2",4,
"DHEPA3",4,
"DHEPA4",1,
"DHEPA5",1,
"DHEPA6",1,
"DHEPA7",1,
"DHEPA8",1,
"DHEPA9",1,
"DHEPB1",4,
"DHEPB2",4,
"DHEPB3",4,
"DHEPB4",4,
"DHEPB5",3,
"DHEPB6",3,
"DHEPB7",3,
"DHEPB8",1,
"DHEPB9",1,
"DHIB1",4,
"DHIB2",4,
"DHIB3",4,
"DHIB4",4,
"DHIB5",4,
"DHIB6",4,
"DHIB7",3,
"DHIB8",3,
"DHIB9",1,
"DMMR1",4,
"DMMR2",4,
"DMMR3",4,
"DMMR4",1,
"DMMR5",1,
"DMMR6",1,
"DMMR7",1,
"DMMR8",1,
"DMMR9",1,
"DMP1",3,
"DMP2",1,
"DMP3",1,
"DMP4",1,
"DMP5",1,
"DMP6",1,
"DMP7",1,
"DMP8",1,
"DMP9",1,
"DMPRB1",3,
"DMPRB2",1,
"DMPRB3",1,
"DMPRB4",1,
"DMPRB5",1,
"DMPRB6",1,
"DMPRB7",1,
"DMPRB8",1,
"DMPRB9",1,
"DPCV1",4,
"DPCV2",4,
"DPCV3",4,
"DPCV4",4,
"DPCV5",4,
"DPCV6",4,
"DPCV7",3,
"DPCV8",3,
"DPCV9",1,
"DPOLIO1",4,
"DPOLIO2",4,
"DPOLIO3",4,
"DPOLIO4",4,
"DPOLIO5",4,
"DPOLIO6",3,
"DPOLIO7",3,
"DPOLIO8",1,
"DPOLIO9",1,
"DRB1",3,
"DRB2",1,
"DRB3",1,
"DRB4",1,
"DRB5",1,
"DRB6",1,
"DRB7",1,
"DRB8",1,
"DRB9",1,
"DROT1",3,
"DROT2",3,
"DROT3",3,
"DROT4",3,
"DROT5",1,
"DROT6",1,
"DROT7",1,
"DROT8",1,
"DROT9",1,
"DTP1_AGE",2,
"DTP2_AGE",2,
"DTP3_AGE",2,
"DTP4_AGE",2,
"DTP5_AGE",2,
"DTP6_AGE",2,
"DTP7_AGE",2,
"DTP8_AGE",2,
"DTP9_AGE",1,
"DVRC1",4,
"DVRC2",4,
"DVRC3",4,
"DVRC4",1,
"DVRC5",1,
"DVRC6",1,
"DVRC7",1,
"DVRC8",1,
"DVRC9",1,
"FLU1_AGE",2,
"FLU2_AGE",2,
"FLU3_AGE",2,
"FLU4_AGE",2,
"FLU5_AGE",2,
"FLU6_AGE",2,
"FLU7_AGE",1,
"FLU8_AGE",1,
"FLU9_AGE",1,
"HEA1_AGE",2,
"HEA2_AGE",2,
"HEA3_AGE",2,
"HEA4_AGE",1,
"HEA5_AGE",1,
"HEA6_AGE",1,
"HEA7_AGE",1,
"HEA8_AGE",1,
"HEA9_AGE",1,
"HEP1_AGE",2,
"HEP2_AGE",2,
"HEP3_AGE",2,
"HEP4_AGE",2,
"HEP5_AGE",2,
"HEP6_AGE",2,
"HEP7_AGE",2,
"HEP8_AGE",1,
"HEP9_AGE",1,
"HIB1_AGE",2,
"HIB2_AGE",2,
"HIB3_AGE",2,
"HIB4_AGE",2,
"HIB5_AGE",2,
"HIB6_AGE",2,
"HIB7_AGE",2,
"HIB8_AGE",2,
"HIB9_AGE",1,
"MMR1_AGE",2,
"MMR2_AGE",2,
"MMR3_AGE",2,
"MMR4_AGE",1,
"MMR5_AGE",1,
"MMR6_AGE",1,
"MMR7_AGE",1,
"MMR8_AGE",1,
"MMR9_AGE",1,
"MP1_AGE",2,
"MP2_AGE",1,
"MP3_AGE",1,
"MP4_AGE",1,
"MP5_AGE",1,
"MP6_AGE",1,
"MP7_AGE",1,
"MP8_AGE",1,
"MP9_AGE",1,
"MPR1_AGE",1,
"MPR2_AGE",1,
"MPR3_AGE",1,
"MPR4_AGE",1,
"MPR5_AGE",1,
"MPR6_AGE",1,
"MPR7_AGE",1,
"MPR8_AGE",1,
"MPR9_AGE",1,
"PCV1_AGE",2,
"PCV2_AGE",2,
"PCV3_AGE",2,
"PCV4_AGE",2,
"PCV5_AGE",2,
"PCV6_AGE",2,
"PCV7_AGE",2,
"PCV8_AGE",2,
"PCV9_AGE",1,
"POL1_AGE",2,
"POL2_AGE",2,
"POL3_AGE",2,
"POL4_AGE",2,
"POL5_AGE",2,
"POL6_AGE",2,
"POL7_AGE",2,
"POL8_AGE",1,
"POL9_AGE",1,
"RB1_AGE",2,
"RB2_AGE",1,
"RB3_AGE",1,
"RB4_AGE",1,
"RB5_AGE",1,
"RB6_AGE",1,
"RB7_AGE",1,
"RB8_AGE",1,
"RB9_AGE",1,
"ROT1_AGE",2,
"ROT2_AGE",2,
"ROT3_AGE",2,
"ROT4_AGE",2,
"ROT5_AGE",1,
"ROT6_AGE",1,
"ROT7_AGE",1,
"ROT8_AGE",1,
"ROT9_AGE",1,
"VRC1_AGE",2,
"VRC2_AGE",2,
"VRC3_AGE",2,
"VRC4_AGE",1,
"VRC5_AGE",1,
"VRC6_AGE",1,
"VRC7_AGE",1,
"VRC8_AGE",1,
"VRC9_AGE",1,
"XDTPTY1",2,
"XDTPTY2",2,
"XDTPTY3",2,
"XDTPTY4",2,
"XDTPTY5",2,
"XDTPTY6",2,
"XDTPTY7",2,
"XDTPTY8",2,
"XDTPTY9",1,
"XFLUTY1",2,
"XFLUTY2",2,
"XFLUTY3",2,
"XFLUTY4",2,
"XFLUTY5",2,
"XFLUTY6",2,
"XFLUTY7",1,
"XFLUTY8",1,
"XFLUTY9",1,
"XHEPTY1",2,
"XHEPTY2",2,
"XHEPTY3",2,
"XHEPTY4",2,
"XHEPTY5",2,
"XHEPTY6",2,
"XHEPTY7",2,
"XHEPTY8",1,
"XHEPTY9",1,
"XHIBTY1",2,
"XHIBTY2",2,
"XHIBTY3",2,
"XHIBTY4",2,
"XHIBTY5",2,
"XHIBTY6",2,
"XHIBTY7",2,
"XHIBTY8",2,
"XHIBTY9",1,
"XMMRTY1",2,
"XMMRTY2",2,
"XMMRTY3",2,
"XMMRTY4",1,
"XMMRTY5",1,
"XMMRTY6",1,
"XMMRTY7",1,
"XMMRTY8",1,
"XMMRTY9",1,
"XPCVTY1",2,
"XPCVTY2",2,
"XPCVTY3",2,
"XPCVTY4",2,
"XPCVTY5",2,
"XPCVTY6",2,
"XPCVTY7",2,
"XPCVTY8",2,
"XPCVTY9",1,
"XPOLTY1",2,
"XPOLTY2",2,
"XPOLTY3",2,
"XPOLTY4",2,
"XPOLTY5",2,
"XPOLTY6",2,
"XPOLTY7",2,
"XPOLTY8",1,
"XPOLTY9",1,
"XVRCTY1",2,
"XVRCTY2",2,
"XVRCTY3",2,
"XVRCTY4",1,
"XVRCTY5",1,
"XVRCTY6",1,
"XVRCTY7",1,
"XVRCTY8",1,
"XVRCTY9",1,
"INS_1",2,
"INS_2",2,
"INS_3",2,
"INS_3A",2,
"INS_4",2,
"INS_5",2,
"INS_6",2,
"INS_11",2
)

NAMEWIDTH <- matrix(LIST.NAMEWIDTH, 442, 2, byrow=T, dimnames = list(NULL, c("VARIABLE","WIDTH")))
NA_STRING <- c(" ", ".", " .", "  .", "   .", "   .    ", " .              ", "    .              ")

NISPUF08 <- read.fwf(flatfile, widths= as.numeric(NAMEWIDTH[,2]), col.names = NAMEWIDTH[,1], na.strings= NA_STRING, as.is=TRUE)

NISPUF08$SEQNUMC <- as.character(NISPUF08$SEQNUMC)
NISPUF08$SEQNUMHH <- as.character(NISPUF08$SEQNUMHH)
NISPUF08$XDTPTY1 <- as.character(NISPUF08$XDTPTY1)
NISPUF08$XDTPTY2 <- as.character(NISPUF08$XDTPTY2)
NISPUF08$XDTPTY3 <- as.character(NISPUF08$XDTPTY3)
NISPUF08$XDTPTY4 <- as.character(NISPUF08$XDTPTY4)
NISPUF08$XDTPTY5 <- as.character(NISPUF08$XDTPTY5)
NISPUF08$XDTPTY6 <- as.character(NISPUF08$XDTPTY6)
NISPUF08$XDTPTY7 <- as.character(NISPUF08$XDTPTY7)
NISPUF08$XDTPTY8 <- as.character(NISPUF08$XDTPTY8)
NISPUF08$XDTPTY9 <- as.character(NISPUF08$XDTPTY9)
NISPUF08$XFLUTY1 <- as.character(NISPUF08$XFLUTY1)
NISPUF08$XFLUTY2 <- as.character(NISPUF08$XFLUTY2)
NISPUF08$XFLUTY3 <- as.character(NISPUF08$XFLUTY3)
NISPUF08$XFLUTY4 <- as.character(NISPUF08$XFLUTY4)
NISPUF08$XFLUTY5 <- as.character(NISPUF08$XFLUTY5)
NISPUF08$XFLUTY6 <- as.character(NISPUF08$XFLUTY6)
NISPUF08$XFLUTY7 <- as.character(NISPUF08$XFLUTY7)
NISPUF08$XFLUTY8 <- as.character(NISPUF08$XFLUTY8)
NISPUF08$XFLUTY9 <- as.character(NISPUF08$XFLUTY9)
NISPUF08$XHEPTY1 <- as.character(NISPUF08$XHEPTY1)
NISPUF08$XHEPTY2 <- as.character(NISPUF08$XHEPTY2)
NISPUF08$XHEPTY3 <- as.character(NISPUF08$XHEPTY3)
NISPUF08$XHEPTY4 <- as.character(NISPUF08$XHEPTY4)
NISPUF08$XHEPTY5 <- as.character(NISPUF08$XHEPTY5)
NISPUF08$XHEPTY6 <- as.character(NISPUF08$XHEPTY6)
NISPUF08$XHEPTY7 <- as.character(NISPUF08$XHEPTY7)
NISPUF08$XHEPTY8 <- as.character(NISPUF08$XHEPTY8)
NISPUF08$XHEPTY9 <- as.character(NISPUF08$XHEPTY9)
NISPUF08$XHIBTY1 <- as.character(NISPUF08$XHIBTY1)
NISPUF08$XHIBTY2 <- as.character(NISPUF08$XHIBTY2)
NISPUF08$XHIBTY3 <- as.character(NISPUF08$XHIBTY3)
NISPUF08$XHIBTY4 <- as.character(NISPUF08$XHIBTY4)
NISPUF08$XHIBTY5 <- as.character(NISPUF08$XHIBTY5)
NISPUF08$XHIBTY6 <- as.character(NISPUF08$XHIBTY6)
NISPUF08$XHIBTY7 <- as.character(NISPUF08$XHIBTY7)
NISPUF08$XHIBTY8 <- as.character(NISPUF08$XHIBTY8)
NISPUF08$XHIBTY9 <- as.character(NISPUF08$XHIBTY9)
NISPUF08$XMMRTY1 <- as.character(NISPUF08$XMMRTY1)
NISPUF08$XMMRTY2 <- as.character(NISPUF08$XMMRTY2)
NISPUF08$XMMRTY3 <- as.character(NISPUF08$XMMRTY3)
NISPUF08$XMMRTY4 <- as.character(NISPUF08$XMMRTY4)
NISPUF08$XMMRTY5 <- as.character(NISPUF08$XMMRTY5)
NISPUF08$XMMRTY6 <- as.character(NISPUF08$XMMRTY6)
NISPUF08$XMMRTY7 <- as.character(NISPUF08$XMMRTY7)
NISPUF08$XMMRTY8 <- as.character(NISPUF08$XMMRTY8)
NISPUF08$XMMRTY9 <- as.character(NISPUF08$XMMRTY9)
NISPUF08$XPCVTY1 <- as.character(NISPUF08$XPCVTY1)
NISPUF08$XPCVTY2 <- as.character(NISPUF08$XPCVTY2)
NISPUF08$XPCVTY3 <- as.character(NISPUF08$XPCVTY3)
NISPUF08$XPCVTY4 <- as.character(NISPUF08$XPCVTY4)
NISPUF08$XPCVTY5 <- as.character(NISPUF08$XPCVTY5)
NISPUF08$XPCVTY6 <- as.character(NISPUF08$XPCVTY6)
NISPUF08$XPCVTY7 <- as.character(NISPUF08$XPCVTY7)
NISPUF08$XPCVTY8 <- as.character(NISPUF08$XPCVTY8)
NISPUF08$XPCVTY9 <- as.character(NISPUF08$XPCVTY9)
NISPUF08$XPOLTY1 <- as.character(NISPUF08$XPOLTY1)
NISPUF08$XPOLTY2 <- as.character(NISPUF08$XPOLTY2)
NISPUF08$XPOLTY3 <- as.character(NISPUF08$XPOLTY3)
NISPUF08$XPOLTY4 <- as.character(NISPUF08$XPOLTY4)
NISPUF08$XPOLTY5 <- as.character(NISPUF08$XPOLTY5)
NISPUF08$XPOLTY6 <- as.character(NISPUF08$XPOLTY6)
NISPUF08$XPOLTY7 <- as.character(NISPUF08$XPOLTY7)
NISPUF08$XPOLTY8 <- as.character(NISPUF08$XPOLTY8)
NISPUF08$XPOLTY9 <- as.character(NISPUF08$XPOLTY9)
NISPUF08$XVRCTY1 <- as.character(NISPUF08$XVRCTY1)
NISPUF08$XVRCTY2 <- as.character(NISPUF08$XVRCTY2)
NISPUF08$XVRCTY3 <- as.character(NISPUF08$XVRCTY3)
NISPUF08$XVRCTY4 <- as.character(NISPUF08$XVRCTY4)
NISPUF08$XVRCTY5 <- as.character(NISPUF08$XVRCTY5)
NISPUF08$XVRCTY6 <- as.character(NISPUF08$XVRCTY6)
NISPUF08$XVRCTY7 <- as.character(NISPUF08$XVRCTY7)
NISPUF08$XVRCTY8 <- as.character(NISPUF08$XVRCTY8)
NISPUF08$XVRCTY9 <- as.character(NISPUF08$XVRCTY9)

############################################################################
# Step 4:   ASSIGN VARIABLE LABELS                                         #
############################################################################

label(NISPUF08$SEQNUMC) <- "UNIQUE CHILD IDENTIFIER"
label(NISPUF08$SEQNUMHH) <- "UNIQUE HOUSEHOLD IDENTIFIER"
label(NISPUF08$PDAT) <- "CHILD HAS ADEQUATE PROVIDER DATA"
label(NISPUF08$PROVWT) <- "WEIGHT FOR CHILDREN WITH ADEQUATE PROVIDER DATA AND UNVACCINATED CHILDREN"
label(NISPUF08$RDDWT) <- "HH-PHASE CHILD INTERVIEW WEIGHT"

label(NISPUF08$YEAR) <- "YEAR OF INTERVIEW"
label(NISPUF08$AGECPOXR) <- "AGE IN MONTHS AT CHICKEN POX DISEASE (RECODE)"
label(NISPUF08$SC_431) <- "HH SHOT CARD REPORT OF 4:3:1 UP-TO-DATE"
label(NISPUF08$SC_4313) <- "HH SHOT CARD REPORT OF 4:3:1:3 UP-TO-DATE"
label(NISPUF08$SC_43133) <- "HH SHOT CARD REPORT OF 4:3:1:3:3 UP-TO-DATE"

label(NISPUF08$SC_DTP) <- "HH SHOT CARD REPORT OF 4+ DT-CONTAINING UP-TO-DATE"
label(NISPUF08$SC_HEPB) <- "HH SHOT CARD REPORT OF 3+ HEPATITIS B-CONTAINING UP-TO-DATE"
label(NISPUF08$SC_HIB) <- "HH SHOT CARD REPORT OF 3+ HIB-CONTAINING UP-TO-DATE"
label(NISPUF08$SC_MCV) <- "HH SHOT CARD REPORT OF 1+ MEASLES-CONTAINING UP-TO-DATE"
label(NISPUF08$SC_POL) <- "HH SHOT CARD REPORT OF 3+ POLIO-CONTAINING UP-TO-DATE"

label(NISPUF08$SC_VRC) <- "HH SHOT CARD REPORT OF 1+ VARICELLA-CONTAINING UP-TO-DATE"
label(NISPUF08$HH_DTP) <- "HH REPORT OF NUMBER OF DT-CONTAINING SHOTS RECEIVED"
label(NISPUF08$HH_FLU) <- "HH REPORT OF NUMBER OF FLU VACCINATIONS RECEIVED"
label(NISPUF08$HH_HEPB) <- "HH REPORT OF NUMBER OF HEPATITIS B-CONTAINING SHOTS RECEIVED"
label(NISPUF08$HH_HIB) <- "HH REPORT OF NUMBER OF HIB-CONTAINING SHOTS RECEIVED"

label(NISPUF08$HH_MCV) <- "HH REPORT OF NUMBER OF MEASLES-CONTAINING SHOTS RECEIVED"
label(NISPUF08$HH_POL) <- "HH REPORT OF NUMBER OF POLIO-CONTAINING SHOTS RECEIVED"
label(NISPUF08$HH_VRC) <- "HH REPORT OF NUMBER OF VARICELLA-CONTAINING SHOTS RECEIVED"
label(NISPUF08$HAD_CPOX) <- "CHILD EVER HAD CHICKEN POX DISEASE?"
label(NISPUF08$SHOTCARD) <- "SHOT CARD USE FLAG"

label(NISPUF08$AGEGRP) <- "AGE CATEGORY OF CHILD (19-23, 24-29, 30-35 MO) (RECODE)"
label(NISPUF08$BF_ENDR06) <- "DURATION OF BREAST FEEDING IN DAYS (TOPCODE)"
label(NISPUF08$BF_EXCLR06) <- "DURATION OF EXCLUSIVE BREAST/FORMULA FEEDING IN DAYS (TOPCODE)"
label(NISPUF08$BF_FORMR08) <- "AGE IN DAYS WHEN CHILD FIRST FED FORMULA (TOPCODE)"
label(NISPUF08$BFENDFL06) <- "DURATION OF BREAST FEEDING EXCEEDS CHILD AGE IN DAYS, WITH BUFFER"

label(NISPUF08$BFFORMFL06) <- "AGE IN DAYS WHEN CHILD FIRST FED FORMULA EXCEEDS CHILD AGE IN DAYS, WITH BUFFER"
label(NISPUF08$C1R) <- "NUMBER OF PEOPLE IN HOUSEHOLD (TOPCODE)"
label(NISPUF08$C5R) <- "RELATIONSHIP OF RESPONDENT TO CHILD (RECODE)"
label(NISPUF08$CBF_01) <- "WAS CHILD EVER BREAST FED OR FED BREAST MILK?"
label(NISPUF08$CEN_REG) <- "CENSUS REGION BASED ON TRUE STATE OF RESIDENCE"

label(NISPUF08$CHILDNM) <- "NUMBER OF CHILDREN LESS THAN 18 YEARS IN HH (RECODE)"
label(NISPUF08$CWIC_01) <- "CHILD EVER RECEIVED WIC BENEFITS?"
label(NISPUF08$CWIC_02) <- "CHILD CURRENTLY RECEIVING WIC BENEFITS?"
label(NISPUF08$EDUC1) <- "EDUCATION OF MOTHER CATEGORIES (RECODE)"
label(NISPUF08$FRSTBRN) <- "FIRST BORN STATUS OF CHILD"

label(NISPUF08$I_HISP_K) <- "HISPANIC ORIGIN OF CHILD"
label(NISPUF08$INCPORAR) <- "INCOME TO POVERTY RATIO (TOP- AND BOTTOMCODE)"
label(NISPUF08$INCPOV1) <- "POVERTY STATUS"
label(NISPUF08$INCQ298A) <- "FAMILY INCOME CATEGORIES (RECODE)"
label(NISPUF08$INOPHONR) <- "LENGTH OF INTERRUPTION IN TELEPHONE SERVICE IN DAYS (RECODE)"

label(NISPUF08$INTRP) <- "PHONE INTERRUPTION OF 7 DAYS OR MORE IN PAST YEAR?"
label(NISPUF08$LANGUAGE) <- "LANGUAGE IN WHICH INTERVIEW WAS CONDUCTED"
label(NISPUF08$M_AGEGRP) <- "AGE OF MOTHER CATEGORIES"
label(NISPUF08$MARITAL) <- "MARITAL STATUS OF MOTHER CATEGORIES (RECODE)"
label(NISPUF08$MOBIL_I) <- "GEOGRAPHIC MOBILITY STATUS: STATE OF RESIDENCE OF CHILD AT BIRTH VERSUS CURRENT STATE"

label(NISPUF08$RACE_K) <- "RACE OF CHILD (RECODE)"
label(NISPUF08$RACEETHK) <- "RACE/ETHNICITY OF CHILD (RECODE)"
label(NISPUF08$SEX) <- "GENDER OF CHILD"
label(NISPUF08$ESTIAP08) <- "ESTIMATION AREA OF RESIDENCE"
label(NISPUF08$STATE) <- "TRUE STATE OF RESIDENCE (STATE FIPS CODE)"

label(NISPUF08$D6R) <- "NUMBER OF VACCINATION PROVIDERS IDENTIFIED BY RESPONDENT (TOPCODE)"
label(NISPUF08$D7) <- "CONSENT TO OBTAIN CHILD'S IMMUNIZATION RECORDS FROM PROVIDERS"
label(NISPUF08$DISPCODE) <- "NIS PROVIDER RECORD-CHECK DISPOSITION CODE"
label(NISPUF08$N_PRVR) <- "NUMBER OF PROVIDERS RESPONDING WITH VACCINATION DATA FOR CHILD (TOPCODE)"
label(NISPUF08$PROV_FAC) <- "PROVIDER FACILITY TYPE"

label(NISPUF08$REGISTRY) <- "CHILD'S PROVIDERS REPORTED CHILD'S VACCINATIONS TO IMMUNIZATION REGISTRY"
label(NISPUF08$VFC_ORDER) <- "DO CHILD'S PROVIDERS ORDER VACCINES FROM STATE/LOCAL HEALTH DEPT?"
label(NISPUF08$HEP_BRTH) <- "HEPATITIS B-CONTAINING SHOT GIVEN AT BIRTH FLAG"
label(NISPUF08$HEP_FLAG) <- "HEPATITIS B BIRTH SHOT DATE IMPUTATION FLAG"
label(NISPUF08$P_NUHEPX) <- "NUMBER OF HEPATITIS B-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF08$P_NUHIBX) <- "NUMBER OF HIB-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUHPHB) <- "NUMBER OF HEPATITIS B/HIB COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMDAH) <- "NUMBER OF DTAP/HIB COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMDHB) <- "NUMBER OF DTP/HIB CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMDHI) <- "NUMBER OF DTAP/HEPB/IPV COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF08$P_NUMDHM) <- "NUMBER OF DTP/HIB COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMDTA) <- "NUMBER OF DTAP-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMDTM) <- "NUMBER OF DT-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMDTP) <- "NUMBER OF DT-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMFLU) <- "NUMBER OF FLU-CONTAINING VACCINATIONS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF08$P_NUMFLUL) <- "NUMBER OF FLU-CONTAINING VACCINATIONS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMFLUM) <- "NUMBER OF FLU SPRAY VACCINATIONS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMFLUN) <- "NUMBER OF INJECTED FLU VACCINATIONS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMHEA) <- "NUMBER OF HEPATITIS A-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMHEN) <- "NUMBER OF HEPATITIS B-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF08$P_NUMHEP) <- "NUMBER OF HEPATITIS B-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMHIB) <- "NUMBER OF HIB-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMHIN) <- "NUMBER OF HIB-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMIPV) <- "NUMBER OF IPV-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMMCN) <- "NUMBER OF MEASLES-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF08$P_NUMMMR) <- "NUMBER OF MEASLES-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMMMRX) <- "NUMBER OF MMR-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMMMX) <- "NUMBER OF MMR-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMMP) <- "NUMBER OF MUMPS-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMMPR) <- "NUMBER OF (MUMPS/RUBELLA)-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF08$P_NUMMRV) <- "NUMBER OF MMR/VARICELLA COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMMS) <- "NUMBER OF MEASLES-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMMSM) <- "NUMBER OF MEASLES/MUMPS COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMMSR) <- "NUMBER OF MEASLES/RUBELLA COMBO SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMOLN) <- "NUMBER OF POLIO SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF08$P_NUMOPV) <- "NUMBER OF OPV-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMPCC) <- "NUMBER OF PCV CONJUGATE SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMPCN) <- "NUMBER OF PCV SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMPCP) <- "NUMBER OF PCV POLYSACCHARIDE SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMPCV) <- "NUMBER OF PNEUMOCOCCAL-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF08$P_NUMPOL) <- "NUMBER OF POLIO-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMRB) <- "NUMBER OF RUBELLA-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMROT) <- "NUMBER OF ROTAVIRUS-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMTPM) <- "NUMBER OF DTP-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMTPN) <- "NUMBER OF DT-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."

label(NISPUF08$P_NUMVRC) <- "NUMBER OF VARICELLA-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMVRN) <- "NUMBER OF VARICELLA-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_NUMVRX) <- "NUMBER OF VARICELLA-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
label(NISPUF08$P_U12VRC) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ VARICELLA-CONTAINING SHOT AT 12+ MONTHS"
label(NISPUF08$P_UTD331) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3:3:1"

label(NISPUF08$P_UTD431) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1"
label(NISPUF08$P_UTDFL1) <- "UTD FLAG FOR PROVIDER INFLUENZA VARIABLE 1"
label(NISPUF08$P_UTDFL2) <- "UTD FLAG FOR PROVIDER INFLUENZA VARIABLE 2"
label(NISPUF08$P_UTDFL3) <- "UTD FLAG FOR PROVIDER INFLUENZA VARIABLE 3"
label(NISPUF08$P_UTDHEP) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HEPATITIS B-CONTAINING SHOTS"

label(NISPUF08$P_UTDHIB) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HIB-CONTAINING SHOTS"
label(NISPUF08$P_UTDMCV) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 1+ MEASLES-CONTAINING SHOT"
label(NISPUF08$P_UTDMMX) <- "UTD FLAG FOR PROVIDER 1+ MMR COMBO SHOT"
label(NISPUF08$P_UTDPC3) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ PNEUMOCOCCAL-CONTAINING SHOTS"
label(NISPUF08$P_UTDPCV) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4+ PNEUMOCOCCAL-CONTAINING SHOTS"

label(NISPUF08$P_UTDPOL) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ POLIO-CONTAINING SHOTS"
label(NISPUF08$P_UTDTP3) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ DT-CONTAINING SHOTS"
label(NISPUF08$P_UTDTP4) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4+ DT-CONTAINING SHOTS"
label(NISPUF08$PU431331) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3:1 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS)"
label(NISPUF08$PU4313313) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3:1:3 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS)"

label(NISPUF08$PU4313314) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3:1:4 (INCLUDES 1+ VARICELLA AT AGE 12+ MTHS)"
label(NISPUF08$PUT43133) <- "UTD FLAG FOR PROVIDER 4:3:1:3:3"
label(NISPUF08$PUTD4313) <- "UTD FLAG FOR PROVIDER 4:3:1:3"
label(NISPUF08$DDTP1) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #1"
label(NISPUF08$DDTP2) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #2"

label(NISPUF08$DDTP3) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #3"
label(NISPUF08$DDTP4) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #4"
label(NISPUF08$DDTP5) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #5"
label(NISPUF08$DDTP6) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #6"
label(NISPUF08$DDTP7) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #7"

label(NISPUF08$DDTP8) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #8"
label(NISPUF08$DDTP9) <- "AGE IN DAYS OF PROV-REPTD DT-CONTAINING SHOT #9"
label(NISPUF08$DFLU1) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING VACCINATION #1"
label(NISPUF08$DFLU2) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING VACCINATION #2"
label(NISPUF08$DFLU3) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING VACCINATION #3"

label(NISPUF08$DFLU4) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING VACCINATION #4"
label(NISPUF08$DFLU5) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING VACCINATION #5"
label(NISPUF08$DFLU6) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING VACCINATION #6"
label(NISPUF08$DFLU7) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING VACCINATION #7"
label(NISPUF08$DFLU8) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING VACCINATION #8"

label(NISPUF08$DFLU9) <- "AGE IN DAYS OF PROV-REPTD FLU-CONTAINING VACCINATION #9"
label(NISPUF08$DHEPA1) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #1"
label(NISPUF08$DHEPA2) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #2"
label(NISPUF08$DHEPA3) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #3"
label(NISPUF08$DHEPA4) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #4"

label(NISPUF08$DHEPA5) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #5"
label(NISPUF08$DHEPA6) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #6"
label(NISPUF08$DHEPA7) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #7"
label(NISPUF08$DHEPA8) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #8"
label(NISPUF08$DHEPA9) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #9"

label(NISPUF08$DHEPB1) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #1"
label(NISPUF08$DHEPB2) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #2"
label(NISPUF08$DHEPB3) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #3"
label(NISPUF08$DHEPB4) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #4"
label(NISPUF08$DHEPB5) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #5"

label(NISPUF08$DHEPB6) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #6"
label(NISPUF08$DHEPB7) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #7"
label(NISPUF08$DHEPB8) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #8"
label(NISPUF08$DHEPB9) <- "AGE IN DAYS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #9"
label(NISPUF08$DHIB1) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #1"

label(NISPUF08$DHIB2) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #2"
label(NISPUF08$DHIB3) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #3"
label(NISPUF08$DHIB4) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #4"
label(NISPUF08$DHIB5) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #5"
label(NISPUF08$DHIB6) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #6"

label(NISPUF08$DHIB7) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #7"
label(NISPUF08$DHIB8) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #8"
label(NISPUF08$DHIB9) <- "AGE IN DAYS OF PROV-REPTD HIB-CONTAINING SHOT #9"
label(NISPUF08$DMMR1) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #1"
label(NISPUF08$DMMR2) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #2"

label(NISPUF08$DMMR3) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #3"
label(NISPUF08$DMMR4) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #4"
label(NISPUF08$DMMR5) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #5"
label(NISPUF08$DMMR6) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #6"
label(NISPUF08$DMMR7) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #7"

label(NISPUF08$DMMR8) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #8"
label(NISPUF08$DMMR9) <- "AGE IN DAYS OF PROV-REPTD MEASLES-CONTAINING SHOT #9"
label(NISPUF08$DMP1) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #1"
label(NISPUF08$DMP2) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #2"
label(NISPUF08$DMP3) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #3"

label(NISPUF08$DMP4) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #4"
label(NISPUF08$DMP5) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #5"
label(NISPUF08$DMP6) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #6"
label(NISPUF08$DMP7) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #7"
label(NISPUF08$DMP8) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #8"

label(NISPUF08$DMP9) <- "AGE IN DAYS OF PROV-REPTD MUMPS-ONLY SHOT #9"
label(NISPUF08$DMPRB1) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #1"
label(NISPUF08$DMPRB2) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #2"
label(NISPUF08$DMPRB3) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #3"
label(NISPUF08$DMPRB4) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #4"

label(NISPUF08$DMPRB5) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #5"
label(NISPUF08$DMPRB6) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #6"
label(NISPUF08$DMPRB7) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #7"
label(NISPUF08$DMPRB8) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #8"
label(NISPUF08$DMPRB9) <- "AGE IN DAYS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #9"

label(NISPUF08$DPCV1) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #1"
label(NISPUF08$DPCV2) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #2"
label(NISPUF08$DPCV3) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #3"
label(NISPUF08$DPCV4) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #4"
label(NISPUF08$DPCV5) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #5"

label(NISPUF08$DPCV6) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #6"
label(NISPUF08$DPCV7) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #7"
label(NISPUF08$DPCV8) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #8"
label(NISPUF08$DPCV9) <- "AGE IN DAYS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #9"
label(NISPUF08$DPOLIO1) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #1"

label(NISPUF08$DPOLIO2) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #2"
label(NISPUF08$DPOLIO3) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #3"
label(NISPUF08$DPOLIO4) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #4"
label(NISPUF08$DPOLIO5) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #5"
label(NISPUF08$DPOLIO6) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #6"

label(NISPUF08$DPOLIO7) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #7"
label(NISPUF08$DPOLIO8) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #8"
label(NISPUF08$DPOLIO9) <- "AGE IN DAYS OF PROV-REPTD POLIO-CONTAINING SHOT #9"
label(NISPUF08$DRB1) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #1"
label(NISPUF08$DRB2) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #2"

label(NISPUF08$DRB3) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #3"
label(NISPUF08$DRB4) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #4"
label(NISPUF08$DRB5) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #5"
label(NISPUF08$DRB6) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #6"
label(NISPUF08$DRB7) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #7"

label(NISPUF08$DRB8) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #8"
label(NISPUF08$DRB9) <- "AGE IN DAYS OF PROV-REPTD RUBELLA-ONLY SHOT #9"
label(NISPUF08$DROT1) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #1"
label(NISPUF08$DROT2) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #2"
label(NISPUF08$DROT3) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #3"

label(NISPUF08$DROT4) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #4"
label(NISPUF08$DROT5) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #5"
label(NISPUF08$DROT6) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #6"
label(NISPUF08$DROT7) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #7"
label(NISPUF08$DROT8) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #8"

label(NISPUF08$DROT9) <- "AGE IN DAYS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #9"
label(NISPUF08$DTP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #1"
label(NISPUF08$DTP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #2"
label(NISPUF08$DTP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #3"
label(NISPUF08$DTP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #4"

label(NISPUF08$DTP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #5"
label(NISPUF08$DTP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #6"
label(NISPUF08$DTP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #7"
label(NISPUF08$DTP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #8"
label(NISPUF08$DTP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD DT-CONTAINING SHOT #9"

label(NISPUF08$DVRC1) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #1"
label(NISPUF08$DVRC2) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #2"
label(NISPUF08$DVRC3) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #3"
label(NISPUF08$DVRC4) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #4"
label(NISPUF08$DVRC5) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #5"

label(NISPUF08$DVRC6) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #6"
label(NISPUF08$DVRC7) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #7"
label(NISPUF08$DVRC8) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #8"
label(NISPUF08$DVRC9) <- "AGE IN DAYS OF PROV-REPTD VARICELLA-CONTAINING SHOT #9"
label(NISPUF08$FLU1_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING VACCINATION #1"

label(NISPUF08$FLU2_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING VACCINATION #2"
label(NISPUF08$FLU3_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING VACCINATION #3"
label(NISPUF08$FLU4_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING VACCINATION #4"
label(NISPUF08$FLU5_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING VACCINATION #5"
label(NISPUF08$FLU6_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING VACCINATION #6"

label(NISPUF08$FLU7_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING VACCINATION #7"
label(NISPUF08$FLU8_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING VACCINATION #8"
label(NISPUF08$FLU9_AGE) <- "AGE IN MONTHS OF PROV-REPTD FLU-CONTAINING VACCINATION #9"
label(NISPUF08$HEA1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #1"
label(NISPUF08$HEA2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #2"

label(NISPUF08$HEA3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #3"
label(NISPUF08$HEA4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #4"
label(NISPUF08$HEA5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #5"
label(NISPUF08$HEA6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #6"
label(NISPUF08$HEA7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #7"

label(NISPUF08$HEA8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #8"
label(NISPUF08$HEA9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS A-CONTAINING SHOT #9"
label(NISPUF08$HEP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #1"
label(NISPUF08$HEP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #2"
label(NISPUF08$HEP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #3"

label(NISPUF08$HEP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #4"
label(NISPUF08$HEP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #5"
label(NISPUF08$HEP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #6"
label(NISPUF08$HEP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #7"
label(NISPUF08$HEP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #8"

label(NISPUF08$HEP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HEPATITIS B-CONTAINING SHOT #9"
label(NISPUF08$HIB1_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #1"
label(NISPUF08$HIB2_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #2"
label(NISPUF08$HIB3_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #3"
label(NISPUF08$HIB4_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #4"

label(NISPUF08$HIB5_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #5"
label(NISPUF08$HIB6_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #6"
label(NISPUF08$HIB7_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #7"
label(NISPUF08$HIB8_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #8"
label(NISPUF08$HIB9_AGE) <- "AGE IN MONTHS OF PROV-REPTD HIB-CONTAINING SHOT #9"

label(NISPUF08$MMR1_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #1"
label(NISPUF08$MMR2_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #2"
label(NISPUF08$MMR3_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #3"
label(NISPUF08$MMR4_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #4"
label(NISPUF08$MMR5_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #5"

label(NISPUF08$MMR6_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #6"
label(NISPUF08$MMR7_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #7"
label(NISPUF08$MMR8_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #8"
label(NISPUF08$MMR9_AGE) <- "AGE IN MONTHS OF PROV-REPTD MEASLES-CONTAINING SHOT #9"
label(NISPUF08$MP1_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #1"

label(NISPUF08$MP2_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #2"
label(NISPUF08$MP3_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #3"
label(NISPUF08$MP4_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #4"
label(NISPUF08$MP5_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #5"
label(NISPUF08$MP6_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #6"

label(NISPUF08$MP7_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #7"
label(NISPUF08$MP8_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #8"
label(NISPUF08$MP9_AGE) <- "AGE IN MONTHS OF PROV-REPTD MUMPS-ONLY SHOT #9"
label(NISPUF08$MPR1_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #1"
label(NISPUF08$MPR2_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #2"

label(NISPUF08$MPR3_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #3"
label(NISPUF08$MPR4_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #4"
label(NISPUF08$MPR5_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #5"
label(NISPUF08$MPR6_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #6"
label(NISPUF08$MPR7_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #7"

label(NISPUF08$MPR8_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #8"
label(NISPUF08$MPR9_AGE) <- "AGE IN MONTHS OF PROV-REPTD (MUMPS/RUBELLA)-ONLY SHOT #9"
label(NISPUF08$PCV1_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #1"
label(NISPUF08$PCV2_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #2"
label(NISPUF08$PCV3_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #3"

label(NISPUF08$PCV4_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #4"
label(NISPUF08$PCV5_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #5"
label(NISPUF08$PCV6_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #6"
label(NISPUF08$PCV7_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #7"
label(NISPUF08$PCV8_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #8"

label(NISPUF08$PCV9_AGE) <- "AGE IN MONTHS OF PROV-REPTD PNEUMOCOCCAL-CONTAINING SHOT #9"
label(NISPUF08$POL1_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #1"
label(NISPUF08$POL2_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #2"
label(NISPUF08$POL3_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #3"
label(NISPUF08$POL4_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #4"

label(NISPUF08$POL5_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #5"
label(NISPUF08$POL6_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #6"
label(NISPUF08$POL7_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #7"
label(NISPUF08$POL8_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #8"
label(NISPUF08$POL9_AGE) <- "AGE IN MONTHS OF PROV-REPTD POLIO-CONTAINING SHOT #9"

label(NISPUF08$RB1_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #1"
label(NISPUF08$RB2_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #2"
label(NISPUF08$RB3_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #3"
label(NISPUF08$RB4_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #4"
label(NISPUF08$RB5_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #5"

label(NISPUF08$RB6_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #6"
label(NISPUF08$RB7_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #7"
label(NISPUF08$RB8_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #8"
label(NISPUF08$RB9_AGE) <- "AGE IN MONTHS OF PROV-REPTD RUBELLA-ONLY SHOT #9"
label(NISPUF08$ROT1_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #1"

label(NISPUF08$ROT2_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #2"
label(NISPUF08$ROT3_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #3"
label(NISPUF08$ROT4_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #4"
label(NISPUF08$ROT5_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #5"
label(NISPUF08$ROT6_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #6"

label(NISPUF08$ROT7_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #7"
label(NISPUF08$ROT8_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #8"
label(NISPUF08$ROT9_AGE) <- "AGE IN MONTHS OF PROV-REPTD ROTAVIRUS-CONTAINING SHOT #9"
label(NISPUF08$VRC1_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #1"
label(NISPUF08$VRC2_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #2"

label(NISPUF08$VRC3_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #3"
label(NISPUF08$VRC4_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #4"
label(NISPUF08$VRC5_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #5"
label(NISPUF08$VRC6_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #6"
label(NISPUF08$VRC7_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #7"

label(NISPUF08$VRC8_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #8"
label(NISPUF08$VRC9_AGE) <- "AGE IN MONTHS OF PROV-REPTD VARICELLA-CONTAINING SHOT #9"
label(NISPUF08$XDTPTY1) <- "DT-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF08$XDTPTY2) <- "DT-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF08$XDTPTY3) <- "DT-CONTAINING VACCINATION #3 TYPE CODE"

label(NISPUF08$XDTPTY4) <- "DT-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF08$XDTPTY5) <- "DT-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF08$XDTPTY6) <- "DT-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF08$XDTPTY7) <- "DT-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF08$XDTPTY8) <- "DT-CONTAINING VACCINATION #8 TYPE CODE"

label(NISPUF08$XDTPTY9) <- "DT-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF08$XFLUTY1) <- "FLU-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF08$XFLUTY2) <- "FLU-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF08$XFLUTY3) <- "FLU-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF08$XFLUTY4) <- "FLU-CONTAINING VACCINATION #4 TYPE CODE"

label(NISPUF08$XFLUTY5) <- "FLU-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF08$XFLUTY6) <- "FLU-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF08$XFLUTY7) <- "FLU-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF08$XFLUTY8) <- "FLU-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF08$XFLUTY9) <- "FLU-CONTAINING VACCINATION #9 TYPE CODE"

label(NISPUF08$XHEPTY1) <- "HEPATITIS B-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF08$XHEPTY2) <- "HEPATITIS B-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF08$XHEPTY3) <- "HEPATITIS B-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF08$XHEPTY4) <- "HEPATITIS B-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF08$XHEPTY5) <- "HEPATITIS B-CONTAINING VACCINATION #5 TYPE CODE"

label(NISPUF08$XHEPTY6) <- "HEPATITIS B-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF08$XHEPTY7) <- "HEPATITIS B-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF08$XHEPTY8) <- "HEPATITIS B-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF08$XHEPTY9) <- "HEPATITIS B-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF08$XHIBTY1) <- "HIB-CONTAINING VACCINATION #1 TYPE CODE"

label(NISPUF08$XHIBTY2) <- "HIB-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF08$XHIBTY3) <- "HIB-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF08$XHIBTY4) <- "HIB-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF08$XHIBTY5) <- "HIB-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF08$XHIBTY6) <- "HIB-CONTAINING VACCINATION #6 TYPE CODE"

label(NISPUF08$XHIBTY7) <- "HIB-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF08$XHIBTY8) <- "HIB-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF08$XHIBTY9) <- "HIB-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF08$XMMRTY1) <- "MEASLES-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF08$XMMRTY2) <- "MEASLES-CONTAINING VACCINATION #2 TYPE CODE"

label(NISPUF08$XMMRTY3) <- "MEASLES-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF08$XMMRTY4) <- "MEASLES-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF08$XMMRTY5) <- "MEASLES-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF08$XMMRTY6) <- "MEASLES-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF08$XMMRTY7) <- "MEASLES-CONTAINING VACCINATION #7 TYPE CODE"

label(NISPUF08$XMMRTY8) <- "MEASLES-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF08$XMMRTY9) <- "MEASLES-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF08$XPCVTY1) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF08$XPCVTY2) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF08$XPCVTY3) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #3 TYPE CODE"

label(NISPUF08$XPCVTY4) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF08$XPCVTY5) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF08$XPCVTY6) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF08$XPCVTY7) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF08$XPCVTY8) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #8 TYPE CODE"

label(NISPUF08$XPCVTY9) <- "PNEUMOCOCCAL-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF08$XPOLTY1) <- "POLIO-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF08$XPOLTY2) <- "POLIO-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF08$XPOLTY3) <- "POLIO-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF08$XPOLTY4) <- "POLIO-CONTAINING VACCINATION #4 TYPE CODE"

label(NISPUF08$XPOLTY5) <- "POLIO-CONTAINING VACCINATION #5 TYPE CODE"
label(NISPUF08$XPOLTY6) <- "POLIO-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF08$XPOLTY7) <- "POLIO-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF08$XPOLTY8) <- "POLIO-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF08$XPOLTY9) <- "POLIO-CONTAINING VACCINATION #9 TYPE CODE"

label(NISPUF08$XVRCTY1) <- "VARICELLA-CONTAINING VACCINATION #1 TYPE CODE"
label(NISPUF08$XVRCTY2) <- "VARICELLA-CONTAINING VACCINATION #2 TYPE CODE"
label(NISPUF08$XVRCTY3) <- "VARICELLA-CONTAINING VACCINATION #3 TYPE CODE"
label(NISPUF08$XVRCTY4) <- "VARICELLA-CONTAINING VACCINATION #4 TYPE CODE"
label(NISPUF08$XVRCTY5) <- "VARICELLA-CONTAINING VACCINATION #5 TYPE CODE"

label(NISPUF08$XVRCTY6) <- "VARICELLA-CONTAINING VACCINATION #6 TYPE CODE"
label(NISPUF08$XVRCTY7) <- "VARICELLA-CONTAINING VACCINATION #7 TYPE CODE"
label(NISPUF08$XVRCTY8) <- "VARICELLA-CONTAINING VACCINATION #8 TYPE CODE"
label(NISPUF08$XVRCTY9) <- "VARICELLA-CONTAINING VACCINATION #9 TYPE CODE"
label(NISPUF08$INS_1) <- "IS CHILD COVERED BY HEALTH INSURANCE PROVIDED THROUGH EMPLOYER OR UNION?"

label(NISPUF08$INS_2) <- "IS CHILD COVERED BY ANY MEDICAID PLAN?"
label(NISPUF08$INS_3) <- "IS CHILD COVERED BY S-CHIP?"
label(NISPUF08$INS_3A) <- "IS CHILD COVERED BY ANY MEDICAID PLAN OR S-CHIP?"
label(NISPUF08$INS_4) <- "IS CHILD COVERED BY INDIAN HEALTH SERVICE?"
label(NISPUF08$INS_5) <- "IS CHILD COVERED BY MILITARY HEALTH CARE, TRICARE, CHAMPUS, OR CHAMP-VA?"

label(NISPUF08$INS_6) <- "IS CHILD COVERED BY ANY OTHER HEALTH INSURANCE OR HEALTH CARE PLAN?"
label(NISPUF08$INS_11) <- "ANY TIME WHEN CHILD WAS NOT COVERED BY ANY HEALTH INSURANCE?"

############################################################################
# Step 5:   CREATE A PERMANENT R DATASET                                   #
############################################################################

save(NISPUF08, file=paste(PUF, "/NISPUF08.RData", sep=""))

############################################################################
# Step 6:   ASSIGN FORMATS                                                 #
#	  FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES	IN R           #
############################################################################

NISPUF08$AGEGRP <- factor(NISPUF08$AGEGRP, levels=AGEGRPlevels, labels=AGEGRPlabels)
NISPUF08$LANGUAGE <- factor(NISPUF08$LANGUAGE, levels=LANGUAGElevels, labels=LANGUAGElabels)
NISPUF08$HAD_CPOX <- factor(NISPUF08$HAD_CPOX, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$CBF_01 <- factor(NISPUF08$CBF_01, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$CWIC_02 <- factor(NISPUF08$CWIC_02, levels=YNDKRFlevels, labels=YNDKRFlabels)

NISPUF08$INTRP <- factor(NISPUF08$INTRP, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$INS_1 <- factor(NISPUF08$INS_1, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$INS_2 <- factor(NISPUF08$INS_2, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$INS_3 <- factor(NISPUF08$INS_3, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$INS_3A <- factor(NISPUF08$INS_3A, levels=YNDKRFlevels, labels=YNDKRFlabels)

NISPUF08$INS_4 <- factor(NISPUF08$INS_4, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$INS_5 <- factor(NISPUF08$INS_5, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$INS_6 <- factor(NISPUF08$INS_6, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$INS_11 <- factor(NISPUF08$INS_11, levels=YNDKRFlevels, labels=YNDKRFlabels)
NISPUF08$P_NUHEPX <- factor(NISPUF08$P_NUHEPX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF08$P_NUHIBX <- factor(NISPUF08$P_NUHIBX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUHPHB <- factor(NISPUF08$P_NUHPHB, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMDAH <- factor(NISPUF08$P_NUMDAH, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMDHB <- factor(NISPUF08$P_NUMDHB, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMDHI <- factor(NISPUF08$P_NUMDHI, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF08$P_NUMDHM <- factor(NISPUF08$P_NUMDHM, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMDTA <- factor(NISPUF08$P_NUMDTA, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMDTM <- factor(NISPUF08$P_NUMDTM, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMDTP <- factor(NISPUF08$P_NUMDTP, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMFLU <- factor(NISPUF08$P_NUMFLU, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF08$P_NUMFLUL <- factor(NISPUF08$P_NUMFLUL, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMFLUM <- factor(NISPUF08$P_NUMFLUM, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMFLUN <- factor(NISPUF08$P_NUMFLUN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMHEA <- factor(NISPUF08$P_NUMHEA, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMHEN <- factor(NISPUF08$P_NUMHEN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF08$P_NUMHEP <- factor(NISPUF08$P_NUMHEP, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMHIB <- factor(NISPUF08$P_NUMHIB, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMHIN <- factor(NISPUF08$P_NUMHIN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMIPV <- factor(NISPUF08$P_NUMIPV, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMMCN <- factor(NISPUF08$P_NUMMCN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF08$P_NUMMMR <- factor(NISPUF08$P_NUMMMR, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMMMRX <- factor(NISPUF08$P_NUMMMRX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMMMX <- factor(NISPUF08$P_NUMMMX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMMP <- factor(NISPUF08$P_NUMMP, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMMPR <- factor(NISPUF08$P_NUMMPR, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF08$P_NUMMRV <- factor(NISPUF08$P_NUMMRV, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMMS <- factor(NISPUF08$P_NUMMS, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMMSM <- factor(NISPUF08$P_NUMMSM, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMMSR <- factor(NISPUF08$P_NUMMSR, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMOLN <- factor(NISPUF08$P_NUMOLN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF08$P_NUMOPV <- factor(NISPUF08$P_NUMOPV, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMPCC <- factor(NISPUF08$P_NUMPCC, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMPCN <- factor(NISPUF08$P_NUMPCN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMPCP <- factor(NISPUF08$P_NUMPCP, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMPCV <- factor(NISPUF08$P_NUMPCV, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF08$P_NUMPOL <- factor(NISPUF08$P_NUMPOL, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMRB <- factor(NISPUF08$P_NUMRB, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMROT <- factor(NISPUF08$P_NUMROT, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMTPM <- factor(NISPUF08$P_NUMTPM, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMTPN <- factor(NISPUF08$P_NUMTPN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)

NISPUF08$P_NUMVRC <- factor(NISPUF08$P_NUMVRC, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMVRN <- factor(NISPUF08$P_NUMVRN, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$P_NUMVRX <- factor(NISPUF08$P_NUMVRX, levels=SHOTCOUNlevels, labels=SHOTCOUNlabels)
NISPUF08$SC_431 <- factor(NISPUF08$SC_431, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF08$SC_4313 <- factor(NISPUF08$SC_4313, levels=SCUTDlevels, labels=SCUTDlabels)

NISPUF08$SC_43133 <- factor(NISPUF08$SC_43133, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF08$SC_DTP <- factor(NISPUF08$SC_DTP, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF08$SC_HEPB <- factor(NISPUF08$SC_HEPB, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF08$SC_HIB <- factor(NISPUF08$SC_HIB, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF08$SC_MCV <- factor(NISPUF08$SC_MCV, levels=SCUTDlevels, labels=SCUTDlabels)

NISPUF08$SC_POL <- factor(NISPUF08$SC_POL, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF08$SC_VRC <- factor(NISPUF08$SC_VRC, levels=SCUTDlevels, labels=SCUTDlabels)
NISPUF08$HH_DTP <- factor(NISPUF08$HH_DTP, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF08$HH_FLU <- factor(NISPUF08$HH_FLU, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF08$HH_HEPB <- factor(NISPUF08$HH_HEPB, levels=HHNUMlevels, labels=HHNUMlabels)

NISPUF08$HH_HIB <- factor(NISPUF08$HH_HIB, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF08$HH_MCV <- factor(NISPUF08$HH_MCV, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF08$HH_POL <- factor(NISPUF08$HH_POL, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF08$HH_VRC <- factor(NISPUF08$HH_VRC, levels=HHNUMlevels, labels=HHNUMlabels)
NISPUF08$D7 <- factor(NISPUF08$D7, levels=YNlevels, labels=YNlabels)

NISPUF08$SHOTCARD <- factor(NISPUF08$SHOTCARD, levels=SHOTCARDlevels, labels=SHOTCARDlabels)
NISPUF08$BFENDFL06 <- factor(NISPUF08$BFENDFL06, levels=Ylevels, labels=Ylabels)
NISPUF08$BFFORMFL06 <- factor(NISPUF08$BFFORMFL06, levels=Ylevels, labels=Ylabels)
NISPUF08$CHILDNM <- factor(NISPUF08$CHILDNM, levels=CHILDNMlevels, labels=CHILDNMlabels)
NISPUF08$CWIC_01 <- factor(NISPUF08$CWIC_01, levels=CWIClevels, labels=CWIClabels)

NISPUF08$EDUC1 <- factor(NISPUF08$EDUC1, levels=EDUC1_levels, labels=EDUC1_labels)
NISPUF08$I_HISP_K <- factor(NISPUF08$I_HISP_K, levels=HISPlevels, labels=HISPlabels)
NISPUF08$M_AGEGRP <- factor(NISPUF08$M_AGEGRP, levels=MAGEGRPlevels, labels=MAGEGRPlabels)
NISPUF08$MOBIL_I <- factor(NISPUF08$MOBIL_I, levels=MOBILlevels, labels=MOBILlabels)
NISPUF08$SEX <- factor(NISPUF08$SEX, levels=SEXlevels, labels=SEXlabels)

NISPUF08$INCPOV1 <- factor(NISPUF08$INCPOV1, levels=INCPOVlevels, labels=INCPOVlabels)
NISPUF08$DISPCODE <- factor(NISPUF08$DISPCODE, levels=DISPlevels, labels=DISPlabels)
NISPUF08$PDAT <- factor(NISPUF08$PDAT, levels=HASPDA2Flevels, labels=HASPDA2Flabels)
NISPUF08$PROV_FAC <- factor(NISPUF08$PROV_FAC, levels=PROVIDlevels, labels=PROVIDlabels)
NISPUF08$REGISTRY <- factor(NISPUF08$REGISTRY, levels=REGISTRYlevels, labels=REGISTRYlabels)

NISPUF08$VFC_ORDER <- factor(NISPUF08$VFC_ORDER, levels=REGISTRYlevels, labels=REGISTRYlabels)
NISPUF08$XDTPTY1 <- factor(NISPUF08$XDTPTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XDTPTY2 <- factor(NISPUF08$XDTPTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XDTPTY3 <- factor(NISPUF08$XDTPTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XDTPTY4 <- factor(NISPUF08$XDTPTY4, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XDTPTY5 <- factor(NISPUF08$XDTPTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XDTPTY6 <- factor(NISPUF08$XDTPTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XDTPTY7 <- factor(NISPUF08$XDTPTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XDTPTY8 <- factor(NISPUF08$XDTPTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XDTPTY9 <- factor(NISPUF08$XDTPTY9, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XFLUTY1 <- factor(NISPUF08$XFLUTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XFLUTY2 <- factor(NISPUF08$XFLUTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XFLUTY3 <- factor(NISPUF08$XFLUTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XFLUTY4 <- factor(NISPUF08$XFLUTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XFLUTY5 <- factor(NISPUF08$XFLUTY5, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XFLUTY6 <- factor(NISPUF08$XFLUTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XFLUTY7 <- factor(NISPUF08$XFLUTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XFLUTY8 <- factor(NISPUF08$XFLUTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XFLUTY9 <- factor(NISPUF08$XFLUTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHEPTY1 <- factor(NISPUF08$XHEPTY1, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XHEPTY2 <- factor(NISPUF08$XHEPTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHEPTY3 <- factor(NISPUF08$XHEPTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHEPTY4 <- factor(NISPUF08$XHEPTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHEPTY5 <- factor(NISPUF08$XHEPTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHEPTY6 <- factor(NISPUF08$XHEPTY6, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XHEPTY7 <- factor(NISPUF08$XHEPTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHEPTY8 <- factor(NISPUF08$XHEPTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHEPTY9 <- factor(NISPUF08$XHEPTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHIBTY1 <- factor(NISPUF08$XHIBTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHIBTY2 <- factor(NISPUF08$XHIBTY2, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XHIBTY3 <- factor(NISPUF08$XHIBTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHIBTY4 <- factor(NISPUF08$XHIBTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHIBTY5 <- factor(NISPUF08$XHIBTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHIBTY6 <- factor(NISPUF08$XHIBTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHIBTY7 <- factor(NISPUF08$XHIBTY7, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XHIBTY8 <- factor(NISPUF08$XHIBTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XHIBTY9 <- factor(NISPUF08$XHIBTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XMMRTY1 <- factor(NISPUF08$XMMRTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XMMRTY2 <- factor(NISPUF08$XMMRTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XMMRTY3 <- factor(NISPUF08$XMMRTY3, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XMMRTY4 <- factor(NISPUF08$XMMRTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XMMRTY5 <- factor(NISPUF08$XMMRTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XMMRTY6 <- factor(NISPUF08$XMMRTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XMMRTY7 <- factor(NISPUF08$XMMRTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XMMRTY8 <- factor(NISPUF08$XMMRTY8, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XMMRTY9 <- factor(NISPUF08$XMMRTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPCVTY1 <- factor(NISPUF08$XPCVTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPCVTY2 <- factor(NISPUF08$XPCVTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPCVTY3 <- factor(NISPUF08$XPCVTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPCVTY4 <- factor(NISPUF08$XPCVTY4, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XPCVTY5 <- factor(NISPUF08$XPCVTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPCVTY6 <- factor(NISPUF08$XPCVTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPCVTY7 <- factor(NISPUF08$XPCVTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPCVTY8 <- factor(NISPUF08$XPCVTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPCVTY9 <- factor(NISPUF08$XPCVTY9, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XPOLTY1 <- factor(NISPUF08$XPOLTY1, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPOLTY2 <- factor(NISPUF08$XPOLTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPOLTY3 <- factor(NISPUF08$XPOLTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPOLTY4 <- factor(NISPUF08$XPOLTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPOLTY5 <- factor(NISPUF08$XPOLTY5, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XPOLTY6 <- factor(NISPUF08$XPOLTY6, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPOLTY7 <- factor(NISPUF08$XPOLTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPOLTY8 <- factor(NISPUF08$XPOLTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XPOLTY9 <- factor(NISPUF08$XPOLTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XVRCTY1 <- factor(NISPUF08$XVRCTY1, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XVRCTY2 <- factor(NISPUF08$XVRCTY2, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XVRCTY3 <- factor(NISPUF08$XVRCTY3, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XVRCTY4 <- factor(NISPUF08$XVRCTY4, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XVRCTY5 <- factor(NISPUF08$XVRCTY5, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XVRCTY6 <- factor(NISPUF08$XVRCTY6, levels=TYPElevels, labels=TYPElabels)

NISPUF08$XVRCTY7 <- factor(NISPUF08$XVRCTY7, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XVRCTY8 <- factor(NISPUF08$XVRCTY8, levels=TYPElevels, labels=TYPElabels)
NISPUF08$XVRCTY9 <- factor(NISPUF08$XVRCTY9, levels=TYPElevels, labels=TYPElabels)
NISPUF08$HEP_BRTH <- factor(NISPUF08$HEP_BRTH, levels=HEPBRTlevels, labels=HEPBRTlabels)
NISPUF08$HEP_FLAG <- factor(NISPUF08$HEP_FLAG, levels=HEPFLGlevels, labels=HEPFLGlabels)

NISPUF08$P_U12VRC <- factor(NISPUF08$P_U12VRC, levels=UTDlevels, labels=UTDlabels)
NISPUF08$P_UTD331 <- factor(NISPUF08$P_UTD331, levels=UTDlevels, labels=UTDlabels)
NISPUF08$P_UTD431 <- factor(NISPUF08$P_UTD431, levels=UTDlevels, labels=UTDlabels)
NISPUF08$P_UTDHEP <- factor(NISPUF08$P_UTDHEP, levels=UTDlevels, labels=UTDlabels)
NISPUF08$P_UTDHIB <- factor(NISPUF08$P_UTDHIB, levels=UTDlevels, labels=UTDlabels)

NISPUF08$P_UTDMCV <- factor(NISPUF08$P_UTDMCV, levels=UTDlevels, labels=UTDlabels)
NISPUF08$P_UTDMMX <- factor(NISPUF08$P_UTDMMX, levels=UTDlevels, labels=UTDlabels)
NISPUF08$P_UTDPC3 <- factor(NISPUF08$P_UTDPC3, levels=UTDlevels, labels=UTDlabels)
NISPUF08$P_UTDPCV <- factor(NISPUF08$P_UTDPCV, levels=UTDlevels, labels=UTDlabels)
NISPUF08$P_UTDPOL <- factor(NISPUF08$P_UTDPOL, levels=UTDlevels, labels=UTDlabels)

NISPUF08$P_UTDTP3 <- factor(NISPUF08$P_UTDTP3, levels=UTDlevels, labels=UTDlabels)
NISPUF08$P_UTDTP4 <- factor(NISPUF08$P_UTDTP4, levels=UTDlevels, labels=UTDlabels)
NISPUF08$PU431331 <- factor(NISPUF08$PU431331, levels=UTDlevels, labels=UTDlabels)
NISPUF08$PU4313313 <- factor(NISPUF08$PU4313313, levels=UTDlevels, labels=UTDlabels)
NISPUF08$PU4313314 <- factor(NISPUF08$PU4313314, levels=UTDlevels, labels=UTDlabels)

NISPUF08$PUT43133 <- factor(NISPUF08$PUT43133, levels=UTDlevels, labels=UTDlabels)
NISPUF08$PUTD4313 <- factor(NISPUF08$PUTD4313, levels=UTDlevels, labels=UTDlabels)
NISPUF08$CEN_REG <- factor(NISPUF08$CEN_REG, levels=CENREGlevels, labels=CENREGlabels)
NISPUF08$STATE <- factor(NISPUF08$STATE, levels=STATElevels, labels=STATElabels)
NISPUF08$P_UTDFL1 <- factor(NISPUF08$P_UTDFL1, levels=FLUUTDlevels, labels=FLUUTDlabels)

NISPUF08$P_UTDFL2 <- factor(NISPUF08$P_UTDFL2, levels=FLUUTDlevels, labels=FLUUTDlabels)
NISPUF08$P_UTDFL3 <- factor(NISPUF08$P_UTDFL3, levels=FLUUTDlevels, labels=FLUUTDlabels)
NISPUF08$RACE_K <- factor(NISPUF08$RACE_K, levels=RACE_PUFlevels, labels=RACE_PUFlabels)
NISPUF08$MARITAL <- factor(NISPUF08$MARITAL, levels=MAR_PUFlevels, labels=MAR_PUFlabels)
NISPUF08$AGECPOXR <- factor(NISPUF08$AGECPOXR, levels=AGECPOXRlevels, labels=AGECPOXRlabels)

NISPUF08$C1R <- factor(NISPUF08$C1R, levels=C1Rlevels, labels=C1Rlabels)
NISPUF08$C5R <- factor(NISPUF08$C5R, levels=C5Rlevels, labels=C5Rlabels)
NISPUF08$INOPHONR <- factor(NISPUF08$INOPHONR, levels=INOPHONRlevels, labels=INOPHONRlabels)
NISPUF08$INCQ298A <- factor(NISPUF08$INCQ298A, levels=INCQ298Alevels, labels=INCQ298Alabels)
NISPUF08$RACEETHK <- factor(NISPUF08$RACEETHK, levels=RACEETHKlevels, labels=RACEETHKlabels)

NISPUF08$D6R <- factor(NISPUF08$D6R, levels=D6Rlevels, labels=D6Rlabels)
NISPUF08$N_PRVR <- factor(NISPUF08$N_PRVR, levels=D6Rlevels, labels=D6Rlabels)
NISPUF08$FRSTBRN <- factor(NISPUF08$FRSTBRN, levels=FRSTBRNlevels, labels=FRSTBRNlabels)
NISPUF08$SEQNUMC <- factor(NISPUF08$SEQNUMC, levels=CHARIDlevels, labels=CHARIDlabels)
NISPUF08$SEQNUMHH <- factor(NISPUF08$SEQNUMHH, levels=CHARIDlevels, labels=CHARIDlabels)

NISPUF08$BF_FORMR08 <- factor(NISPUF08$BF_FORMR08, levels=BFFORM08Flevels, labels=BFFORM08Flabels)
NISPUF08$ESTIAP08 <- factor(NISPUF08$ESTIAP08, levels=ESTIAP08Flevels, labels=ESTIAP08Flabels)

##########################################################################
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE        #
##########################################################################

#---CONTENTS---#
NISPUF08.CONTENTS <- contents(NISPUF08)$contents

print(NISPUF08.CONTENTS)

#IN CASE THAT THE R CONSOLE CANNOT DISPLAY WHOLE CONTENTS,
#YOU CAN SAVE CONTENTS INTO A FILE
#write.table(NISPUF08.CONTENTS, file=paste(PUF,"/file-name",sep=""))

#---UNWEIGHTED FREQUENCY---#
unwt_freq <- function(UNWT.VAR){#FUNCTION TO PRINT UNWEIGHTED FREQUENCIES

unwt.tab <- wtd.table(UNWT.VAR, weights= NULL, type='table')
unwtd.freq <- data.frame(cbind(
unwt.tab, round(unwt.tab/sum(unwt.tab)*100,2),
cumsum(unwt.tab), cumsum(round(unwt.tab/sum(unwt.tab)*100,2))))
names(unwtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
unwtd.title <- paste('2008 NIS', 'UNWEIGHTED FREQUENCIES', label(UNWT.VAR), sep="\n")
label(unwtd.freq) <- unwtd.title

print(unwtd.freq)
}

UNWT.VAR <- NISPUF08$AGEGRP	#INPUT A VARIABLE OF INTEREST
unwt_freq(UNWT.VAR)

#---WEIGHTED FREQUENCY---#
WT <- NISPUF08$RDDWT		#INPUT A WEIGHT VARIABLE
WT.VAR <- NISPUF08$AGEGRP	#INPUT A VARIABLE OF INTEREST

wt.tab <- wtd.table(WT.VAR, weights= WT, type='table')
wtd.freq <- data.frame(cbind(
wt.tab, round(wt.tab/sum(wt.tab)*100,2),
cumsum(wt.tab), cumsum(round(wt.tab/sum(wt.tab)*100,2))))
names(wtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
wtd.title <- paste('2008 NIS PUBLIC USE FILE', 'WEIGHTED FREQUENCIES', label(WT.VAR), sep="\n")
label(wtd.freq) <- wtd.title

print(wtd.freq)
