---
title: "Initial immunity by state, age, and pathogen"
author: "Mathew Kiang"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

# eTables S2-S5. Initial immunity by state, age, and pathogen

```{r data, results='hide'}
## Imports ----
library(tidyverse)
library(duckdb)
library(here)
library(kableExtra)
library(knitr)
source(here("code", "utils.R"))
```

## Measles

```{r}
map_dfr(.x = c("DC", state.abb),
    .f = ~ {
        tibble(
            state = .x,
            age = seq(0, 85, 5),
            rate = return_initial_immunity(
                state_abbrev = .x,
                pathogen_x = "measles"
            )
        )
    }) |> 
    arrange(state, age) |>
    mutate(label = sprintf("%0.1f", round(rate * 100, 1))) |> 
    select(-rate) |> 
    pivot_wider(values_from = "label", names_from = "age") |> 
    kable(format = "html") |>
    kable_styling("striped", full_width = TRUE)
    
```
## Rubella

```{r}
map_dfr(.x = c("DC", state.abb),
    .f = ~ {
        tibble(
            state = .x,
            age = seq(0, 85, 5),
            rate = return_initial_immunity(
                state_abbrev = .x,
                pathogen_x = "rubella"
            )
        )
    }) |> 
    arrange(state, age) |>
    mutate(label = sprintf("%0.1f", round(rate * 100, 1))) |> 
    select(-rate) |> 
    pivot_wider(values_from = "label", names_from = "age") |> 
    kable(format = "html") |>
    kable_styling("striped", full_width = TRUE)
```

## Diphtheria

```{r}
map_dfr(.x = c("DC", state.abb),
    .f = ~ {
        tibble(
            state = .x,
            age = seq(0, 85, 5),
            rate = return_initial_immunity(
                state_abbrev = .x,
                pathogen_x = "diphtheria"
            )
        )
    }) |> 
    arrange(state, age) |>
    mutate(label = sprintf("%0.1f", round(rate * 100, 1))) |> 
    select(-rate) |> 
    pivot_wider(values_from = "label", names_from = "age") |> 
    kable(format = "html") |>
    kable_styling("striped", full_width = TRUE)
    
```

## Polio

```{r}
map_dfr(.x = c("DC", state.abb),
    .f = ~ {
        tibble(
            state = .x,
            age = seq(0, 85, 5),
            rate = return_initial_immunity(
                state_abbrev = .x,
                pathogen_x = "polio"
            )
        )
    }) |> 
    arrange(state, age) |>
    mutate(label = sprintf("%0.1f", round(rate * 100, 1))) |> 
    select(-rate) |> 
    pivot_wider(values_from = "label", names_from = "age") |> 
    kable(format = "html") |>
    kable_styling("striped", full_width = TRUE)
    
```

